# Agent Repair Pipeline — HotpotQA

**ICLR Experiment Pipeline — Colab A100-80GB + Qwen2.5-32B-Instruct-AWQ**

| Stage | What it does | ~Time (A100-80GB, 500 Qs) |
|---|---|---|
| 0 | Download HotpotQA, create folders | 1 min |
| 1 | ReAct trajectory generation (Qwen2.5-32B-Instruct-AWQ) | ~1-2 h |
| 2 | Step-level uncertainty scoring | ~1-2 h |
| 3 | 72B judge error annotation | ~1-2 h |
| 4 | Localization scoring (+ cascade-aware rules) | < 1 min |
| 5 | 126 repair strategies (backtrack × nudge type ablation) | ~4-6 h |
| 6 | Tables, stats, figures, ablation analysis | < 1 min |

**Every stage is resumable** — if Colab disconnects, re-run the cell and it picks up where it left off.

---
## 0. Setup

In [1]:
# Verify GPU — should show A100
!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

NVIDIA A100-SXM4-80GB, 81920 MiB

In [2]:
# Mount Google Drive for persistent storage
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_hotpotqa.yaml'

if not os.path.exists(REPO_DIR):
    !git clone https://github.com/kishormorol/agent-repair.git {REPO_DIR}
else:
    !cd {REPO_DIR} && git pull

os.chdir(REPO_DIR)
print(f'Working directory: {os.getcwd()}')

Cloning into '/content/agent-repair'...
remote: Enumerating objects: 203, done.
remote: Counting objects: 100% (203/203), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 203 (delta 104), reused 164 (delta 65), pack-reused 0 (from 0)
Receiving objects: 100% (203/203), 261.91 KiB | 1.26 MiB/s, done.
Resolving deltas: 100% (104/104), done.
Working directory: /content/agent-repair

In [4]:
# Check Colab's CUDA version first
!nvcc --version 2>/dev/null || echo "nvcc not found"
!python -c "import torch; print(f'torch CUDA: {torch.version.cuda}')" 2>/dev/null || echo "torch not installed yet"
!nvidia-smi | grep "CUDA Version"

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0
torch CUDA: 12.8
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |

In [5]:
# Install vLLM — pinned to 0.19.0 (last version with CUDA 12 default wheels)
# vLLM >= 0.20 ships CUDA 13 wheels which don't work on Colab's CUDA 12.x
!pip uninstall -y vllm 2>/dev/null
!pip install -q "vllm==0.19.0" 2>&1 | tail -5

# Install remaining dependencies
!pip install -q "transformers>=4.57.0" "tokenizers>=0.21.0" accelerate \
    huggingface_hub datasets scipy scikit-learn pandas pyarrow \
    pyyaml tqdm matplotlib seaborn statsmodels 2>&1 | tail -3

print('\n--- Installation complete ---')

gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.6 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.6 which is incompatible.
google-adk 2.4.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.4.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.

--- Installation complete ---

In [6]:
# Quick sanity check: can vLLM see the GPU?
import torch, vllm
print(f'torch:  {torch.__version__}')
print(f'vLLM:   {vllm.__version__}')
print(f'CUDA:   {torch.version.cuda}')
print(f'GPU:    {torch.cuda.get_device_name(0)}')
print(f'VRAM:   {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

torch:  2.10.0+cu128
vLLM:   0.19.0
CUDA:   12.8
GPU:    NVIDIA A100-SXM4-80GB
VRAM:   85.1 GB

In [7]:
# Clear previous data
import shutil, os
drive_base = '/content/drive/MyDrive/agent-repair-hotpotqa'
for d in ['outputs', 'data/processed']:
    p = os.path.join(drive_base, d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
for d in ['outputs', 'data/processed']:
    p = os.path.join('/content/agent-repair', d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
print('Ready for fresh run with HotpotQA')

Ready for fresh run with HotpotQA

---
## Smoke Test (20 questions, ~10-15 min)

**Run this first** to verify everything works before committing A100 units to the full 500-question run.

In [8]:
stages = ['run_setup', 'run_generate', 'run_uncertainty', 'run_annotate',
          'run_localize', 'run_repair', 'run_eval']

for stage in stages:
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG} --limit 20
    print()

============================================================
  run_setup
============================================================
05:42:10 | INFO    | setup | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
05:42:10 | INFO    | setup | Dataset: hotpotqa (file: hotpot_dev_distractor_v1.json)
Trying direct: http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json
  failed: <urlopen error timed out>
Trying direct: https://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json
  failed: <urlopen error timed out>
05:42:50 | INFO    | setup | Direct download unavailable -> Hugging Face fallback
`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'hotpotqa/hotpot_qa' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
README.md: 9.52kB [00:00, 38.5MB/s]
distractor/train-00000-of-00002.parquet: 100% 166M/166M [00:02<00:00, 59.2MB/s]
distractor/train-00001-of-00002.parquet: 100% 166M/166M [00:01<00:00, 83.1MB/s]
distractor/validation-00000-of-00001.par(…): 100% 27.5M/27.5M [00:00<00:00, 34.2MB/s]
Generating train split: 100% 90447/90447 [00:02<00:00, 41508.08 examples/s]
Generating validation split: 100% 7405/7405 [00:00<00:00, 46208.72 examples/s]
05:43:07 | INFO    | setup | Converted 7405 questions from Hugging Face.
05:43:07 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-hotpotqa/data/raw/hotpot_dev_distractor_v1.json (46.8 MB, 7405 questions)
05:43:07 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-hotpotqa


============================================================
  run_generate
============================================================
05:43:08 | INFO    | stage1 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
05:43:08 | INFO    | stage1 | Dataset: hotpotqa (env: HotpotEnv)
05:43:08 | INFO    | stage1 | Pool: 500 questions
05:43:08 | INFO    | stage1 | To process: 20 of 20 (0 already done)
05:43:10 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 05:43:13.906697: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 05:43:13.978285: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tokenizer_config.json: 7.30kB [00:00, 31.1MB/s]
vocab.json: 2.78MB [00:00, 109MB/s]
merges.txt: 1.67MB [00:00, 129MB/s]
tokenizer.json: 7.03MB [00:00, 170MB/s]
INFO 07-21 05:43:27 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
config.json: 100% 841/841 [00:00<00:00, 9.00MB/s]
INFO 07-21 05:43:46 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 05:43:46 [model.py:1678] Using max model len 8192
INFO 07-21 05:43:46 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 05:43:46 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
model.safetensors.index.json: 143kB [00:00, 232MB/s]
Parse safetensors files: 100% 5/5 [00:00<00:00,  5.43it/s]
INFO 07-21 05:43:49 [vllm.py:790] Asynchronous scheduling is enabled.
generation_config.json: 100% 243/243 [00:00<00:00, 2.75MB/s]
WARNING 07-21 05:43:50 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=2551) INFO 07-21 05:44:08 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=2551) INFO 07-21 05:44:08 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:54849 backend=nccl
(EngineCore pid=2551) INFO 07-21 05:44:08 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=2551) INFO 07-21 05:44:09 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=2551) INFO 07-21 05:44:09 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=2551) INFO 07-21 05:44:10 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=2551) INFO 07-21 05:44:10 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=2551) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=2551) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
model-00001-of-00005.safetensors:   0% 0.00/3.94G [00:00<?, ?B/s]
model-00005-of-00005.safetensors:   0% 0.00/3.48G [00:00<?, ?B/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:   0% 0.00/3.95G [00:00<?, ?B/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
model-00005-of-00005.safetensors:   6% 201M/3.48G [00:02<00:36, 88.8MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:   5% 201M/3.95G [00:02<00:42, 88.6MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:   5% 201M/3.94G [00:02<00:46, 79.7MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:   7% 268M/3.98G [00:02<00:35, 104MB/s]
(EngineCore pid=2551)
model-00001-of-00005.safetensors:   7% 268M/3.94G [00:02<00:35, 103MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:   8% 335M/3.98G [00:02<00:27, 131MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:   8% 335M/3.98G [00:03<00:34, 105MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:   7% 268M/3.95G [00:03<00:45, 80.5MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:  10% 402M/3.98G [00:03<00:27, 132MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:  10% 402M/3.95G [00:03<00:26, 136MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:  13% 537M/3.98G [00:03<00:20, 172MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  12% 471M/3.94G [00:03<00:24, 144MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:  17% 671M/3.98G [00:04<00:14, 223MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:  15% 603M/3.98G [00:04<00:18, 187MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  14% 538M/3.94G [00:04<00:23, 142MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:  20% 805M/3.98G [00:05<00:17, 184MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:  22% 872M/3.98G [00:05<00:18, 172MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:  20% 805M/3.95G [00:05<00:18, 169MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:  20% 805M/3.98G [00:05<00:20, 159MB/s]
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  27% 1.07G/3.94G [00:10<00:29, 96.7MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:  31% 1.21G/3.95G [00:10<00:25, 106MB/s]
model-00005-of-00005.safetensors:  23% 805M/3.48G [00:10<00:34, 77.4MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:  30% 1.21G/3.98G [00:10<00:26, 106MB/s]
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  32% 1.28G/3.94G [00:13<00:31, 84.7MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:  41% 1.61G/3.95G [00:16<00:27, 86.3MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00004-of-00005.safetensors:  44% 1.74G/3.98G [00:18<00:27, 81.5MB/s]
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  46% 1.81G/3.94G [00:19<00:23, 89.9MB/s]
model-00001-of-00005.safetensors:  49% 1.95G/3.94G [00:22<00:27, 72.1MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:  53% 2.08G/3.95G [00:22<00:23, 79.6MB/s]
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  60% 2.35G/3.94G [00:26<00:19, 81.3MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  63% 2.50G/3.94G [00:28<00:17, 81.1MB/s]
model-00005-of-00005.safetensors:  63% 2.19G/3.48G [00:30<00:18, 69.6MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  70% 2.76G/3.94G [00:32<00:15, 76.4MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:  76% 3.02G/3.98G [00:32<00:11, 82.6MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  73% 2.90G/3.94G [00:34<00:15, 65.6MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  82% 3.23G/3.94G [00:38<00:09, 73.8MB/s]
model-00005-of-00005.safetensors:  84% 2.93G/3.48G [00:39<00:07, 74.9MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00001-of-00005.safetensors:  87% 3.43G/3.94G [00:42<00:07, 64.5MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors:  93% 3.69G/3.98G [00:43<00:03, 73.1MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors:  92% 3.62G/3.95G [00:43<00:04, 76.3MB/s]
(EngineCore pid=2551)
model-00002-of-00005.safetensors: 100% 3.98G/3.98G [00:46<00:00, 84.9MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00003-of-00005.safetensors: 100% 3.95G/3.95G [00:47<00:00, 84.0MB/s]
(EngineCore pid=2551)
model-00005-of-00005.safetensors: 100% 3.48G/3.48G [00:47<00:00, 73.6MB/s]
(EngineCore pid=2551)
(EngineCore pid=2551)
(EngineCore pid=2551)
model-00005-of-00005.safetensors: 100% 3.48G/3.48G [00:47<00:00, 73.9MB/s]
model-00004-of-00005.safetensors: 100% 3.98G/3.98G [00:47<00:00, 84.6MB/s]
model-00001-of-00005.safetensors: 100% 3.94G/3.94G [00:47<00:00, 83.6MB/s]
(EngineCore pid=2551) INFO 07-21 05:44:59 [weight_utils.py:581] Time spent downloading weights for Qwen/Qwen2.5-32B-Instruct-AWQ: 47.948731 seconds
Loading safetensors checkpoint shards: 100% 5/5 [00:06<00:00,  1.23s/it]
(EngineCore pid=2551) INFO 07-21 05:45:06 [default_loader.py:384] Loading weights took 6.25 seconds
(EngineCore pid=2551) INFO 07-21 05:45:11 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 60.202207 seconds
(EngineCore pid=2551) INFO 07-21 05:45:29 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=2551) INFO 07-21 05:45:29 [backends.py:1111] Dynamo bytecode transform time: 18.31 s
(EngineCore pid=2551) INFO 07-21 05:45:35 [backends.py:372] Cache the graph of compile range (1, 8192) for later use
(EngineCore pid=2551) INFO 07-21 05:45:44 [backends.py:390] Compiling a graph for compile range (1, 8192) takes 13.84 s
(EngineCore pid=2551) INFO 07-21 05:45:50 [decorators.py:640] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=2551) INFO 07-21 05:45:50 [monitor.py:48] torch.compile took 38.43 s in total
(EngineCore pid=2551) INFO 07-21 05:45:53 [monitor.py:76] Initial profiling/warmup run took 3.25 s
(EngineCore pid=2551) INFO 07-21 05:46:03 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=2551) INFO 07-21 05:46:03 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=2551) INFO 07-21 05:46:06 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=2551) INFO 07-21 05:46:07 [gpu_worker.py:436] Available KV cache memory: 51.42 GiB
(EngineCore pid=2551) INFO 07-21 05:46:07 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=2551) INFO 07-21 05:46:07 [kv_cache_utils.py:1319] GPU KV cache size: 210,608 tokens
(EngineCore pid=2551) INFO 07-21 05:46:07 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.71x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.09it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.74it/s]
(EngineCore pid=2551) INFO 07-21 05:46:19 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=2551) INFO 07-21 05:46:19 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=2551) INFO 07-21 05:46:19 [core.py:283] init engine (profile, create kv cache, warmup model) took 68.85 seconds
(EngineCore pid=2551) INFO 07-21 05:46:22 [vllm.py:790] Asynchronous scheduling is enabled.
05:46:39 | INFO    | stage1 | 20/20  (1.20 q/s, ETA 0 min)
05:46:39 | INFO    | stage1 | TOTAL 20 | success 11 (55.0%) | FAILED 9
05:46:39 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=2551) INFO 07-21 05:46:39 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=2551) INFO 07-21 05:46:39 [core.py:1233] Shutdown complete
[rank0]:[W721 05:46:39.397125692 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())


============================================================
  run_uncertainty
============================================================
05:46:43 | INFO    | stage2 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
05:46:43 | INFO    | stage2 | Math metrics: 20 of 20 trajectories to do
05:46:43 | INFO    | stage2 | Math metrics done.
05:46:43 | INFO    | stage2 | Sampling metrics: 9 of 9 failed trajectories
05:46:45 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 05:46:48.588944: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 05:46:48.668081: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 05:46:58 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 05:47:00 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 05:47:00 [model.py:1678] Using max model len 8192
INFO 07-21 05:47:01 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.

In [9]:
# Check smoke test produced output
import glob
tables = glob.glob('outputs/tables/*') + glob.glob('/content/drive/MyDrive/agent-repair-hotpotqa/outputs/tables/*')
figs = glob.glob('outputs/figures/*') + glob.glob('/content/drive/MyDrive/agent-repair-hotpotqa/outputs/figures/*')
print(f'Tables: {len(tables)}, Figures: {len(figs)}')
if tables or figs:
    print('Smoke test PASSED — safe to run the full pipeline below.')
else:
    print('WARNING: No outputs found. Check the logs above for errors.')

Tables: 4, Figures: 0
Smoke test PASSED — safe to run the full pipeline below.

---
## Full Pipeline (500 questions)

Only run these cells after the smoke test passes. To reset and run fresh, delete the `data/processed/` folder.

### Stage 0: Download HotpotQA

In [10]:
!python scripts/run_setup.py --config {CONFIG}

05:59:00 | INFO    | setup | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
05:59:00 | INFO    | setup | Dataset: hotpotqa (file: hotpot_dev_distractor_v1.json)
05:59:00 | INFO    | setup | Dataset already present: /content/drive/MyDrive/agent-repair-hotpotqa/data/raw/hotpot_dev_distractor_v1.json
05:59:00 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-hotpotqa/data/raw/hotpot_dev_distractor_v1.json (46.8 MB, 7405 questions)
05:59:00 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-hotpotqa

### Stage 1: Generate ReAct Trajectories

In [11]:
!python scripts/run_generate.py --config {CONFIG}

05:59:01 | INFO    | stage1 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
05:59:01 | INFO    | stage1 | Dataset: hotpotqa (env: HotpotEnv)
05:59:01 | INFO    | stage1 | Pool: 500 questions
05:59:01 | INFO    | stage1 | To process: 480 of 500 (20 already done)
05:59:03 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 05:59:06.481553: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 05:59:06.553007: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 05:59:17 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 05:59:18 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 05:59:18 [model.py:1678] Using max model len 8192
INFO 07-21 05:59:20 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 05:59:20 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  5.78it/s]
INFO 07-21 05:59:21 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 05:59:23 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=7918) INFO 07-21 05:59:41 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=7918) INFO 07-21 05:59:41 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:55449 backend=nccl
(EngineCore pid=7918) INFO 07-21 05:59:41 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=7918) INFO 07-21 05:59:42 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=7918) INFO 07-21 05:59:43 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=7918) INFO 07-21 05:59:43 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=7918) INFO 07-21 05:59:43 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=7918) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=7918) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=7918) INFO 07-21 05:59:51 [default_loader.py:384] Loading weights took 5.87 seconds
(EngineCore pid=7918) INFO 07-21 05:59:56 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.971863 seconds
(EngineCore pid=7918) INFO 07-21 06:00:04 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=7918) INFO 07-21 06:00:04 [backends.py:1111] Dynamo bytecode transform time: 7.97 s
(EngineCore pid=7918) INFO 07-21 06:00:08 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.006 s
(EngineCore pid=7918) INFO 07-21 06:00:08 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=7918) INFO 07-21 06:00:08 [monitor.py:48] torch.compile took 12.14 s in total
(EngineCore pid=7918) INFO 07-21 06:00:11 [monitor.py:76] Initial profiling/warmup run took 3.03 s
(EngineCore pid=7918) INFO 07-21 06:00:12 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=7918) INFO 07-21 06:00:12 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=7918) INFO 07-21 06:00:15 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=7918) INFO 07-21 06:00:15 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=7918) INFO 07-21 06:00:15 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=7918) INFO 07-21 06:00:15 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=7918) INFO 07-21 06:00:15 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.14it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.68it/s]
(EngineCore pid=7918) INFO 07-21 06:00:27 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=7918) INFO 07-21 06:00:27 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=7918) INFO 07-21 06:00:27 [core.py:283] init engine (profile, create kv cache, warmup model) took 31.97 seconds
(EngineCore pid=7918) INFO 07-21 06:00:30 [vllm.py:790] Asynchronous scheduling is enabled.
06:00:51 | INFO    | stage1 | 32/480  (1.54 q/s, ETA 5 min)
06:01:12 | INFO    | stage1 | 64/480  (1.51 q/s, ETA 5 min)
06:01:31 | INFO    | stage1 | 96/480  (1.57 q/s, ETA 4 min)
06:01:49 | INFO    | stage1 | 128/480  (1.63 q/s, ETA 4 min)
06:02:08 | INFO    | stage1 | 160/480  (1.63 q/s, ETA 3 min)
06:02:27 | INFO    | stage1 | 192/480  (1.64 q/s, ETA 3 min)
06:02:44 | INFO    | stage1 | 224/480  (1.68 q/s, ETA 3 min)
06:03:05 | INFO    | stage1 | 256/480  (1.65 q/s, ETA 2 min)
06:03:22 | INFO    | stage1 | 288/480  (1.67 q/s, ETA 2 min)
06:03:40 | INFO    | stage1 | 320/480  (1.68 q/s, ETA 2 min)
06:03:59 | INFO    | stage1 | 352/480  (1.68 q/s, ETA 1 min)
06:04:19 | INFO    | stage1 | 384/480  (1.67 q/s, ETA 1 min)
06:04:38 | INFO    | stage1 | 416/480  (1.68 q/s, ETA 1 min)
06:04:54 | INFO    | stage1 | 448/480  (1.70 q/s, ETA 0 min)
06:05:13 | INFO    | stage1 | 480/480  (1.70 q/s, ETA 0 min)
06:05:16 | INFO    | stage1 | TOTAL 500 | success 274 (54.8%) | FAILED 226
06:05:16 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=7918) INFO 07-21 06:05:16 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=7918) INFO 07-21 06:05:16 [core.py:1233] Shutdown complete
[rank0]:[W721 06:05:16.846024378 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 2: Step-Level Uncertainty

In [12]:
!python scripts/run_uncertainty.py --config {CONFIG}

06:05:21 | INFO    | stage2 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
06:05:21 | INFO    | stage2 | Math metrics: 480 of 500 trajectories to do
06:05:34 | INFO    | stage2 | Math metrics done.
06:05:34 | INFO    | stage2 | Sampling metrics: 217 of 226 failed trajectories
06:05:35 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 06:05:38.814231: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 06:05:38.884507: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 06:05:49 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 06:05:51 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 06:05:51 [model.py:1678] Using max model len 8192
INFO 07-21 06:05:52 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 06:05:52 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  5.22it/s]
INFO 07-21 06:05:54 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 06:05:55 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=10326) INFO 07-21 06:06:13 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=10326) INFO 07-21 06:06:13 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:39147 backend=nccl
(EngineCore pid=10326) INFO 07-21 06:06:13 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=10326) INFO 07-21 06:06:14 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=10326) INFO 07-21 06:06:15 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=10326) INFO 07-21 06:06:15 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=10326) INFO 07-21 06:06:15 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=10326) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=10326) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=10326) INFO 07-21 06:06:23 [default_loader.py:384] Loading weights took 5.88 seconds
(EngineCore pid=10326) INFO 07-21 06:06:28 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 12.162047 seconds
(EngineCore pid=10326) INFO 07-21 06:06:37 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=10326) INFO 07-21 06:06:37 [backends.py:1111] Dynamo bytecode transform time: 8.06 s
(EngineCore pid=10326) INFO 07-21 06:06:41 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.030 s
(EngineCore pid=10326) INFO 07-21 06:06:41 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=10326) INFO 07-21 06:06:41 [monitor.py:48] torch.compile took 12.28 s in total
(EngineCore pid=10326) INFO 07-21 06:06:44 [monitor.py:76] Initial profiling/warmup run took 3.04 s
(EngineCore pid=10326) INFO 07-21 06:06:45 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=10326) INFO 07-21 06:06:45 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=10326) INFO 07-21 06:06:47 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=10326) INFO 07-21 06:06:48 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=10326) INFO 07-21 06:06:48 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=10326) INFO 07-21 06:06:48 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=10326) INFO 07-21 06:06:48 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.02it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.70it/s]
(EngineCore pid=10326) INFO 07-21 06:07:00 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=10326) INFO 07-21 06:07:00 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=10326) INFO 07-21 06:07:00 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.25 seconds
(EngineCore pid=10326) INFO 07-21 06:07:03 [vllm.py:790] Asynchronous scheduling is enabled.
06:07:33 | INFO    | stage2 | 16/217  (0.54 q/s, ETA 6 min)
06:08:12 | INFO    | stage2 | 32/217  (0.46 q/s, ETA 7 min)
06:08:42 | INFO    | stage2 | 48/217  (0.49 q/s, ETA 6 min)
06:09:17 | INFO    | stage2 | 64/217  (0.48 q/s, ETA 5 min)
06:09:47 | INFO    | stage2 | 80/217  (0.49 q/s, ETA 5 min)
06:10:19 | INFO    | stage2 | 96/217  (0.49 q/s, ETA 4 min)
06:10:52 | INFO    | stage2 | 112/217  (0.49 q/s, ETA 4 min)
06:11:21 | INFO    | stage2 | 128/217  (0.50 q/s, ETA 3 min)
06:11:52 | INFO    | stage2 | 144/217  (0.50 q/s, ETA 2 min)
06:12:16 | INFO    | stage2 | 160/217  (0.51 q/s, ETA 2 min)
06:12:40 | INFO    | stage2 | 176/217  (0.52 q/s, ETA 1 min)
06:13:05 | INFO    | stage2 | 192/217  (0.53 q/s, ETA 1 min)
06:13:29 | INFO    | stage2 | 208/217  (0.54 q/s, ETA 0 min)
06:13:43 | INFO    | stage2 | 217/217  (0.54 q/s, ETA 0 min)
06:13:43 | INFO    | stage2 | Sampling-based uncertainty done.
(EngineCore pid=10326) INFO 07-21 06:13:43 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=10326) INFO 07-21 06:13:43 [core.py:1233] Shutdown complete
[rank0]:[W721 06:13:44.028456922 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 3: Error Annotation (72B Judge)

In [13]:
!python scripts/run_annotate.py --config {CONFIG}

06:13:48 | INFO    | stage3 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
06:13:48 | INFO    | stage3 | To annotate: 217 of 226 failed trajectories
06:13:49 | INFO    | stage3 | GPU VRAM: 85.094825984 GB | judge: Qwen/Qwen2.5-72B-Instruct-AWQ (85 GB -> 72B judge)
2026-07-21 06:13:52.921100: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 06:13:52.991437: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 06:14:03 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-72B-Instruct-AWQ'}
INFO 07-21 06:14:05 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 06:14:05 [model.py:1678] Using max model len 8192
INFO 07-21 06:14:06 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 06:14:06 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 11/11 [00:01<00:00,  6.82it/s]
INFO 07-21 06:14:08 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 06:14:10 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=12701) INFO 07-21 06:14:28 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-72B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-72B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-72B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=12701) INFO 07-21 06:14:28 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:46635 backend=nccl
(EngineCore pid=12701) INFO 07-21 06:14:28 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=12701) INFO 07-21 06:14:29 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-72B-Instruct-AWQ...
(EngineCore pid=12701) INFO 07-21 06:14:29 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=12701) INFO 07-21 06:14:30 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=12701) INFO 07-21 06:14:30 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=12701) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=12701) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 11/11 [00:13<00:00,  1.25s/it]
(EngineCore pid=12701) INFO 07-21 06:14:46 [default_loader.py:384] Loading weights took 13.93 seconds
(EngineCore pid=12701) INFO 07-21 06:14:56 [gpu_model_runner.py:4820] Model loading took 38.77 GiB memory and 25.696264 seconds
(EngineCore pid=12701) INFO 07-21 06:15:06 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/53d20b985e/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=12701) INFO 07-21 06:15:06 [backends.py:1111] Dynamo bytecode transform time: 9.38 s
(EngineCore pid=12701) INFO 07-21 06:15:11 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.702 s
(EngineCore pid=12701) INFO 07-21 06:15:11 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/bfecb0b875229f090c0ca3328404a3eb2f6add3eda8c9a9377d884ffa1bb6e0d/rank_0_0/model
(EngineCore pid=12701) INFO 07-21 06:15:11 [monitor.py:48] torch.compile took 14.67 s in total
(EngineCore pid=12701) INFO 07-21 06:15:18 [monitor.py:76] Initial profiling/warmup run took 6.50 s
(EngineCore pid=12701) INFO 07-21 06:15:28 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=12701) INFO 07-21 06:15:28 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=12701) INFO 07-21 06:15:32 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.31 GiB total
(EngineCore pid=12701) INFO 07-21 06:15:33 [gpu_worker.py:436] Available KV cache memory: 32.24 GiB
(EngineCore pid=12701) INFO 07-21 06:15:33 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9200 to 0.9365 to maintain the same effective KV cache size.
(EngineCore pid=12701) INFO 07-21 06:15:33 [kv_cache_utils.py:1319] GPU KV cache size: 105,648 tokens
(EngineCore pid=12701) INFO 07-21 06:15:33 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 12.90x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:12<00:00,  3.98it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:05<00:00,  5.94it/s]
(EngineCore pid=12701) INFO 07-21 06:15:53 [gpu_model_runner.py:6046] Graph capturing finished in 20 secs, took 1.17 GiB
(EngineCore pid=12701) INFO 07-21 06:15:53 [gpu_worker.py:597] CUDA graph pool memory: 1.17 GiB (actual), 1.31 GiB (estimated), difference: 0.14 GiB (12.2%).
(EngineCore pid=12701) INFO 07-21 06:15:53 [core.py:283] init engine (profile, create kv cache, warmup model) took 56.52 seconds
(EngineCore pid=12701) INFO 07-21 06:15:55 [vllm.py:790] Asynchronous scheduling is enabled.
06:16:15 | INFO    | stage3 | 16/217  (0.82 traj/s, ETA 4 min)
06:16:36 | INFO    | stage3 | 32/217  (0.77 traj/s, ETA 4 min)
06:16:55 | INFO    | stage3 | 48/217  (0.79 traj/s, ETA 4 min)
06:17:15 | INFO    | stage3 | 64/217  (0.80 traj/s, ETA 3 min)
06:17:33 | INFO    | stage3 | 80/217  (0.81 traj/s, ETA 3 min)
06:17:52 | INFO    | stage3 | 96/217  (0.82 traj/s, ETA 2 min)
06:18:12 | INFO    | stage3 | 112/217  (0.82 traj/s, ETA 2 min)
06:18:31 | INFO    | stage3 | 128/217  (0.82 traj/s, ETA 2 min)
06:18:50 | INFO    | stage3 | 144/217  (0.82 traj/s, ETA 1 min)
06:19:05 | INFO    | stage3 | 160/217  (0.84 traj/s, ETA 1 min)
06:19:20 | INFO    | stage3 | 176/217  (0.86 traj/s, ETA 1 min)
06:19:36 | INFO    | stage3 | 192/217  (0.87 traj/s, ETA 0 min)
06:19:51 | INFO    | stage3 | 208/217  (0.88 traj/s, ETA 0 min)
06:20:02 | INFO    | stage3 | 217/217  (0.88 traj/s, ETA 0 min)
06:20:02 | INFO    | stage3 | Annotated: 226
06:20:02 | INFO    | stage3 | error types: Counter({'wrong_search_query': 124, 'premature_or_wrong_answer': 56, 'wrong_fact_extraction': 24, 'faulty_reasoning': 22})
06:20:02 | INFO    | stage3 | sources    : Counter({'judge': 226})
06:20:02 | INFO    | stage3 | Next: run `python scripts/label_human.py` to hand-label 50 and check agreement.
(EngineCore pid=12701) INFO 07-21 06:20:02 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=12701) INFO 07-21 06:20:02 [core.py:1233] Shutdown complete
[rank0]:[W721 06:20:02.660944044 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 4: Localization Scoring

In [14]:
!python scripts/run_localize.py --config {CONFIG}

06:20:07 | INFO    | stage4 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
06:20:08 | INFO    | stage4 | records: 2260 (226 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.248           0.460  0.456          0.279              0.553     0.389     0.584  226
token_entropy_max             0.195           0.451  0.420          0.230              0.544     0.376     0.544  226
max_token_prob_max            0.177           0.442  0.418          0.248              0.549     0.389     0.566  226
perplexity                    0.173           0.456  0.406          0.212              0.562     0.332     0.562  226
max_token_prob_mean           0.164           0.447  0.400          0.208              0.562     0.319     0.566  226
token_entropy_mean            0.159           0.447  0.391          0.204              0.540     0.310     0.549  226
token_entropy_mean_k20        0.159           0.447  0.391          0.204              0.540     0.310     0.549  226
token_entropy_mean_k50        0.159           0.447  0.391          0.204              0.540     0.310     0.549  226
token_entropy_mean_k5         0.155           0.460  0.393          0.208              0.558     0.314     0.571  226
verbalized_confidence         0.088           0.261  0.362          0.137              0.358     0.248     0.580  226
06:20:08 | INFO    | stage4 | Random top-1 baseline: 0.223 | best metric: self_consistency (0.248)
06:20:08 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-hotpotqa/outputs/tables/localization_summary.csv

### Stage 5: Repair (126 Strategies)

In [15]:
!python scripts/run_repair.py --config {CONFIG}

06:20:09 | INFO    | stage5 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
06:20:09 | INFO    | stage5 | Dataset: hotpotqa (env: HotpotEnv)
06:20:09 | INFO    | stage5 | 226 failed x 126 strategies x 3 seeds = 85428 result rows (actual GPU runs are far fewer: dedup)
06:20:11 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 06:20:14.469302: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 06:20:14.542563: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 06:20:25 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 06:20:27 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 06:20:27 [model.py:1678] Using max model len 8192
INFO 07-21 06:20:28 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 06:20:28 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  5.43it/s]
INFO 07-21 06:20:30 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 06:20:31 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=14619) INFO 07-21 06:20:49 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=14619) INFO 07-21 06:20:49 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:44855 backend=nccl
(EngineCore pid=14619) INFO 07-21 06:20:49 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=14619) INFO 07-21 06:20:50 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=14619) INFO 07-21 06:20:51 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=14619) INFO 07-21 06:20:51 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=14619) INFO 07-21 06:20:51 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=14619) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=14619) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=14619) INFO 07-21 06:20:59 [default_loader.py:384] Loading weights took 5.89 seconds
(EngineCore pid=14619) INFO 07-21 06:21:04 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 12.055152 seconds
(EngineCore pid=14619) INFO 07-21 06:21:12 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=14619) INFO 07-21 06:21:12 [backends.py:1111] Dynamo bytecode transform time: 8.07 s
(EngineCore pid=14619) INFO 07-21 06:21:17 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 2.999 s
(EngineCore pid=14619) INFO 07-21 06:21:17 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=14619) INFO 07-21 06:21:17 [monitor.py:48] torch.compile took 12.24 s in total
(EngineCore pid=14619) INFO 07-21 06:21:20 [monitor.py:76] Initial profiling/warmup run took 3.03 s
(EngineCore pid=14619) INFO 07-21 06:21:21 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=14619) INFO 07-21 06:21:21 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=14619) INFO 07-21 06:21:23 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=14619) INFO 07-21 06:21:24 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=14619) INFO 07-21 06:21:24 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=14619) INFO 07-21 06:21:24 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=14619) INFO 07-21 06:21:24 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.08it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.73it/s]
(EngineCore pid=14619) INFO 07-21 06:21:36 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=14619) INFO 07-21 06:21:36 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=14619) INFO 07-21 06:21:36 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.07 seconds
(EngineCore pid=14619) INFO 07-21 06:21:38 [vllm.py:790] Asynchronous scheduling is enabled.
06:21:38 | INFO    | stage5 | --- seed 0 ---
06:29:59 | INFO    | stage5 | seed 0: 64/226 questions | 705 GPU repairs so far | 8.3 min elapsed
06:38:09 | INFO    | stage5 | seed 0: 128/226 questions | 1414 GPU repairs so far | 16.5 min elapsed
06:45:01 | INFO    | stage5 | seed 0: 192/226 questions | 2050 GPU repairs so far | 23.4 min elapsed
06:48:40 | INFO    | stage5 | seed 0: 226/226 questions | 2375 GPU repairs so far | 27.0 min elapsed
06:48:40 | INFO    | stage5 | --- seed 1 ---
06:56:46 | INFO    | stage5 | seed 1: 64/226 questions | 3074 GPU repairs so far | 35.1 min elapsed
07:05:01 | INFO    | stage5 | seed 1: 128/226 questions | 3786 GPU repairs so far | 43.4 min elapsed
07:11:57 | INFO    | stage5 | seed 1: 192/226 questions | 4422 GPU repairs so far | 50.3 min elapsed
07:15:35 | INFO    | stage5 | seed 1: 226/226 questions | 4746 GPU repairs so far | 53.9 min elapsed
07:15:35 | INFO    | stage5 | --- seed 2 ---
07:23:45 | INFO    | stage5 | seed 2: 64/226 questions | 5449 GPU repairs so far | 62.1 min elapsed
07:31:52 | INFO    | stage5 | seed 2: 128/226 questions | 6162 GPU repairs so far | 70.2 min elapsed
07:38:50 | INFO    | stage5 | seed 2: 192/226 questions | 6799 GPU repairs so far | 77.2 min elapsed
07:42:25 | INFO    | stage5 | seed 2: 226/226 questions | 7120 GPU repairs so far | 80.8 min elapsed
07:42:25 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 7120 (vs 85428 result rows — dedup saved 92%)
07:42:25 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-hotpotqa/outputs/repairs/results.jsonl
(EngineCore pid=14619) INFO 07-21 07:42:25 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=14619) INFO 07-21 07:42:25 [core.py:1233] Shutdown complete
[rank0]:[W721 07:42:25.929852654 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 6: Evaluation

In [16]:
!python scripts/run_eval.py --config {CONFIG}

07:42:30 | INFO    | stage6 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
07:42:32 | INFO    | stage6 | rows: 86106 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%     95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step      8.4  6.3-10.5%         180            2.78             23.0
                                                       full_restart     14.6 11.9-17.3%         275            4.75             31.9
                                               oracle_targeted__bt2     12.2  9.9-14.8%         272            4.51             31.9
                                     oracle_targeted__bt2__informed     11.8  9.4-14.3%         276            4.58             31.9
                                          oracle_targeted__informed     11.4  9.0-13.7%         244            3.83            100.0
                                    unc__max_token_prob_max__argmax      9.9  7.7-12.2%         177            2.70             17.7
                               unc__max_token_prob_max__argmax__bt2     11.8  9.4-14.2%         228            3.68             18.6
                     unc__max_token_prob_max__argmax__bt2__informed     11.5  9.1-13.9%         230            3.76             18.6
                          unc__max_token_prob_max__argmax__informed      8.6  6.5-10.8%         175            2.72             17.7
                          unc__max_token_prob_max__cascade_gradient     10.2  8.0-12.5%         186            2.86             23.9
                     unc__max_token_prob_max__cascade_gradient__bt2     12.0  9.6-14.4%         241            3.93             23.9
           unc__max_token_prob_max__cascade_gradient__bt2__informed     12.1  9.7-14.6%         242            3.99             23.9
                unc__max_token_prob_max__cascade_gradient__informed      8.7  6.6-10.9%         184            2.82             23.9
                          unc__max_token_prob_max__cascade_upstream     11.8  9.4-14.2%         228            3.68             18.6
                     unc__max_token_prob_max__cascade_upstream__bt2     11.2  8.8-13.6%         262            4.35             27.0
           unc__max_token_prob_max__cascade_upstream__bt2__informed     11.5  9.1-14.0%         265            4.40             27.0
                unc__max_token_prob_max__cascade_upstream__informed     11.5  9.1-13.9%         230            3.76             18.6
                          unc__max_token_prob_max__cascade_weighted     11.4  9.0-13.9%         244            3.96             21.2
                     unc__max_token_prob_max__cascade_weighted__bt2     11.6  9.3-14.0%         270            4.47             29.2
           unc__max_token_prob_max__cascade_weighted__bt2__informed     12.4  9.9-14.9%         272            4.55             29.2
                unc__max_token_prob_max__cascade_weighted__informed     12.2  9.7-14.8%         242            3.95             21.2
                  unc__max_token_prob_max__earliest_above_threshold     10.0  7.8-12.4%         212            3.32             24.8
             unc__max_token_prob_max__earliest_above_threshold__bt2     12.4 10.0-14.9%         255            4.17             28.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed     13.0 10.5-15.5%         256            4.21             28.8
        unc__max_token_prob_max__earliest_above_threshold__informed     10.5  8.3-12.8%         213            3.34             24.8
                                      unc__max_token_prob_max__topk     10.9  8.6-13.3%         240            3.88             19.0
                                 unc__max_token_prob_max__topk__bt2     12.5 10.0-15.0%         265            4.39             31.0
                       unc__max_token_prob_max__topk__bt2__informed     13.1 10.6-15.8%         268            4.44             31.0
                            unc__max_token_prob_max__topk__informed     13.0 10.5-15.6%         237            3.89             19.0
                                            unc__perplexity__argmax      8.4  6.3-10.5%         193            3.01             17.3
                                       unc__perplexity__argmax__bt2     11.6  9.3-14.2%         239            3.89             19.0
                             unc__perplexity__argmax__bt2__informed     12.2  9.9-14.8%         239            3.89             19.0
                                  unc__perplexity__argmax__informed     10.0  7.8-12.4%         188            2.96             17.3
                                  unc__perplexity__cascade_gradient      9.7  7.5-11.9%         192            2.93             25.7
                             unc__perplexity__cascade_gradient__bt2     12.5 10.2-15.0%         246            4.02             23.9
                   unc__perplexity__cascade_gradient__bt2__informed     12.2  9.9-14.8%         251            4.09             23.9
                        unc__perplexity__cascade_gradient__informed      9.0  6.8-11.2%         191            2.95             25.7
                                  unc__perplexity__cascade_upstream     11.6  9.3-14.2%         239            3.89             19.0
                             unc__perplexity__cascade_upstream__bt2     12.1  9.7-14.6%         263            4.35             25.7
                   unc__perplexity__cascade_upstream__bt2__informed     12.0  9.6-14.4%         267            4.44             25.7
                        unc__perplexity__cascade_upstream__informed     12.2  9.9-14.8%         239            3.89             19.0
                                  unc__perplexity__cascade_weighted     10.9  8.7-13.3%         240            3.88             18.1
                             unc__perplexity__cascade_weighted__bt2     11.6  9.3-14.0%         268            4.44             30.5
                   unc__perplexity__cascade_weighted__bt2__informed     12.7 10.2-15.2%         270            4.47             30.5
                        unc__perplexity__cascade_weighted__informed     11.5  9.1-14.0%         237            3.85             18.1
                          unc__perplexity__earliest_above_threshold     10.2  8.0-12.5%         215            3.40             21.2
                     unc__perplexity__earliest_above_threshold__bt2     12.5 10.0-15.0%         256            4.18             25.2
           unc__perplexity__earliest_above_threshold__bt2__informed     13.0 10.5-15.6%         260            4.27             25.2
                unc__perplexity__earliest_above_threshold__informed     11.1  8.7-13.6%         213            3.37             21.2
                                              unc__perplexity__topk     11.6  9.3-14.2%         239            3.87             16.8
                                         unc__perplexity__topk__bt2     12.5 10.2-15.0%         266            4.40             30.1
                               unc__perplexity__topk__bt2__informed     12.7 10.2-15.2%         271            4.47             30.1
                                    unc__perplexity__topk__informed     12.4 10.0-14.9%         236            3.87             16.8
                                      unc__self_consistency__argmax      9.1  7.1-11.4%         187            2.92             24.8
                                 unc__self_consistency__argmax__bt2     11.4  9.0-13.7%         245            3.96             23.9
                       unc__self_consistency__argmax__bt2__informed     11.4  9.0-13.7%         248            4.11             23.9
                            unc__self_consistency__argmax__informed      9.9  7.7-12.2%         188            2.94             24.8
                            unc__self_consistency__cascade_gradient      9.1  7.1-11.4%         196            3.00             31.0
                       unc__self_consistency__cascade_gradient__bt2     11.1  8.7-13.4%         256            4.21             23.0
             unc__self_consistency__cascade_gradient__bt2__informed     11.8  9.4-14.2%         254            4.21             23.0
                  unc__self_consistency__cascade_gradient__informed     10.8  8.6-13.1%         195            3.01             31.0
                            unc__self_consistency__cascade_upstream     11.4  9.0-13.7%         245            3.96             23.9
                       unc__self_consistency__cascade_upstream__bt2     10.6  8.4-13.0%         267            4.43             31.4
             unc__self_consistency__cascade_upstream__bt2__informed     11.4  9.0-13.7%         269            4.47             31.4
                  unc__self_consistency__cascade_upstream__informed     11.4  9.0-13.7%         248            4.11             23.9
                            unc__self_consistency__cascade_weighted     11.1  8.7-13.4%         242            3.94             18.6
                       unc__self_consistency__cascade_weighted__bt2     11.6  9.3-14.0%         271            4.48             28.8
             unc__self_consistency__cascade_weighted__bt2__informed     10.9  8.6-13.3%         274            4.59             28.8
                  unc__self_consistency__cascade_weighted__informed     11.5  9.1-14.0%         240            3.91             18.6
                    unc__self_consistency__earliest_above_threshold     10.6  8.4-13.0%         215            3.38             27.9
               unc__self_consistency__earliest_above_threshold__bt2     11.6  9.3-14.0%         262            4.29             27.9
     unc__self_consistency__earliest_above_threshold__bt2__informed     11.5  9.1-13.9%         263            4.39             27.9
          unc__self_consistency__earliest_above_threshold__informed     10.5  8.3-12.8%         215            3.38             27.9
                                        unc__self_consistency__topk     11.5  9.1-13.9%         245            4.00             18.1
                                   unc__self_consistency__topk__bt2     11.6  9.3-14.0%         272            4.50             28.8
                         unc__self_consistency__topk__bt2__informed     11.2  8.8-13.6%         273            4.55             28.8
                              unc__self_consistency__topk__informed     12.1  9.7-14.6%         242            3.98             18.1
                                     unc__token_entropy_max__argmax      9.0  6.9-11.2%         168            2.52             19.5
                                unc__token_entropy_max__argmax__bt2     10.6  8.3-13.0%         222            3.61             18.6
                      unc__token_entropy_max__argmax__bt2__informed     11.1  8.7-13.6%         222            3.62             18.6
                           unc__token_entropy_max__argmax__informed      7.7   5.8-9.7%         166            2.52             19.5
                           unc__token_entropy_max__cascade_gradient     10.2  8.0-12.5%         189            2.90             27.0
                      unc__token_entropy_max__cascade_gradient__bt2     10.9  8.7-13.3%         246            4.01             23.0
            unc__token_entropy_max__cascade_gradient__bt2__informed     10.9  8.6-13.3%         247            4.06             23.0
                 unc__token_entropy_max__cascade_gradient__informed      9.1  7.1-11.5%         189            2.91             27.0
                           unc__token_entropy_max__cascade_upstream     10.6  8.3-13.0%         222            3.61             18.6
                      unc__token_entropy_max__cascade_upstream__bt2     10.3  8.1-12.7%         260            4.35             26.6
            unc__token_entropy_max__cascade_upstream__bt2__informed     11.4  9.0-13.7%         261            4.34             26.6
                 unc__token_entropy_max__cascade_upstream__informed     11.1  8.7-13.6%         222            3.62             18.6
                           unc__token_entropy_max__cascade_weighted     11.6  9.3-14.2%         240            3.88             18.6
                      unc__token_entropy_max__cascade_weighted__bt2     12.1  9.7-14.6%         268            4.43             27.0
            unc__token_entropy_max__cascade_weighted__bt2__informed     12.5 10.0-15.0%         274            4.55             27.0
                 unc__token_entropy_max__cascade_weighted__informed     10.9  8.6-13.3%         238            3.86             18.6
                   unc__token_entropy_max__earliest_above_threshold     10.0  7.8-12.4%         201            3.14             23.0
              unc__token_entropy_max__earliest_above_threshold__bt2     10.9  8.6-13.3%         251            4.12             26.6
    unc__token_entropy_max__earliest_above_threshold__bt2__informed     12.4  9.9-14.9%         254            4.18             26.6
         unc__token_entropy_max__earliest_above_threshold__informed      9.3  7.1-11.5%         202            3.15             23.0
                                       unc__token_entropy_max__topk     11.1  8.7-13.4%         232            3.76             17.3
                                  unc__token_entropy_max__topk__bt2     11.8  9.4-14.3%         265            4.39             27.9
                        unc__token_entropy_max__topk__bt2__informed     12.7 10.2-15.2%         269            4.42             27.9
                             unc__token_entropy_max__topk__informed     12.5 10.2-15.0%         233            3.81             17.3
                                 unc__verbalized_confidence__argmax      7.2   5.3-9.1%         178            2.82              8.8
                            unc__verbalized_confidence__argmax__bt2     10.6  8.4-13.0%         227            3.72             13.7
                  unc__verbalized_confidence__argmax__bt2__informed     10.3  8.1-12.7%         223            3.70             13.7
                       unc__verbalized_confidence__argmax__informed     10.2  8.0-12.5%         174            2.79              8.8
                       unc__verbalized_confidence__cascade_gradient      8.3  6.2-10.3%         176            2.68             14.2
                  unc__verbalized_confidence__cascade_gradient__bt2      9.9  7.7-12.2%         240            3.96             19.9
        unc__verbalized_confidence__cascade_gradient__bt2__informed     10.9  8.6-13.3%         235            3.92             19.9
             unc__verbalized_confidence__cascade_gradient__informed      9.0  6.9-11.2%         173            2.62             14.2
                       unc__verbalized_confidence__cascade_upstream     10.6  8.4-13.0%         227            3.72             13.7
                  unc__verbalized_confidence__cascade_upstream__bt2     10.0  7.8-12.4%         259            4.36             26.1
        unc__verbalized_confidence__cascade_upstream__bt2__informed     12.5 10.0-15.0%         257            4.27             26.1
             unc__verbalized_confidence__cascade_upstream__informed     10.3  8.1-12.7%         223            3.70             13.7
                       unc__verbalized_confidence__cascade_weighted      8.1  6.2-10.2%         217            3.52             13.7
                  unc__verbalized_confidence__cascade_weighted__bt2     11.5  9.1-14.0%         252            4.16             20.3
        unc__verbalized_confidence__cascade_weighted__bt2__informed     11.1  8.7-13.6%         253            4.22             20.3
             unc__verbalized_confidence__cascade_weighted__informed     10.9  8.7-13.3%         216            3.51             13.7
               unc__verbalized_confidence__earliest_above_threshold      7.8   5.9-9.9%         214            3.49             13.7
          unc__verbalized_confidence__earliest_above_threshold__bt2     10.8  8.6-13.1%         253            4.19             19.9
unc__verbalized_confidence__earliest_above_threshold__bt2__informed     11.4  9.0-13.9%         251            4.18             19.9
     unc__verbalized_confidence__earliest_above_threshold__informed     10.2  8.0-12.5%         213            3.50             13.7
                                   unc__verbalized_confidence__topk      9.0  6.9-11.2%         238            3.91             18.6
                              unc__verbalized_confidence__topk__bt2     12.1  9.7-14.6%         263            4.36             23.0
                    unc__verbalized_confidence__topk__bt2__informed     12.7 10.2-15.2%         264            4.38             23.0
                         unc__verbalized_confidence__topk__informed     10.8  8.4-13.1%         236            3.92             18.6
                                           uncertainty_ensemble_any     36.4 32.9-40.1%       12836          205.14             89.4
                                                    oracle_targeted     10.9  8.6-13.3%         235            3.68            100.0
Traceback (most recent call last):
  File "/content/agent-repair/scripts/run_eval.py", line 461, in <module>
    main()
  File "/content/agent-repair/scripts/run_eval.py", line 91, in main
    u = df[df.strategy.isin(bt0_strats)] if bt0_strats else df[df.strategy.isin(unc_strats)]
                                            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'bt0_strats' where it is not associated with a value

---
## Results

In [17]:
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())
else:
    print('Summary not yet generated. Run Stage 6 first.')

Summary not yet generated. Run Stage 6 first.

In [18]:
import pandas as pd

results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)
else:
    print('Results table not yet generated. Run Stage 6 first.')

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,8.4,6.3-10.5%,180,2.78,23.0
1,full_restart,14.6,11.9-17.3%,275,4.75,31.9
2,oracle_targeted__bt2,12.2,9.9-14.8%,272,4.51,31.9
3,oracle_targeted__bt2__informed,11.8,9.4-14.3%,276,4.58,31.9
4,oracle_targeted__informed,11.4,9.0-13.7%,244,3.83,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,12.1,9.7-14.6%,263,4.36,23.0
123,unc__verbalized_confidence__topk__bt2__informed,12.7,10.2-15.2%,264,4.38,23.0
124,unc__verbalized_confidence__topk__informed,10.8,8.4-13.1%,236,3.92,18.6
125,uncertainty_ensemble_any,36.4,32.9-40.1%,12836,205.14,89.4
126,oracle_targeted,10.9,8.6-13.3%,235,3.68,100.0

In [19]:
import glob
from IPython.display import display, Image

fig_dir = cfg.path('figures')
figs = sorted(glob.glob(os.path.join(fig_dir, '*.png')))
if figs:
    for f in figs:
        print(f'\n--- {os.path.basename(f)} ---')
        display(Image(filename=f, width=800))
else:
    print('No figures yet. Run Stage 6 first.')

No figures yet. Run Stage 6 first.

---
## Re-run Stages 4–6 with Cascade-Aware Strategies

**Use this after you already have stages 1–3 completed** (trajectories, uncertainty, annotations).
This pulls the latest code (with cascade rules), clears only localization/repair/eval outputs,
and re-runs stages 4→5→6 in one cell. ~3-4 hours on A100-80GB for 500 questions.

In [20]:
import os, shutil

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_hotpotqa.yaml'

# 1. Pull latest code with cascade-aware strategies
os.chdir(REPO_DIR)
!git pull

# 2. Clear ONLY stages 4-6 outputs (keep trajectories, uncertainty, annotations)
drive_base = '/content/drive/MyDrive/agent-repair-hotpotqa'
for base in [REPO_DIR, drive_base]:
    for d in ['outputs/localization', 'outputs/repairs', 'outputs/tables', 'outputs/figures']:
        p = os.path.join(base, d)
        if os.path.exists(p):
            shutil.rmtree(p)
            print(f'Cleared {p}')

# 3. Clear checkpoint files for stages 4-6 (these live in outputs/logs/)
for base in [REPO_DIR, drive_base]:
    for ckpt in ['outputs/logs/stage4_localize.jsonl',
                 'outputs/logs/stage5_repair.jsonl',
                 'outputs/logs/stage6_eval.jsonl']:
        p = os.path.join(base, ckpt)
        if os.path.exists(p):
            os.remove(p)
            print(f'Removed checkpoint: {p}')

print('\nStages 1-3 data preserved. Ready to re-run 4→5→6.')

remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 1.46 KiB | 1.46 MiB/s, done.
From https://github.com/kishormorol/agent-repair
   a76bf73..aba0a7c  main       -> origin/main
Updating a76bf73..aba0a7c
Fast-forward
 paper_title_abstract.md | 9 +++++++++
 1 file changed, 9 insertions(+)
 create mode 100644 paper_title_abstract.md
Cleared /content/drive/MyDrive/agent-repair-hotpotqa/outputs/localization
Cleared /content/drive/MyDrive/agent-repair-hotpotqa/outputs/repairs
Cleared /content/drive/MyDrive/agent-repair-hotpotqa/outputs/tables
Cleared /content/drive/MyDrive/agent-repair-hotpotqa/outputs/figures
Removed checkpoint: /content/drive/MyDrive/agent-repair-hotpotqa/outputs/logs/stage5_repair.jsonl

Stages 1-3 data preserved. Ready to re-run 4→5→6.

In [21]:
# Run stages 4 → 5 → 6 sequentially (run this and go to sleep)
import time

for stage in ['run_localize', 'run_repair', 'run_eval']:
    t0 = time.time()
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG}
    elapsed = (time.time() - t0) / 60
    print(f'  ✓ {stage} done in {elapsed:.1f} min\n')

print('\n' + '='*60)
print('  ALL DONE — check results below')
print('='*60)

============================================================
  run_localize
============================================================
07:42:43 | INFO    | stage4 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
07:42:44 | INFO    | stage4 | records: 2260 (226 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.248           0.460  0.456          0.279              0.553     0.389     0.584  226
token_entropy_max             0.195           0.451  0.420          0.230              0.544     0.376     0.544  226
max_token_prob_max            0.177           0.442  0.418          0.248              0.549     0.389     0.566  226
perplexity                    0.173           0.456  0.406          0.212              0.562     0.332     0.562  226
max_token_prob_mean           0.164           0.447  0.400          0.208              0.562     0.319     0.566  226
token_entropy_mean            0.159           0.447  0.391          0.204              0.540     0.310     0.549  226
token_entropy_mean_k20        0.159           0.447  0.391          0.204              0.540     0.310     0.549  226
token_entropy_mean_k50        0.159           0.447  0.391          0.204              0.540     0.310     0.549  226
token_entropy_mean_k5         0.155           0.460  0.393          0.208              0.558     0.314     0.571  226
verbalized_confidence         0.088           0.261  0.362          0.137              0.358     0.248     0.580  226
07:42:44 | INFO    | stage4 | Random top-1 baseline: 0.223 | best metric: self_consistency (0.248)
07:42:44 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-hotpotqa/outputs/tables/localization_summary.csv
  ✓ run_localize done in 0.0 min


============================================================
  run_repair
============================================================
07:42:44 | INFO    | stage5 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
07:42:44 | INFO    | stage5 | Dataset: hotpotqa (env: HotpotEnv)
07:42:44 | INFO    | stage5 | 226 failed x 126 strategies x 3 seeds = 85428 result rows (actual GPU runs are far fewer: dedup)
07:42:46 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 07:42:49.626520: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 07:42:49.698693: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 07:43:00 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 07:43:02 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 07:43:02 [model.py:1678] Using max model len 8192
INFO 07-21 07:43:03 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 07:43:03 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:01<00:00,  3.55it/s]
INFO 07-21 07:43:05 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 07:43:07 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=36388) INFO 07-21 07:43:25 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=36388) INFO 07-21 07:43:25 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:37043 backend=nccl
(EngineCore pid=36388) INFO 07-21 07:43:25 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=36388) INFO 07-21 07:43:26 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=36388) INFO 07-21 07:43:27 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=36388) INFO 07-21 07:43:27 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=36388) INFO 07-21 07:43:27 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=36388) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=36388) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.17s/it]
(EngineCore pid=36388) INFO 07-21 07:43:35 [default_loader.py:384] Loading weights took 5.91 seconds
(EngineCore pid=36388) INFO 07-21 07:43:39 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.942997 seconds
(EngineCore pid=36388) INFO 07-21 07:43:48 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=36388) INFO 07-21 07:43:48 [backends.py:1111] Dynamo bytecode transform time: 8.06 s
(EngineCore pid=36388) INFO 07-21 07:43:52 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.023 s
(EngineCore pid=36388) INFO 07-21 07:43:52 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=36388) INFO 07-21 07:43:52 [monitor.py:48] torch.compile took 12.26 s in total
(EngineCore pid=36388) INFO 07-21 07:43:55 [monitor.py:76] Initial profiling/warmup run took 3.03 s
(EngineCore pid=36388) INFO 07-21 07:43:56 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=36388) INFO 07-21 07:43:56 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=36388) INFO 07-21 07:43:59 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=36388) INFO 07-21 07:43:59 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=36388) INFO 07-21 07:43:59 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=36388) INFO 07-21 07:43:59 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=36388) INFO 07-21 07:43:59 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.16it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.70it/s]
(EngineCore pid=36388) INFO 07-21 07:44:12 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=36388) INFO 07-21 07:44:12 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=36388) INFO 07-21 07:44:12 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.06 seconds
(EngineCore pid=36388) INFO 07-21 07:44:14 [vllm.py:790] Asynchronous scheduling is enabled.
07:44:14 | INFO    | stage5 | --- seed 0 ---
07:53:04 | INFO    | stage5 | seed 0: 64/226 questions | 742 GPU repairs so far | 8.8 min elapsed
08:01:21 | INFO    | stage5 | seed 0: 128/226 questions | 1464 GPU repairs so far | 17.1 min elapsed
08:08:32 | INFO    | stage5 | seed 0: 192/226 questions | 2131 GPU repairs so far | 24.3 min elapsed
08:12:32 | INFO    | stage5 | seed 0: 226/226 questions | 2484 GPU repairs so far | 28.3 min elapsed
08:12:32 | INFO    | stage5 | --- seed 1 ---
08:21:14 | INFO    | stage5 | seed 1: 64/226 questions | 3221 GPU repairs so far | 37.0 min elapsed
08:29:36 | INFO    | stage5 | seed 1: 128/226 questions | 3946 GPU repairs so far | 45.4 min elapsed
08:36:50 | INFO    | stage5 | seed 1: 192/226 questions | 4613 GPU repairs so far | 52.6 min elapsed
08:40:51 | INFO    | stage5 | seed 1: 226/226 questions | 4966 GPU repairs so far | 56.6 min elapsed
08:40:51 | INFO    | stage5 | --- seed 2 ---
08:49:37 | INFO    | stage5 | seed 2: 64/226 questions | 5706 GPU repairs so far | 65.4 min elapsed
08:57:52 | INFO    | stage5 | seed 2: 128/226 questions | 6432 GPU repairs so far | 73.6 min elapsed
09:05:06 | INFO    | stage5 | seed 2: 192/226 questions | 7100 GPU repairs so far | 80.9 min elapsed
09:08:58 | INFO    | stage5 | seed 2: 226/226 questions | 7450 GPU repairs so far | 84.7 min elapsed
09:08:58 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 7450 (vs 85428 result rows — dedup saved 91%)
09:08:58 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-hotpotqa/outputs/repairs/results.jsonl
(EngineCore pid=36388) INFO 07-21 09:08:58 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=36388) INFO 07-21 09:08:58 [core.py:1233] Shutdown complete
[rank0]:[W721 09:08:58.538471743 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
  ✓ run_repair done in 86.3 min


============================================================
  run_eval
============================================================
09:09:03 | INFO    | stage6 | config=config/config_colab_hotpotqa.yaml  base=/content/drive/MyDrive/agent-repair-hotpotqa
09:09:05 | INFO    | stage6 | rows: 86106 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%     95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step      8.1  6.0-10.2%         182            2.80             23.0
                                                       full_restart     14.2 11.7-16.8%         274            4.74             31.9
                                               oracle_targeted__bt2     12.4 10.0-14.9%         272            4.51             31.9
                                     oracle_targeted__bt2__informed     11.8  9.4-14.2%         276            4.60             31.9
                                          oracle_targeted__informed     11.4  9.0-13.9%         244            3.85            100.0
                                    unc__max_token_prob_max__argmax      9.9  7.7-12.2%         177            2.71             17.7
                               unc__max_token_prob_max__argmax__bt2     11.6  9.3-14.2%         228            3.70             18.6
                     unc__max_token_prob_max__argmax__bt2__informed     11.4  9.0-13.7%         230            3.76             18.6
                          unc__max_token_prob_max__argmax__informed      8.3  6.2-10.5%         175            2.71             17.7
                          unc__max_token_prob_max__cascade_gradient      9.9  7.7-12.2%         187            2.86             23.9
                     unc__max_token_prob_max__cascade_gradient__bt2     12.2  9.9-14.8%         242            3.94             23.9
           unc__max_token_prob_max__cascade_gradient__bt2__informed     12.1  9.7-14.6%         243            4.01             23.9
                unc__max_token_prob_max__cascade_gradient__informed      9.0  6.9-11.2%         185            2.84             23.9
                          unc__max_token_prob_max__cascade_upstream     11.6  9.3-14.2%         228            3.70             18.6
                     unc__max_token_prob_max__cascade_upstream__bt2     11.1  8.8-13.4%         261            4.36             27.0
           unc__max_token_prob_max__cascade_upstream__bt2__informed     11.4  9.1-13.9%         264            4.39             27.0
                unc__max_token_prob_max__cascade_upstream__informed     11.4  9.0-13.7%         230            3.76             18.6
                          unc__max_token_prob_max__cascade_weighted     11.5  9.1-13.9%         244            3.97             21.2
                     unc__max_token_prob_max__cascade_weighted__bt2     11.5  9.1-14.0%         270            4.49             29.2
           unc__max_token_prob_max__cascade_weighted__bt2__informed     12.1  9.7-14.6%         273            4.58             29.2
                unc__max_token_prob_max__cascade_weighted__informed     12.0  9.6-14.4%         242            3.96             21.2
                  unc__max_token_prob_max__earliest_above_threshold     10.8  8.4-13.1%         212            3.32             24.8
             unc__max_token_prob_max__earliest_above_threshold__bt2     12.4 10.0-14.9%         255            4.19             28.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed     12.1  9.7-14.6%         257            4.24             28.8
        unc__max_token_prob_max__earliest_above_threshold__informed     10.5  8.3-12.8%         212            3.34             24.8
                                      unc__max_token_prob_max__topk     10.9  8.7-13.3%         241            3.91             19.0
                                 unc__max_token_prob_max__topk__bt2     12.1  9.7-14.6%         266            4.42             31.0
                       unc__max_token_prob_max__topk__bt2__informed     12.5 10.2-15.0%         269            4.48             31.0
                            unc__max_token_prob_max__topk__informed     12.8 10.3-15.3%         238            3.91             19.0
                                            unc__perplexity__argmax      8.3  6.2-10.3%         193            3.02             17.3
                                       unc__perplexity__argmax__bt2     11.4  9.0-13.7%         239            3.91             19.0
                             unc__perplexity__argmax__bt2__informed     12.0  9.6-14.4%         238            3.91             19.0
                                  unc__perplexity__argmax__informed      9.7  7.5-11.9%         188            2.98             17.3
                                  unc__perplexity__cascade_gradient      9.6  7.4-11.8%         193            2.96             25.7
                             unc__perplexity__cascade_gradient__bt2     12.1  9.7-14.6%         246            4.03             23.9
                   unc__perplexity__cascade_gradient__bt2__informed     12.2  9.9-14.8%         250            4.10             23.9
                        unc__perplexity__cascade_gradient__informed      9.4  7.4-11.7%         191            2.94             25.7
                                  unc__perplexity__cascade_upstream     11.4  9.0-13.7%         239            3.91             19.0
                             unc__perplexity__cascade_upstream__bt2     12.0  9.6-14.4%         262            4.37             25.7
                   unc__perplexity__cascade_upstream__bt2__informed     11.8  9.4-14.3%         267            4.46             25.7
                        unc__perplexity__cascade_upstream__informed     12.0  9.6-14.4%         238            3.91             19.0

In [22]:
# View cascade-aware results
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())

import pandas as pd
results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)

import glob
from IPython.display import display, Image
figs = sorted(glob.glob(os.path.join(cfg.path('figures'), '*.png')))
for f in figs:
    print(f'\n--- {os.path.basename(f)} ---')
    display(Image(filename=f, width=800))

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,8.1,6.0-10.2%,182,2.80,23.0
1,full_restart,14.2,11.7-16.8%,274,4.74,31.9
2,oracle_targeted__bt2,12.4,10.0-14.9%,272,4.51,31.9
3,oracle_targeted__bt2__informed,11.8,9.4-14.2%,276,4.60,31.9
4,oracle_targeted__informed,11.4,9.0-13.9%,244,3.85,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,12.1,9.7-14.6%,262,4.36,23.0
123,unc__verbalized_confidence__topk__bt2__informed,12.7,10.3-15.2%,265,4.40,23.0
124,unc__verbalized_confidence__topk__informed,10.3,8.1-12.7%,236,3.93,18.6
125,uncertainty_ensemble_any,36.0,32.5-39.7%,12868,206.16,89.4
126,oracle_targeted,10.9,8.6-13.3%,236,3.70,100.0