# Agent Repair Pipeline — MuSiQue

**ICLR Experiment Pipeline — Colab A100-80GB + Qwen2.5-32B-Instruct-AWQ**

| Stage | What it does | ~Time (A100-80GB, 500 Qs) |
|---|---|---|
| 0 | Download MuSiQue, create folders | 1 min |
| 1 | ReAct trajectory generation (Qwen2.5-32B-Instruct-AWQ) | ~1-2 h |
| 2 | Step-level uncertainty scoring | ~1-2 h |
| 3 | 72B judge error annotation | ~1-2 h |
| 4 | Localization scoring (+ cascade-aware rules) | < 1 min |
| 5 | 126 repair strategies (backtrack × nudge type ablation) | ~4-6 h |
| 6 | Tables, stats, figures, ablation analysis | < 1 min |

**Every stage is resumable** — if Colab disconnects, re-run the cell and it picks up where it left off.

---
## 0. Setup

In [1]:
# Verify GPU — should show A100
!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

NVIDIA A100-SXM4-80GB, 81920 MiB

In [2]:
# Mount Google Drive for persistent storage
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_musique.yaml'

if not os.path.exists(REPO_DIR):
    !git clone https://github.com/kishormorol/agent-repair.git {REPO_DIR}
else:
    !cd {REPO_DIR} && git pull

os.chdir(REPO_DIR)
print(f'Working directory: {os.getcwd()}')

Cloning into '/content/agent-repair'...
remote: Enumerating objects: 239, done.
remote: Counting objects: 100% (239/239), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 239 (delta 125), reused 181 (delta 70), pack-reused 0 (from 0)
Receiving objects: 100% (239/239), 334.29 KiB | 8.57 MiB/s, done.
Resolving deltas: 100% (125/125), done.
Working directory: /content/agent-repair

In [4]:
# Check Colab's CUDA version first
!nvcc --version 2>/dev/null || echo "nvcc not found"
!python -c "import torch; print(f'torch CUDA: {torch.version.cuda}')" 2>/dev/null || echo "torch not installed yet"
!nvidia-smi | grep "CUDA Version"

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0
torch CUDA: 12.8
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |

In [5]:
# Install vLLM — pinned to 0.19.0 (last version with CUDA 12 default wheels)
# vLLM >= 0.20 ships CUDA 13 wheels which don't work on Colab's CUDA 12.x
!pip uninstall -y vllm 2>/dev/null
!pip install -q "vllm==0.19.0" 2>&1 | tail -5

# Install remaining dependencies
!pip install -q "transformers>=4.57.0" "tokenizers>=0.21.0" accelerate \
    huggingface_hub datasets scipy scikit-learn pandas pyarrow \
    pyyaml tqdm matplotlib seaborn statsmodels 2>&1 | tail -3

print('\n--- Installation complete ---')

google-adk 2.4.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.4.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.6 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.6 which is incompatible.

--- Installation complete ---

In [6]:
# Quick sanity check: can vLLM see the GPU?
import torch, vllm
print(f'torch:  {torch.__version__}')
print(f'vLLM:   {vllm.__version__}')
print(f'CUDA:   {torch.version.cuda}')
print(f'GPU:    {torch.cuda.get_device_name(0)}')
print(f'VRAM:   {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

torch:  2.10.0+cu128
vLLM:   0.19.0
CUDA:   12.8
GPU:    NVIDIA A100-SXM4-80GB
VRAM:   85.1 GB

In [7]:
# Clear previous data
import shutil, os
drive_base = '/content/drive/MyDrive/agent-repair-musique'
for d in ['outputs', 'data/processed']:
    p = os.path.join(drive_base, d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
for d in ['outputs', 'data/processed']:
    p = os.path.join('/content/agent-repair', d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
print('Ready for fresh run with MuSiQue')

Ready for fresh run with MuSiQue

In [23]:
!cd /content/agent-repair && git pull

remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 815 bytes | 815.00 KiB/s, done.
From https://github.com/kishormorol/agent-repair
   bedc712..238a905  main       -> origin/main
Updating bedc712..238a905
Fast-forward
 src/env/musique_env.py | 12 +++++++++++-
 1 file changed, 11 insertions(+), 1 deletion(-)

---
## Smoke Test (20 questions, ~10-15 min)

**Run this first** to verify everything works before committing A100 units to the full 500-question run.

In [24]:
stages = ['run_setup', 'run_generate', 'run_uncertainty', 'run_annotate',
          'run_localize', 'run_repair', 'run_eval']

for stage in stages:
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG} --limit 20
    print()

============================================================
  run_setup
============================================================
00:24:50 | INFO    | setup | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
00:24:50 | INFO    | setup | Dataset: musique (file: musique_dev.json)
00:24:50 | INFO    | setup | Downloading musique via registry download function...
README.md: 100% 359/359 [00:00<00:00, 1.84MB/s]
musique_full_v1.0_train.jsonl: 100% 477M/477M [00:02<00:00, 220MB/s]
musique_full_v1.0_dev.jsonl: 100% 59.4M/59.4M [00:00<00:00, 62.1MB/s]
Generating train split: 100% 39876/39876 [00:01<00:00, 37260.61 examples/s]
Generating validation split: 100% 4834/4834 [00:00<00:00, 36527.01 examples/s]
  Loaded MuSiQue from bdsaglam/musique
00:25:02 | INFO    | setup | Downloaded 4834 records for musique.
00:25:03 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-musique/data/raw/musique_dev.json (61.1 MB, 4834 questions)
00:25:03 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-musique


============================================================
  run_generate
============================================================
00:25:04 | INFO    | stage1 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
00:25:04 | INFO    | stage1 | Dataset: musique (env: MuSiQueEnv)
00:25:05 | INFO    | stage1 | Pool: 500 questions
00:25:05 | INFO    | stage1 | To process: 20 of 20 (0 already done)
00:25:07 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-22 00:25:10.636532: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-22 00:25:10.707641: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tokenizer_config.json: 7.30kB [00:00, 26.8MB/s]
vocab.json: 2.78MB [00:00, 90.2MB/s]
merges.txt: 1.67MB [00:00, 125MB/s]
tokenizer.json: 7.03MB [00:00, 167MB/s]
INFO 07-22 00:25:23 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
config.json: 100% 841/841 [00:00<00:00, 8.28MB/s]
INFO 07-22 00:25:41 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-22 00:25:41 [model.py:1678] Using max model len 8192
INFO 07-22 00:25:41 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-22 00:25:41 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
model.safetensors.index.json: 143kB [00:00, 219MB/s]
Parse safetensors files: 100% 5/5 [00:00<00:00, 10.29it/s]
INFO 07-22 00:25:42 [vllm.py:790] Asynchronous scheduling is enabled.
generation_config.json: 100% 243/243 [00:00<00:00, 2.74MB/s]
WARNING 07-22 00:25:43 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=13900) INFO 07-22 00:26:01 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=13900) INFO 07-22 00:26:01 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:50203 backend=nccl
(EngineCore pid=13900) INFO 07-22 00:26:01 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=13900) INFO 07-22 00:26:02 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=13900) INFO 07-22 00:26:03 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=13900) INFO 07-22 00:26:04 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=13900) INFO 07-22 00:26:04 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=13900) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=13900) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
model-00002-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
model-00005-of-00005.safetensors:   0% 0.00/3.48G [00:00<?, ?B/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00003-of-00005.safetensors:   0% 0.00/3.95G [00:00<?, ?B/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors:   2% 67.1M/3.98G [00:01<01:28, 44.1MB/s]
(EngineCore pid=13900)
model-00002-of-00005.safetensors:   3% 134M/3.98G [00:01<00:44, 86.8MB/s]
model-00005-of-00005.safetensors:   4% 134M/3.48G [00:01<00:44, 75.6MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:   7% 268M/3.98G [00:01<00:19, 189MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00003-of-00005.safetensors:   2% 67.0M/3.95G [00:01<01:42, 38.0MB/s]
model-00005-of-00005.safetensors:   8% 268M/3.48G [00:02<00:21, 152MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors:   8% 335M/3.98G [00:02<00:22, 165MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00001-of-00005.safetensors:   8% 332M/3.94G [00:02<00:27, 132MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  13% 536M/3.98G [00:02<00:14, 230MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors:  13% 537M/3.98G [00:03<00:13, 249MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00003-of-00005.safetensors:  10% 402M/3.95G [00:03<00:23, 151MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors:  17% 671M/3.98G [00:03<00:12, 255MB/s]
model-00005-of-00005.safetensors:  12% 402M/3.48G [00:03<00:26, 116MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  20% 805M/3.98G [00:04<00:14, 223MB/s]
model-00005-of-00005.safetensors:  13% 469M/3.48G [00:04<00:25, 120MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors:  27% 1.07G/3.98G [00:06<00:15, 189MB/s]
model-00005-of-00005.safetensors:  25% 872M/3.48G [00:06<00:16, 154MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00003-of-00005.safetensors:  24% 939M/3.95G [00:09<00:33, 90.9MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00001-of-00005.safetensors:  26% 1.02G/3.94G [00:09<00:30, 95.6MB/s]
(EngineCore pid=13900)
model-00002-of-00005.safetensors:  42% 1.68G/3.98G [00:13<00:22, 105MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  39% 1.54G/3.98G [00:13<00:25, 96.2MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00001-of-00005.safetensors:  36% 1.41G/3.94G [00:14<00:28, 89.0MB/s]
model-00005-of-00005.safetensors:  48% 1.68G/3.48G [00:17<00:20, 85.9MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  45% 1.81G/3.98G [00:18<00:26, 83.0MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors:  52% 2.08G/3.98G [00:19<00:20, 91.1MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  52% 2.08G/3.98G [00:22<00:25, 74.2MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00001-of-00005.safetensors:  46% 1.81G/3.94G [00:22<00:31, 68.6MB/s]
model-00002-of-00005.safetensors:  64% 2.55G/3.98G [00:26<00:18, 78.0MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  64% 2.55G/3.98G [00:27<00:17, 81.6MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00001-of-00005.safetensors:  60% 2.38G/3.94G [00:28<00:19, 79.3MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00003-of-00005.safetensors:  44% 1.74G/3.95G [00:29<00:24, 88.3MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors:  76% 3.02G/3.98G [00:31<00:11, 85.4MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  72% 2.88G/3.98G [00:32<00:13, 79.3MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00001-of-00005.safetensors:  68% 2.70G/3.94G [00:32<00:15, 79.1MB/s]
model-00002-of-00005.safetensors:  84% 3.35G/3.98G [00:35<00:07, 82.3MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  83% 3.29G/3.98G [00:36<00:08, 81.1MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00003-of-00005.safetensors:  85% 3.35G/3.95G [00:39<00:07, 81.4MB/s]
model-00005-of-00005.safetensors: 100% 3.48G/3.48G [00:40<00:00, 80.7MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00005-of-00005.safetensors: 100% 3.48G/3.48G [00:42<00:00, 81.1MB/s]
model-00002-of-00005.safetensors:  98% 3.89G/3.98G [00:44<00:01, 74.9MB/s]
(EngineCore pid=13900)
model-00004-of-00005.safetensors:  96% 3.82G/3.98G [00:44<00:02, 78.0MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00002-of-00005.safetensors: 100% 3.98G/3.98G [00:44<00:00, 89.4MB/s]
model-00003-of-00005.safetensors: 100% 3.95G/3.95G [00:44<00:00, 88.2MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00004-of-00005.safetensors: 100% 3.98G/3.98G [00:44<00:00, 88.6MB/s]
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
(EngineCore pid=13900)
model-00001-of-00005.safetensors: 100% 3.94G/3.94G [00:45<00:00, 86.7MB/s]
(EngineCore pid=13900) INFO 07-22 00:26:50 [weight_utils.py:581] Time spent downloading weights for Qwen/Qwen2.5-32B-Instruct-AWQ: 45.849909 seconds
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.20s/it]
(EngineCore pid=13900) INFO 07-22 00:26:56 [default_loader.py:384] Loading weights took 6.06 seconds
(EngineCore pid=13900) INFO 07-22 00:27:01 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 57.364018 seconds
(EngineCore pid=13900) INFO 07-22 00:27:21 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=13900) INFO 07-22 00:27:21 [backends.py:1111] Dynamo bytecode transform time: 18.90 s
(EngineCore pid=13900) INFO 07-22 00:27:27 [backends.py:372] Cache the graph of compile range (1, 8192) for later use
(EngineCore pid=13900) INFO 07-22 00:27:36 [backends.py:390] Compiling a graph for compile range (1, 8192) takes 14.27 s
(EngineCore pid=13900) INFO 07-22 00:27:41 [decorators.py:640] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=13900) INFO 07-22 00:27:41 [monitor.py:48] torch.compile took 39.58 s in total
(EngineCore pid=13900) INFO 07-22 00:27:45 [monitor.py:76] Initial profiling/warmup run took 3.26 s
(EngineCore pid=13900) INFO 07-22 00:27:56 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=13900) INFO 07-22 00:27:56 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=13900) INFO 07-22 00:27:59 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=13900) INFO 07-22 00:28:00 [gpu_worker.py:436] Available KV cache memory: 51.42 GiB
(EngineCore pid=13900) INFO 07-22 00:28:00 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=13900) INFO 07-22 00:28:00 [kv_cache_utils.py:1319] GPU KV cache size: 210,608 tokens
(EngineCore pid=13900) INFO 07-22 00:28:00 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.71x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  6.76it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.24it/s]
(EngineCore pid=13900) INFO 07-22 00:28:13 [gpu_model_runner.py:6046] Graph capturing finished in 13 secs, took 0.90 GiB
(EngineCore pid=13900) INFO 07-22 00:28:13 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=13900) INFO 07-22 00:28:13 [core.py:283] init engine (profile, create kv cache, warmup model) took 71.46 seconds
(EngineCore pid=13900) INFO 07-22 00:28:15 [vllm.py:790] Asynchronous scheduling is enabled.
00:28:39 | INFO    | stage1 | 20/20  (0.81 q/s, ETA 0 min)
00:28:40 | INFO    | stage1 | TOTAL 20 | success 4 (20.0%) | FAILED 16
00:28:40 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=13900) INFO 07-22 00:28:40 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=13900) INFO 07-22 00:28:40 [core.py:1233] Shutdown complete
[rank0]:[W722 00:28:40.607511763 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())


============================================================
  run_uncertainty
============================================================
00:28:44 | INFO    | stage2 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
00:28:44 | INFO    | stage2 | Math metrics: 20 of 20 trajectories to do
00:28:45 | INFO    | stage2 | Math metrics done.
00:28:45 | INFO    | stage2 | Sampling metrics: 16 of 16 failed trajectories
00:28:46 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-22 00:28:49.923107: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-22 00:28:49.996198: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-22 00:29:00 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-22 00:29:00 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-22 00:29:00 [model.py:1678] Using max model len 8192
INFO 07-22 00:29:02 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-22 00:29:02 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  9.04it/s]
INFO 07-22 00:29:02 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-22 00:29:04 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized

In [25]:
# Check smoke test produced output
import glob
tables = glob.glob('outputs/tables/*') + glob.glob('/content/drive/MyDrive/agent-repair-musique/outputs/tables/*')
figs = glob.glob('outputs/figures/*') + glob.glob('/content/drive/MyDrive/agent-repair-musique/outputs/figures/*')
print(f'Tables: {len(tables)}, Figures: {len(figs)}')
if tables or figs:
    print('Smoke test PASSED — safe to run the full pipeline below.')
else:
    print('WARNING: No outputs found. Check the logs above for errors.')

Tables: 4, Figures: 0
Smoke test PASSED — safe to run the full pipeline below.

---
## Full Pipeline (500 questions)

Only run these cells after the smoke test passes. To reset and run fresh, delete the `data/processed/` folder.

### Stage 0: Download MuSiQue

In [26]:
!python scripts/run_setup.py --config {CONFIG}

00:46:05 | INFO    | setup | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
00:46:05 | INFO    | setup | Dataset: musique (file: musique_dev.json)
00:46:05 | INFO    | setup | Dataset already present: /content/drive/MyDrive/agent-repair-musique/data/raw/musique_dev.json
00:46:06 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-musique/data/raw/musique_dev.json (61.1 MB, 4834 questions)
00:46:06 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-musique

### Stage 1: Generate ReAct Trajectories

In [27]:
!python scripts/run_generate.py --config {CONFIG}

00:46:07 | INFO    | stage1 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
00:46:07 | INFO    | stage1 | Dataset: musique (env: MuSiQueEnv)
00:46:07 | INFO    | stage1 | Pool: 500 questions
00:46:07 | INFO    | stage1 | To process: 479 of 500 (21 already done)
00:46:09 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-22 00:46:12.088414: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-22 00:46:12.161532: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-22 00:46:21 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-22 00:46:22 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-22 00:46:22 [model.py:1678] Using max model len 8192
INFO 07-22 00:46:24 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-22 00:46:24 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00, 10.98it/s]
INFO 07-22 00:46:25 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-22 00:46:26 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=20436) INFO 07-22 00:46:44 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=20436) INFO 07-22 00:46:44 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:39873 backend=nccl
(EngineCore pid=20436) INFO 07-22 00:46:44 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=20436) INFO 07-22 00:46:45 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=20436) INFO 07-22 00:46:45 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=20436) INFO 07-22 00:46:46 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=20436) INFO 07-22 00:46:46 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=20436) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=20436) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.15s/it]
(EngineCore pid=20436) INFO 07-22 00:46:53 [default_loader.py:384] Loading weights took 5.83 seconds
(EngineCore pid=20436) INFO 07-22 00:46:58 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.378757 seconds
(EngineCore pid=20436) INFO 07-22 00:47:06 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=20436) INFO 07-22 00:47:06 [backends.py:1111] Dynamo bytecode transform time: 7.97 s
(EngineCore pid=20436) INFO 07-22 00:47:11 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.068 s
(EngineCore pid=20436) INFO 07-22 00:47:11 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=20436) INFO 07-22 00:47:11 [monitor.py:48] torch.compile took 12.23 s in total
(EngineCore pid=20436) INFO 07-22 00:47:14 [monitor.py:76] Initial profiling/warmup run took 3.06 s
(EngineCore pid=20436) INFO 07-22 00:47:15 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=20436) INFO 07-22 00:47:15 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=20436) INFO 07-22 00:47:17 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=20436) INFO 07-22 00:47:18 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=20436) INFO 07-22 00:47:18 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=20436) INFO 07-22 00:47:18 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=20436) INFO 07-22 00:47:18 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.02it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.58it/s]
(EngineCore pid=20436) INFO 07-22 00:47:30 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=20436) INFO 07-22 00:47:30 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=20436) INFO 07-22 00:47:30 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.31 seconds
(EngineCore pid=20436) INFO 07-22 00:47:32 [vllm.py:790] Asynchronous scheduling is enabled.
00:47:58 | INFO    | stage1 | 32/479  (1.25 q/s, ETA 6 min)
00:48:22 | INFO    | stage1 | 64/479  (1.28 q/s, ETA 5 min)
00:48:47 | INFO    | stage1 | 96/479  (1.27 q/s, ETA 5 min)
00:49:14 | INFO    | stage1 | 128/479  (1.26 q/s, ETA 5 min)
00:49:41 | INFO    | stage1 | 160/479  (1.24 q/s, ETA 4 min)
00:50:08 | INFO    | stage1 | 192/479  (1.23 q/s, ETA 4 min)
00:50:33 | INFO    | stage1 | 224/479  (1.24 q/s, ETA 3 min)
00:50:59 | INFO    | stage1 | 256/479  (1.24 q/s, ETA 3 min)
00:51:24 | INFO    | stage1 | 288/479  (1.24 q/s, ETA 3 min)
00:51:51 | INFO    | stage1 | 320/479  (1.24 q/s, ETA 2 min)
00:52:17 | INFO    | stage1 | 352/479  (1.24 q/s, ETA 2 min)
00:52:42 | INFO    | stage1 | 384/479  (1.24 q/s, ETA 1 min)
00:53:08 | INFO    | stage1 | 416/479  (1.24 q/s, ETA 1 min)
00:53:36 | INFO    | stage1 | 448/479  (1.23 q/s, ETA 0 min)
00:54:03 | INFO    | stage1 | 479/479  (1.22 q/s, ETA 0 min)
00:54:08 | INFO    | stage1 | TOTAL 475 | success 50 (10.5%) | FAILED 425
00:54:08 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=20436) INFO 07-22 00:54:08 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=20436) INFO 07-22 00:54:08 [core.py:1233] Shutdown complete
[rank0]:[W722 00:54:08.953983817 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 2: Step-Level Uncertainty

In [28]:
!python scripts/run_uncertainty.py --config {CONFIG}

00:54:13 | INFO    | stage2 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
00:54:13 | INFO    | stage2 | Math metrics: 455 of 475 trajectories to do
00:54:28 | INFO    | stage2 | Math metrics done.
00:54:28 | INFO    | stage2 | Sampling metrics: 409 of 425 failed trajectories
00:54:30 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-22 00:54:33.307067: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-22 00:54:33.380288: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-22 00:54:43 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-22 00:54:43 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-22 00:54:43 [model.py:1678] Using max model len 8192
INFO 07-22 00:54:45 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-22 00:54:45 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00, 10.74it/s]
INFO 07-22 00:54:46 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-22 00:54:47 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=23199) INFO 07-22 00:55:05 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=23199) INFO 07-22 00:55:05 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:50417 backend=nccl
(EngineCore pid=23199) INFO 07-22 00:55:05 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=23199) INFO 07-22 00:55:06 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=23199) INFO 07-22 00:55:07 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=23199) INFO 07-22 00:55:07 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=23199) INFO 07-22 00:55:07 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=23199) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=23199) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=23199) INFO 07-22 00:55:14 [default_loader.py:384] Loading weights took 5.88 seconds
(EngineCore pid=23199) INFO 07-22 00:55:19 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.383594 seconds
(EngineCore pid=23199) INFO 07-22 00:55:28 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=23199) INFO 07-22 00:55:28 [backends.py:1111] Dynamo bytecode transform time: 8.08 s
(EngineCore pid=23199) INFO 07-22 00:55:32 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.073 s
(EngineCore pid=23199) INFO 07-22 00:55:32 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=23199) INFO 07-22 00:55:32 [monitor.py:48] torch.compile took 12.34 s in total
(EngineCore pid=23199) INFO 07-22 00:55:35 [monitor.py:76] Initial profiling/warmup run took 3.06 s
(EngineCore pid=23199) INFO 07-22 00:55:36 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=23199) INFO 07-22 00:55:36 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=23199) INFO 07-22 00:55:39 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=23199) INFO 07-22 00:55:39 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=23199) INFO 07-22 00:55:39 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=23199) INFO 07-22 00:55:39 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=23199) INFO 07-22 00:55:39 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.01it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.53it/s]
(EngineCore pid=23199) INFO 07-22 00:55:52 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=23199) INFO 07-22 00:55:52 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=23199) INFO 07-22 00:55:52 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.48 seconds
(EngineCore pid=23199) INFO 07-22 00:55:54 [vllm.py:790] Asynchronous scheduling is enabled.
00:56:31 | INFO    | stage2 | 16/409  (0.43 q/s, ETA 15 min)
00:57:09 | INFO    | stage2 | 32/409  (0.43 q/s, ETA 15 min)
00:57:48 | INFO    | stage2 | 48/409  (0.42 q/s, ETA 14 min)
00:58:21 | INFO    | stage2 | 64/409  (0.43 q/s, ETA 13 min)
00:58:59 | INFO    | stage2 | 80/409  (0.43 q/s, ETA 13 min)
00:59:36 | INFO    | stage2 | 96/409  (0.43 q/s, ETA 12 min)
01:00:14 | INFO    | stage2 | 112/409  (0.43 q/s, ETA 12 min)
01:00:45 | INFO    | stage2 | 128/409  (0.44 q/s, ETA 11 min)
01:01:26 | INFO    | stage2 | 144/409  (0.43 q/s, ETA 10 min)
01:02:03 | INFO    | stage2 | 160/409  (0.43 q/s, ETA 10 min)
01:02:43 | INFO    | stage2 | 176/409  (0.43 q/s, ETA 9 min)
01:03:15 | INFO    | stage2 | 192/409  (0.43 q/s, ETA 8 min)
01:03:56 | INFO    | stage2 | 208/409  (0.43 q/s, ETA 8 min)
01:04:34 | INFO    | stage2 | 224/409  (0.43 q/s, ETA 7 min)
01:05:13 | INFO    | stage2 | 240/409  (0.43 q/s, ETA 7 min)
01:05:53 | INFO    | stage2 | 256/409  (0.43 q/s, ETA 6 min)
01:06:28 | INFO    | stage2 | 272/409  (0.43 q/s, ETA 5 min)
01:07:04 | INFO    | stage2 | 288/409  (0.43 q/s, ETA 5 min)
01:07:40 | INFO    | stage2 | 304/409  (0.43 q/s, ETA 4 min)
01:08:22 | INFO    | stage2 | 320/409  (0.43 q/s, ETA 3 min)
01:09:04 | INFO    | stage2 | 336/409  (0.43 q/s, ETA 3 min)
01:09:44 | INFO    | stage2 | 352/409  (0.42 q/s, ETA 2 min)
01:10:21 | INFO    | stage2 | 368/409  (0.42 q/s, ETA 2 min)
01:11:02 | INFO    | stage2 | 384/409  (0.42 q/s, ETA 1 min)
01:11:38 | INFO    | stage2 | 400/409  (0.42 q/s, ETA 0 min)
01:12:02 | INFO    | stage2 | 409/409  (0.42 q/s, ETA 0 min)
01:12:02 | INFO    | stage2 | Sampling-based uncertainty done.
(EngineCore pid=23199) INFO 07-22 01:12:02 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=23199) INFO 07-22 01:12:02 [core.py:1233] Shutdown complete
[rank0]:[W722 01:12:02.091863175 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 3: Error Annotation (72B Judge)

In [29]:
!python scripts/run_annotate.py --config {CONFIG}

01:12:07 | INFO    | stage3 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
01:12:07 | INFO    | stage3 | To annotate: 409 of 425 failed trajectories
01:12:08 | INFO    | stage3 | GPU VRAM: 85.094825984 GB | judge: Qwen/Qwen2.5-72B-Instruct-AWQ (85 GB -> 72B judge)
2026-07-22 01:12:12.080222: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-22 01:12:12.151543: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-22 01:12:22 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-72B-Instruct-AWQ'}
INFO 07-22 01:12:22 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-22 01:12:22 [model.py:1678] Using max model len 8192
INFO 07-22 01:12:24 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-22 01:12:24 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 11/11 [00:00<00:00, 16.98it/s]
INFO 07-22 01:12:25 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-22 01:12:26 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=27796) INFO 07-22 01:12:44 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-72B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-72B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-72B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=27796) INFO 07-22 01:12:45 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:45457 backend=nccl
(EngineCore pid=27796) INFO 07-22 01:12:45 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=27796) INFO 07-22 01:12:46 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-72B-Instruct-AWQ...
(EngineCore pid=27796) INFO 07-22 01:12:46 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=27796) INFO 07-22 01:12:47 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=27796) INFO 07-22 01:12:47 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=27796) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=27796) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 11/11 [00:13<00:00,  1.27s/it]
(EngineCore pid=27796) INFO 07-22 01:13:03 [default_loader.py:384] Loading weights took 14.11 seconds
(EngineCore pid=27796) INFO 07-22 01:13:13 [gpu_model_runner.py:4820] Model loading took 38.77 GiB memory and 25.301293 seconds
(EngineCore pid=27796) INFO 07-22 01:13:23 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/53d20b985e/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=27796) INFO 07-22 01:13:23 [backends.py:1111] Dynamo bytecode transform time: 9.48 s
(EngineCore pid=27796) INFO 07-22 01:13:28 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.819 s
(EngineCore pid=27796) INFO 07-22 01:13:28 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/bfecb0b875229f090c0ca3328404a3eb2f6add3eda8c9a9377d884ffa1bb6e0d/rank_0_0/model
(EngineCore pid=27796) INFO 07-22 01:13:28 [monitor.py:48] torch.compile took 14.88 s in total
(EngineCore pid=27796) INFO 07-22 01:13:35 [monitor.py:76] Initial profiling/warmup run took 6.51 s
(EngineCore pid=27796) INFO 07-22 01:13:45 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=27796) INFO 07-22 01:13:46 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=27796) INFO 07-22 01:13:49 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.31 GiB total
(EngineCore pid=27796) INFO 07-22 01:13:50 [gpu_worker.py:436] Available KV cache memory: 32.24 GiB
(EngineCore pid=27796) INFO 07-22 01:13:50 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9200 to 0.9365 to maintain the same effective KV cache size.
(EngineCore pid=27796) INFO 07-22 01:13:50 [kv_cache_utils.py:1319] GPU KV cache size: 105,648 tokens
(EngineCore pid=27796) INFO 07-22 01:13:50 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 12.90x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:12<00:00,  3.99it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:06<00:00,  5.81it/s]
(EngineCore pid=27796) INFO 07-22 01:14:10 [gpu_model_runner.py:6046] Graph capturing finished in 20 secs, took 1.17 GiB
(EngineCore pid=27796) INFO 07-22 01:14:10 [gpu_worker.py:597] CUDA graph pool memory: 1.17 GiB (actual), 1.31 GiB (estimated), difference: 0.14 GiB (12.2%).
(EngineCore pid=27796) INFO 07-22 01:14:10 [core.py:283] init engine (profile, create kv cache, warmup model) took 57.34 seconds
(EngineCore pid=27796) INFO 07-22 01:14:12 [vllm.py:790] Asynchronous scheduling is enabled.
01:14:33 | INFO    | stage3 | 16/409  (0.76 traj/s, ETA 9 min)
01:14:52 | INFO    | stage3 | 32/409  (0.79 traj/s, ETA 8 min)
01:15:13 | INFO    | stage3 | 48/409  (0.78 traj/s, ETA 8 min)
01:15:32 | INFO    | stage3 | 64/409  (0.80 traj/s, ETA 7 min)
01:15:51 | INFO    | stage3 | 80/409  (0.80 traj/s, ETA 7 min)
01:16:11 | INFO    | stage3 | 96/409  (0.81 traj/s, ETA 6 min)
01:16:31 | INFO    | stage3 | 112/409  (0.80 traj/s, ETA 6 min)
01:16:49 | INFO    | stage3 | 128/409  (0.81 traj/s, ETA 6 min)
01:17:11 | INFO    | stage3 | 144/409  (0.80 traj/s, ETA 6 min)
01:17:31 | INFO    | stage3 | 160/409  (0.80 traj/s, ETA 5 min)
01:17:51 | INFO    | stage3 | 176/409  (0.80 traj/s, ETA 5 min)
01:18:10 | INFO    | stage3 | 192/409  (0.81 traj/s, ETA 4 min)
01:18:32 | INFO    | stage3 | 208/409  (0.80 traj/s, ETA 4 min)
01:18:53 | INFO    | stage3 | 224/409  (0.80 traj/s, ETA 4 min)
01:19:15 | INFO    | stage3 | 240/409  (0.79 traj/s, ETA 4 min)
01:19:36 | INFO    | stage3 | 256/409  (0.79 traj/s, ETA 3 min)
01:19:55 | INFO    | stage3 | 272/409  (0.79 traj/s, ETA 3 min)
01:20:17 | INFO    | stage3 | 288/409  (0.79 traj/s, ETA 3 min)
01:20:37 | INFO    | stage3 | 304/409  (0.79 traj/s, ETA 2 min)
01:21:00 | INFO    | stage3 | 320/409  (0.78 traj/s, ETA 2 min)
01:21:23 | INFO    | stage3 | 336/409  (0.78 traj/s, ETA 2 min)
01:21:45 | INFO    | stage3 | 352/409  (0.78 traj/s, ETA 1 min)
01:22:05 | INFO    | stage3 | 368/409  (0.78 traj/s, ETA 1 min)
01:22:27 | INFO    | stage3 | 384/409  (0.77 traj/s, ETA 1 min)
01:22:48 | INFO    | stage3 | 400/409  (0.78 traj/s, ETA 0 min)
01:23:01 | INFO    | stage3 | 409/409  (0.77 traj/s, ETA 0 min)
01:23:01 | INFO    | stage3 | Annotated: 425
01:23:01 | INFO    | stage3 | error types: Counter({'wrong_search_query': 374, 'faulty_reasoning': 19, 'wrong_fact_extraction': 19, 'premature_or_wrong_answer': 13})
01:23:01 | INFO    | stage3 | sources    : Counter({'judge': 425})
01:23:01 | INFO    | stage3 | Next: run `python scripts/label_human.py` to hand-label 50 and check agreement.
(EngineCore pid=27796) INFO 07-22 01:23:01 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=27796) INFO 07-22 01:23:01 [core.py:1233] Shutdown complete
[rank0]:[W722 01:23:01.318617834 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 4: Localization Scoring

In [30]:
!python scripts/run_localize.py --config {CONFIG}

01:23:06 | INFO    | stage4 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
01:23:08 | INFO    | stage4 | records: 4250 (425 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.129           0.322  0.328          0.169              0.454     0.231     0.346  425
max_token_prob_max            0.099           0.282  0.296          0.141              0.440     0.200     0.282  425
token_entropy_max             0.099           0.242  0.292          0.155              0.369     0.200     0.287  425
verbalized_confidence         0.085           0.242  0.323          0.122              0.339     0.221     0.379  425
token_entropy_mean_k50        0.073           0.268  0.268          0.089              0.379     0.153     0.271  425
token_entropy_mean            0.073           0.268  0.268          0.089              0.379     0.153     0.271  425
token_entropy_mean_k20        0.073           0.268  0.268          0.089              0.379     0.153     0.271  425
token_entropy_mean_k5         0.068           0.278  0.269          0.101              0.407     0.165     0.273  425
max_token_prob_mean           0.064           0.278  0.270          0.111              0.431     0.176     0.271  425
perplexity                    0.064           0.271  0.270          0.111              0.449     0.176     0.268  425
01:23:08 | INFO    | stage4 | Random top-1 baseline: 0.153 | best metric: self_consistency (0.129)
01:23:08 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-musique/outputs/tables/localization_summary.csv

### Stage 5: Repair (126 Strategies)

In [31]:
!python scripts/run_repair.py --config {CONFIG}

01:23:09 | INFO    | stage5 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
01:23:09 | INFO    | stage5 | Dataset: musique (env: MuSiQueEnv)
01:23:09 | INFO    | stage5 | 425 failed x 126 strategies x 3 seeds = 160650 result rows (actual GPU runs are far fewer: dedup)
01:23:10 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-22 01:23:14.095646: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-22 01:23:14.168204: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-22 01:23:24 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-22 01:23:25 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-22 01:23:25 [model.py:1678] Using max model len 8192
INFO 07-22 01:23:27 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-22 01:23:27 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  9.61it/s]
INFO 07-22 01:23:28 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-22 01:23:29 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=30809) INFO 07-22 01:23:47 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=30809) INFO 07-22 01:23:47 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:47081 backend=nccl
(EngineCore pid=30809) INFO 07-22 01:23:47 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=30809) INFO 07-22 01:23:48 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=30809) INFO 07-22 01:23:49 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=30809) INFO 07-22 01:23:49 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=30809) INFO 07-22 01:23:49 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=30809) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=30809) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.18s/it]
(EngineCore pid=30809) INFO 07-22 01:23:56 [default_loader.py:384] Loading weights took 5.96 seconds
(EngineCore pid=30809) INFO 07-22 01:24:01 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.419098 seconds
(EngineCore pid=30809) INFO 07-22 01:24:10 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=30809) INFO 07-22 01:24:10 [backends.py:1111] Dynamo bytecode transform time: 8.11 s
(EngineCore pid=30809) INFO 07-22 01:24:14 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.153 s
(EngineCore pid=30809) INFO 07-22 01:24:14 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=30809) INFO 07-22 01:24:14 [monitor.py:48] torch.compile took 12.46 s in total
(EngineCore pid=30809) INFO 07-22 01:24:17 [monitor.py:76] Initial profiling/warmup run took 3.04 s
(EngineCore pid=30809) INFO 07-22 01:24:18 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=30809) INFO 07-22 01:24:18 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=30809) INFO 07-22 01:24:21 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=30809) INFO 07-22 01:24:22 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=30809) INFO 07-22 01:24:22 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=30809) INFO 07-22 01:24:22 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=30809) INFO 07-22 01:24:22 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.01it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.34it/s]
(EngineCore pid=30809) INFO 07-22 01:24:34 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=30809) INFO 07-22 01:24:34 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=30809) INFO 07-22 01:24:34 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.74 seconds
(EngineCore pid=30809) INFO 07-22 01:24:36 [vllm.py:790] Asynchronous scheduling is enabled.
01:24:36 | INFO    | stage5 | --- seed 0 ---
01:33:59 | INFO    | stage5 | seed 0: 64/425 questions | 786 GPU repairs so far | 9.4 min elapsed
01:42:53 | INFO    | stage5 | seed 0: 128/425 questions | 1552 GPU repairs so far | 18.3 min elapsed
01:51:56 | INFO    | stage5 | seed 0: 192/425 questions | 2350 GPU repairs so far | 27.3 min elapsed
02:01:44 | INFO    | stage5 | seed 0: 256/425 questions | 3171 GPU repairs so far | 37.1 min elapsed
02:11:13 | INFO    | stage5 | seed 0: 320/425 questions | 3960 GPU repairs so far | 46.6 min elapsed
02:21:34 | INFO    | stage5 | seed 0: 384/425 questions | 4840 GPU repairs so far | 57.0 min elapsed
02:28:02 | INFO    | stage5 | seed 0: 425/425 questions | 5356 GPU repairs so far | 63.4 min elapsed
02:28:02 | INFO    | stage5 | --- seed 1 ---
02:37:22 | INFO    | stage5 | seed 1: 64/425 questions | 6143 GPU repairs so far | 72.8 min elapsed
02:46:26 | INFO    | stage5 | seed 1: 128/425 questions | 6909 GPU repairs so far | 81.8 min elapsed
02:55:34 | INFO    | stage5 | seed 1: 192/425 questions | 7707 GPU repairs so far | 91.0 min elapsed
03:05:24 | INFO    | stage5 | seed 1: 256/425 questions | 8528 GPU repairs so far | 100.8 min elapsed
03:14:56 | INFO    | stage5 | seed 1: 320/425 questions | 9316 GPU repairs so far | 110.3 min elapsed
03:25:23 | INFO    | stage5 | seed 1: 384/425 questions | 10192 GPU repairs so far | 120.8 min elapsed
03:31:56 | INFO    | stage5 | seed 1: 425/425 questions | 10713 GPU repairs so far | 127.3 min elapsed
03:31:56 | INFO    | stage5 | --- seed 2 ---
03:41:22 | INFO    | stage5 | seed 2: 64/425 questions | 11498 GPU repairs so far | 136.8 min elapsed
03:50:32 | INFO    | stage5 | seed 2: 128/425 questions | 12268 GPU repairs so far | 145.9 min elapsed
03:59:45 | INFO    | stage5 | seed 2: 192/425 questions | 13062 GPU repairs so far | 155.2 min elapsed
04:09:39 | INFO    | stage5 | seed 2: 256/425 questions | 13880 GPU repairs so far | 165.1 min elapsed
04:19:03 | INFO    | stage5 | seed 2: 320/425 questions | 14674 GPU repairs so far | 174.5 min elapsed
04:29:36 | INFO    | stage5 | seed 2: 384/425 questions | 15554 GPU repairs so far | 185.0 min elapsed
04:36:07 | INFO    | stage5 | seed 2: 425/425 questions | 16071 GPU repairs so far | 191.5 min elapsed
04:36:07 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 16071 (vs 160650 result rows — dedup saved 90%)
04:36:07 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-musique/outputs/repairs/results.jsonl
(EngineCore pid=30809) INFO 07-22 04:36:07 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=30809) INFO 07-22 04:36:07 [core.py:1233] Shutdown complete
[rank0]:[W722 04:36:08.393973275 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 6: Evaluation

In [32]:
!python scripts/run_eval.py --config {CONFIG}

04:36:13 | INFO    | stage6 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
04:36:17 | INFO    | stage6 | rows: 161925 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%     95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step      3.6   2.6-4.6%         216            3.92             14.8
                                                       full_restart      6.4   5.0-7.7%         348            6.63             42.8
                                               oracle_targeted__bt2      6.1   4.9-7.4%         346            6.38             42.8
                                     oracle_targeted__bt2__informed      5.2   4.1-6.5%         347            6.45             42.8
                                          oracle_targeted__informed      4.4   3.3-5.6%         320            5.88            100.0
                                    unc__max_token_prob_max__argmax      4.1   3.1-5.2%         207            3.74              9.9
                               unc__max_token_prob_max__argmax__bt2      4.6   3.5-5.7%         281            5.14             26.8
                     unc__max_token_prob_max__argmax__bt2__informed      4.2   3.1-5.3%         278            5.17             26.8
                          unc__max_token_prob_max__argmax__informed      3.1   2.2-4.1%         206            3.76              9.9
                          unc__max_token_prob_max__cascade_gradient      3.7   2.7-4.7%         229            4.23             11.5
                     unc__max_token_prob_max__cascade_gradient__bt2      4.9   3.7-6.1%         299            5.53             29.6
           unc__max_token_prob_max__cascade_gradient__bt2__informed      4.4   3.3-5.6%         300            5.60             29.6
                unc__max_token_prob_max__cascade_gradient__informed      3.2   2.3-4.2%         230            4.26             11.5
                          unc__max_token_prob_max__cascade_upstream      4.6   3.5-5.7%         281            5.14             26.8
                     unc__max_token_prob_max__cascade_upstream__bt2      5.6   4.4-7.0%         330            6.04             39.5
           unc__max_token_prob_max__cascade_upstream__bt2__informed      5.2   4.0-6.4%         329            6.10             39.5
                unc__max_token_prob_max__cascade_upstream__informed      4.2   3.1-5.3%         278            5.17             26.8
                          unc__max_token_prob_max__cascade_weighted      5.2   4.0-6.4%         304            5.57             22.8
                     unc__max_token_prob_max__cascade_weighted__bt2      5.6   4.3-6.9%         342            6.26             41.2
           unc__max_token_prob_max__cascade_weighted__bt2__informed      5.2   4.1-6.5%         342            6.34             41.2
                unc__max_token_prob_max__cascade_weighted__informed      4.8   3.7-6.0%         302            5.60             22.8
                  unc__max_token_prob_max__earliest_above_threshold      4.7   3.5-5.9%         256            4.68             14.1
             unc__max_token_prob_max__earliest_above_threshold__bt2      5.2   4.1-6.5%         318            5.81             38.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed      4.8   3.7-6.0%         315            5.82             38.8
        unc__max_token_prob_max__earliest_above_threshold__informed      3.2   2.3-4.2%         254            4.71             14.1
                                      unc__max_token_prob_max__topk      4.4   3.3-5.6%         288            5.28             20.5
                                 unc__max_token_prob_max__topk__bt2      5.1   3.9-6.3%         337            6.16             44.0
                       unc__max_token_prob_max__topk__bt2__informed      5.1   3.9-6.3%         337            6.25             44.0
                            unc__max_token_prob_max__topk__informed      3.6   2.7-4.6%         287            5.34             20.5
                                            unc__perplexity__argmax      3.4   2.4-4.4%         209            3.78              6.4
                                       unc__perplexity__argmax__bt2      5.1   3.9-6.3%         283            5.15             31.3
                             unc__perplexity__argmax__bt2__informed      4.9   3.7-6.0%         281            5.19             31.3
                                  unc__perplexity__argmax__informed      2.9   2.0-3.8%         206            3.79              6.4
                                  unc__perplexity__cascade_gradient      3.5   2.6-4.5%         229            4.19              9.2
                             unc__perplexity__cascade_gradient__bt2      4.8   3.7-6.0%         300            5.50             34.1
                   unc__perplexity__cascade_gradient__bt2__informed      4.1   3.1-5.2%         297            5.52             34.1
                        unc__perplexity__cascade_gradient__informed      3.5   2.6-4.5%         228            4.22              9.2
                                  unc__perplexity__cascade_upstream      5.1   3.9-6.3%         283            5.15             31.3
                             unc__perplexity__cascade_upstream__bt2      5.8   4.5-7.1%         330            6.07             38.6
                   unc__perplexity__cascade_upstream__bt2__informed      4.7   3.6-5.9%         329            6.14             38.6
                        unc__perplexity__cascade_upstream__informed      4.9   3.7-6.0%         281            5.19             31.3
                                  unc__perplexity__cascade_weighted      3.9   2.9-5.0%         285            5.24             16.9
                             unc__perplexity__cascade_weighted__bt2      5.3   4.2-6.6%         333            6.06             45.2
                   unc__perplexity__cascade_weighted__bt2__informed      5.5   4.2-6.8%         332            6.11             45.2
                        unc__perplexity__cascade_weighted__informed      4.2   3.1-5.3%         283            5.27             16.9
                          unc__perplexity__earliest_above_threshold      4.4   3.3-5.6%         258            4.72             11.1
                     unc__perplexity__earliest_above_threshold__bt2      5.0   3.8-6.3%         320            5.82             43.8
           unc__perplexity__earliest_above_threshold__bt2__informed      5.4   4.2-6.7%         318            5.88             43.8
                unc__perplexity__earliest_above_threshold__informed      3.9   2.9-5.0%         256            4.76             11.1
                                              unc__perplexity__topk      4.6   3.5-5.7%         285            5.25             19.1
                                         unc__perplexity__topk__bt2      5.2   4.0-6.4%         335            6.13             48.5
                               unc__perplexity__topk__bt2__informed      5.2   4.1-6.5%         335            6.23             48.5
                                    unc__perplexity__topk__informed      4.5   3.4-5.7%         285            5.30             19.1
                                      unc__self_consistency__argmax      3.9   2.9-5.0%         210            3.79             12.9
                                 unc__self_consistency__argmax__bt2      5.2   4.1-6.5%         281            5.10             24.9
                       unc__self_consistency__argmax__bt2__informed      4.4   3.3-5.6%         281            5.19             24.9
                            unc__self_consistency__argmax__informed      2.8   2.0-3.8%         210            3.86             12.9
                            unc__self_consistency__cascade_gradient      4.0   3.0-5.1%         236            4.28             15.1
                       unc__self_consistency__cascade_gradient__bt2      4.9   3.8-6.2%         305            5.58             32.2
             unc__self_consistency__cascade_gradient__bt2__informed      4.4   3.3-5.6%         302            5.61             32.2
                  unc__self_consistency__cascade_gradient__informed      3.1   2.1-4.1%         237            4.39             15.1
                            unc__self_consistency__cascade_upstream      5.2   4.1-6.5%         281            5.10             24.9
                       unc__self_consistency__cascade_upstream__bt2      5.2   4.1-6.5%         328            6.03             40.0
             unc__self_consistency__cascade_upstream__bt2__informed      5.7   4.5-7.1%         327            6.08             40.0
                  unc__self_consistency__cascade_upstream__informed      4.4   3.3-5.6%         281            5.19             24.9
                            unc__self_consistency__cascade_weighted      4.2   3.2-5.4%         285            5.25             25.4
                       unc__self_consistency__cascade_weighted__bt2      5.4   4.2-6.7%         334            6.10             39.8
             unc__self_consistency__cascade_weighted__bt2__informed      5.2   4.1-6.5%         332            6.15             39.8
                  unc__self_consistency__cascade_weighted__informed      4.0   3.0-5.1%         284            5.31             25.4
                    unc__self_consistency__earliest_above_threshold      4.9   3.7-6.1%         254            4.63             16.9
               unc__self_consistency__earliest_above_threshold__bt2      5.2   4.1-6.5%         315            5.76             35.1
     unc__self_consistency__earliest_above_threshold__bt2__informed      4.7   3.6-5.9%         313            5.80             35.1
          unc__self_consistency__earliest_above_threshold__informed      4.1   3.1-5.2%         252            4.69             16.9
                                        unc__self_consistency__topk      4.7   3.6-5.9%         285            5.26             23.8
                                   unc__self_consistency__topk__bt2      5.1   3.9-6.3%         336            6.16             40.0
                         unc__self_consistency__topk__bt2__informed      4.9   3.8-6.1%         334            6.22             40.0
                              unc__self_consistency__topk__informed      4.7   3.6-5.9%         284            5.33             23.8
                                     unc__token_entropy_max__argmax      3.8   2.8-4.9%         200            3.60              9.9
                                unc__token_entropy_max__argmax__bt2      4.6   3.5-5.8%         276            5.02             26.1
                      unc__token_entropy_max__argmax__bt2__informed      4.4   3.3-5.6%         272            5.06             26.1
                           unc__token_entropy_max__argmax__informed      3.0   2.1-3.9%         198            3.62              9.9
                           unc__token_entropy_max__cascade_gradient      3.2   2.3-4.2%         234            4.32             12.0
                      unc__token_entropy_max__cascade_gradient__bt2      5.2   4.1-6.5%         304            5.62             32.0
            unc__token_entropy_max__cascade_gradient__bt2__informed      4.9   3.7-6.0%         303            5.64             32.0
                 unc__token_entropy_max__cascade_gradient__informed      3.4   2.5-4.5%         234            4.34             12.0
                           unc__token_entropy_max__cascade_upstream      4.6   3.5-5.8%         276            5.02             26.1
                      unc__token_entropy_max__cascade_upstream__bt2      5.6   4.3-6.8%         326            5.99             39.8
            unc__token_entropy_max__cascade_upstream__bt2__informed      4.9   3.7-6.0%         324            6.04             39.8
                 unc__token_entropy_max__cascade_upstream__informed      4.4   3.3-5.6%         272            5.06             26.1
                           unc__token_entropy_max__cascade_weighted      4.4   3.3-5.6%         296            5.42             22.1
                      unc__token_entropy_max__cascade_weighted__bt2      5.4   4.2-6.7%         339            6.20             41.6
            unc__token_entropy_max__cascade_weighted__bt2__informed      5.0   3.8-6.2%         338            6.26             41.6
                 unc__token_entropy_max__cascade_weighted__informed      4.7   3.6-5.9%         293            5.42             22.1
                   unc__token_entropy_max__earliest_above_threshold      4.2   3.1-5.2%         250            4.53             15.5
              unc__token_entropy_max__earliest_above_threshold__bt2      5.0   3.8-6.3%         314            5.72             40.7
    unc__token_entropy_max__earliest_above_threshold__bt2__informed      4.4   3.3-5.5%         312            5.80             40.7
         unc__token_entropy_max__earliest_above_threshold__informed      3.4   2.4-4.4%         247            4.55             15.5
                                       unc__token_entropy_max__topk      4.4   3.3-5.6%         278            5.09             20.5
                                  unc__token_entropy_max__topk__bt2      4.8   3.6-6.0%         333            6.10             44.5
                        unc__token_entropy_max__topk__bt2__informed      4.6   3.5-5.8%         332            6.16             44.5
                             unc__token_entropy_max__topk__informed      3.7   2.7-4.8%         278            5.16             20.5
                                 unc__verbalized_confidence__argmax      3.1   2.1-4.1%         204            3.67              8.5
                            unc__verbalized_confidence__argmax__bt2      4.3   3.3-5.4%         271            4.94             20.9
                  unc__verbalized_confidence__argmax__bt2__informed      4.0   3.0-5.1%         268            5.01             20.9
                       unc__verbalized_confidence__argmax__informed      2.4   1.6-3.2%         204            3.75              8.5
                       unc__verbalized_confidence__cascade_gradient      3.2   2.3-4.2%         209            3.78              7.8
                  unc__verbalized_confidence__cascade_gradient__bt2      4.6   3.5-5.7%         281            5.13             31.8
        unc__verbalized_confidence__cascade_gradient__bt2__informed      4.3   3.2-5.5%         279            5.17             31.8
             unc__verbalized_confidence__cascade_gradient__informed      2.5   1.7-3.4%         208            3.81              7.8
                       unc__verbalized_confidence__cascade_upstream      4.3   3.3-5.4%         271            4.94             20.9
                  unc__verbalized_confidence__cascade_upstream__bt2      5.2   4.1-6.5%         322            5.91             36.2
        unc__verbalized_confidence__cascade_upstream__bt2__informed      4.6   3.5-5.8%         322            6.00             36.2
             unc__verbalized_confidence__cascade_upstream__informed      4.0   3.0-5.1%         268            5.01             20.9
                       unc__verbalized_confidence__cascade_weighted      3.4   2.5-4.5%         256            4.66             13.6
                  unc__verbalized_confidence__cascade_weighted__bt2      4.6   3.5-5.7%         308            5.65             30.6
        unc__verbalized_confidence__cascade_weighted__bt2__informed      3.9   2.9-5.0%         306            5.70             30.6
             unc__verbalized_confidence__cascade_weighted__informed      3.1   2.1-4.0%         254            4.71             13.6
               unc__verbalized_confidence__earliest_above_threshold      3.8   2.8-4.9%         251            4.54             12.2
          unc__verbalized_confidence__earliest_above_threshold__bt2      4.6   3.5-5.8%         306            5.57             28.7
unc__verbalized_confidence__earliest_above_threshold__bt2__informed      4.2   3.1-5.4%         303            5.65             28.7
     unc__verbalized_confidence__earliest_above_threshold__informed      3.2   2.3-4.2%         249            4.61             12.2
                                   unc__verbalized_confidence__topk      4.1   3.1-5.2%         285            5.19             22.1
                              unc__verbalized_confidence__topk__bt2      4.5   3.4-5.7%         326            5.96             33.9
                    unc__verbalized_confidence__topk__bt2__informed      4.6   3.5-5.7%         323            6.03             33.9
                         unc__verbalized_confidence__topk__informed      3.8   2.8-4.9%         284            5.28             22.1
                                           uncertainty_ensemble_any     16.1 14.1-18.1%       15314          281.52             84.9
                                                    oracle_targeted      5.2   4.0-6.4%         320            5.84            100.0
Traceback (most recent call last):
  File "/content/agent-repair/scripts/run_eval.py", line 461, in <module>
    main()
  File "/content/agent-repair/scripts/run_eval.py", line 91, in main
    u = df[df.strategy.isin(bt0_strats)] if bt0_strats else df[df.strategy.isin(unc_strats)]
                                            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'bt0_strats' where it is not associated with a value

---
## Results

In [33]:
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())
else:
    print('Summary not yet generated. Run Stage 6 first.')

Summary not yet generated. Run Stage 6 first.

In [34]:
import pandas as pd

results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)
else:
    print('Results table not yet generated. Run Stage 6 first.')

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,3.6,2.6-4.6%,216,3.92,14.8
1,full_restart,6.4,5.0-7.7%,348,6.63,42.8
2,oracle_targeted__bt2,6.1,4.9-7.4%,346,6.38,42.8
3,oracle_targeted__bt2__informed,5.2,4.1-6.5%,347,6.45,42.8
4,oracle_targeted__informed,4.4,3.3-5.6%,320,5.88,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,4.5,3.4-5.7%,326,5.96,33.9
123,unc__verbalized_confidence__topk__bt2__informed,4.6,3.5-5.7%,323,6.03,33.9
124,unc__verbalized_confidence__topk__informed,3.8,2.8-4.9%,284,5.28,22.1
125,uncertainty_ensemble_any,16.1,14.1-18.1%,15314,281.52,84.9
126,oracle_targeted,5.2,4.0-6.4%,320,5.84,100.0

In [35]:
import glob
from IPython.display import display, Image

fig_dir = cfg.path('figures')
figs = sorted(glob.glob(os.path.join(fig_dir, '*.png')))
if figs:
    for f in figs:
        print(f'\n--- {os.path.basename(f)} ---')
        display(Image(filename=f, width=800))
else:
    print('No figures yet. Run Stage 6 first.')

No figures yet. Run Stage 6 first.

---
## Re-run Stages 4–6 with Cascade-Aware Strategies

**Use this after you already have stages 1–3 completed** (trajectories, uncertainty, annotations).
This pulls the latest code (with cascade rules), clears only localization/repair/eval outputs,
and re-runs stages 4→5→6 in one cell. ~3-4 hours on A100-80GB for 500 questions.

In [36]:
import os, shutil

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_musique.yaml'

# 1. Pull latest code with cascade-aware strategies
os.chdir(REPO_DIR)
!git pull

# 2. Clear ONLY stages 4-6 outputs (keep trajectories, uncertainty, annotations)
drive_base = '/content/drive/MyDrive/agent-repair-musique'
for base in [REPO_DIR, drive_base]:
    for d in ['outputs/localization', 'outputs/repairs', 'outputs/tables', 'outputs/figures']:
        p = os.path.join(base, d)
        if os.path.exists(p):
            shutil.rmtree(p)
            print(f'Cleared {p}')

# 3. Clear checkpoint files for stages 4-6 (these live in outputs/logs/)
for base in [REPO_DIR, drive_base]:
    for ckpt in ['outputs/logs/stage4_localize.jsonl',
                 'outputs/logs/stage5_repair.jsonl',
                 'outputs/logs/stage6_eval.jsonl']:
        p = os.path.join(base, ckpt)
        if os.path.exists(p):
            os.remove(p)
            print(f'Removed checkpoint: {p}')

print('\nStages 1-3 data preserved. Ready to re-run 4→5→6.')

Already up to date.
Cleared /content/drive/MyDrive/agent-repair-musique/outputs/localization
Cleared /content/drive/MyDrive/agent-repair-musique/outputs/repairs
Cleared /content/drive/MyDrive/agent-repair-musique/outputs/tables
Cleared /content/drive/MyDrive/agent-repair-musique/outputs/figures
Removed checkpoint: /content/drive/MyDrive/agent-repair-musique/outputs/logs/stage5_repair.jsonl

Stages 1-3 data preserved. Ready to re-run 4→5→6.

In [37]:
# Run stages 4 → 5 → 6 sequentially (run this and go to sleep)
import time

for stage in ['run_localize', 'run_repair', 'run_eval']:
    t0 = time.time()
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG}
    elapsed = (time.time() - t0) / 60
    print(f'  ✓ {stage} done in {elapsed:.1f} min\n')

print('\n' + '='*60)
print('  ALL DONE — check results below')
print('='*60)

============================================================
  run_localize
============================================================
04:36:35 | INFO    | stage4 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
04:36:37 | INFO    | stage4 | records: 4250 (425 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.129           0.322  0.328          0.169              0.454     0.231     0.346  425
max_token_prob_max            0.099           0.282  0.296          0.141              0.440     0.200     0.282  425
token_entropy_max             0.099           0.242  0.292          0.155              0.369     0.200     0.287  425
verbalized_confidence         0.085           0.242  0.323          0.122              0.339     0.221     0.379  425
token_entropy_mean_k50        0.073           0.268  0.268          0.089              0.379     0.153     0.271  425
token_entropy_mean            0.073           0.268  0.268          0.089              0.379     0.153     0.271  425
token_entropy_mean_k20        0.073           0.268  0.268          0.089              0.379     0.153     0.271  425
token_entropy_mean_k5         0.068           0.278  0.269          0.101              0.407     0.165     0.273  425
max_token_prob_mean           0.064           0.278  0.270          0.111              0.431     0.176     0.271  425
perplexity                    0.064           0.271  0.270          0.111              0.449     0.176     0.268  425
04:36:37 | INFO    | stage4 | Random top-1 baseline: 0.153 | best metric: self_consistency (0.129)
04:36:37 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-musique/outputs/tables/localization_summary.csv
  ✓ run_localize done in 0.1 min


============================================================
  run_repair
============================================================
04:36:37 | INFO    | stage5 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
04:36:37 | INFO    | stage5 | Dataset: musique (env: MuSiQueEnv)
04:36:38 | INFO    | stage5 | 425 failed x 126 strategies x 3 seeds = 160650 result rows (actual GPU runs are far fewer: dedup)
04:36:39 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-22 04:36:42.828600: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-22 04:36:42.901440: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-22 04:36:53 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-22 04:36:54 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-22 04:36:54 [model.py:1678] Using max model len 8192
INFO 07-22 04:36:55 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-22 04:36:55 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00, 10.69it/s]
INFO 07-22 04:36:56 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-22 04:36:57 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=81035) INFO 07-22 04:37:16 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=81035) INFO 07-22 04:37:16 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:36817 backend=nccl
(EngineCore pid=81035) INFO 07-22 04:37:16 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=81035) INFO 07-22 04:37:17 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=81035) INFO 07-22 04:37:17 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=81035) INFO 07-22 04:37:18 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=81035) INFO 07-22 04:37:18 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=81035) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=81035) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.18s/it]
(EngineCore pid=81035) INFO 07-22 04:37:25 [default_loader.py:384] Loading weights took 5.98 seconds
(EngineCore pid=81035) INFO 07-22 04:37:30 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.329389 seconds
(EngineCore pid=81035) INFO 07-22 04:37:38 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=81035) INFO 07-22 04:37:38 [backends.py:1111] Dynamo bytecode transform time: 8.11 s
(EngineCore pid=81035) INFO 07-22 04:37:43 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.090 s
(EngineCore pid=81035) INFO 07-22 04:37:43 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=81035) INFO 07-22 04:37:43 [monitor.py:48] torch.compile took 12.40 s in total
(EngineCore pid=81035) INFO 07-22 04:37:46 [monitor.py:76] Initial profiling/warmup run took 3.06 s
(EngineCore pid=81035) INFO 07-22 04:37:47 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=81035) INFO 07-22 04:37:47 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=81035) INFO 07-22 04:37:49 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=81035) INFO 07-22 04:37:50 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=81035) INFO 07-22 04:37:50 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=81035) INFO 07-22 04:37:50 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=81035) INFO 07-22 04:37:50 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.06it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.33it/s]
(EngineCore pid=81035) INFO 07-22 04:38:02 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=81035) INFO 07-22 04:38:02 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=81035) INFO 07-22 04:38:02 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.65 seconds
(EngineCore pid=81035) INFO 07-22 04:38:04 [vllm.py:790] Asynchronous scheduling is enabled.
04:38:04 | INFO    | stage5 | --- seed 0 ---
04:47:43 | INFO    | stage5 | seed 0: 64/425 questions | 814 GPU repairs so far | 9.7 min elapsed
04:57:25 | INFO    | stage5 | seed 0: 128/425 questions | 1611 GPU repairs so far | 19.3 min elapsed
05:07:04 | INFO    | stage5 | seed 0: 192/425 questions | 2447 GPU repairs so far | 29.0 min elapsed
05:17:21 | INFO    | stage5 | seed 0: 256/425 questions | 3311 GPU repairs so far | 39.3 min elapsed
05:27:26 | INFO    | stage5 | seed 0: 320/425 questions | 4146 GPU repairs so far | 49.4 min elapsed
05:38:11 | INFO    | stage5 | seed 0: 384/425 questions | 5056 GPU repairs so far | 60.1 min elapsed
05:44:43 | INFO    | stage5 | seed 0: 425/425 questions | 5572 GPU repairs so far | 66.7 min elapsed
05:44:43 | INFO    | stage5 | --- seed 1 ---
05:54:27 | INFO    | stage5 | seed 1: 64/425 questions | 6388 GPU repairs so far | 76.4 min elapsed
06:04:18 | INFO    | stage5 | seed 1: 128/425 questions | 7183 GPU repairs so far | 86.2 min elapsed
06:13:55 | INFO    | stage5 | seed 1: 192/425 questions | 8018 GPU repairs so far | 95.8 min elapsed
06:24:11 | INFO    | stage5 | seed 1: 256/425 questions | 8882 GPU repairs so far | 106.1 min elapsed
06:34:15 | INFO    | stage5 | seed 1: 320/425 questions | 9715 GPU repairs so far | 116.2 min elapsed
06:45:06 | INFO    | stage5 | seed 1: 384/425 questions | 10622 GPU repairs so far | 127.0 min elapsed
06:51:40 | INFO    | stage5 | seed 1: 425/425 questions | 11143 GPU repairs so far | 133.6 min elapsed
06:51:40 | INFO    | stage5 | --- seed 2 ---
07:01:24 | INFO    | stage5 | seed 2: 64/425 questions | 11956 GPU repairs so far | 143.3 min elapsed
07:11:14 | INFO    | stage5 | seed 2: 128/425 questions | 12755 GPU repairs so far | 153.2 min elapsed
07:20:55 | INFO    | stage5 | seed 2: 192/425 questions | 13586 GPU repairs so far | 162.8 min elapsed
07:31:17 | INFO    | stage5 | seed 2: 256/425 questions | 14448 GPU repairs so far | 173.2 min elapsed
07:41:15 | INFO    | stage5 | seed 2: 320/425 questions | 15287 GPU repairs so far | 183.2 min elapsed
07:52:13 | INFO    | stage5 | seed 2: 384/425 questions | 16197 GPU repairs so far | 194.2 min elapsed
07:58:43 | INFO    | stage5 | seed 2: 425/425 questions | 16714 GPU repairs so far | 200.6 min elapsed
07:58:43 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 16714 (vs 160650 result rows — dedup saved 90%)
07:58:43 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-musique/outputs/repairs/results.jsonl
(EngineCore pid=81035) INFO 07-22 07:58:43 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=81035) INFO 07-22 07:58:43 [core.py:1233] Shutdown complete
[rank0]:[W722 07:58:43.097947635 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
  ✓ run_repair done in 202.2 min


============================================================
  run_eval
============================================================
07:58:48 | INFO    | stage6 | config=config/config_colab_musique.yaml  base=/content/drive/MyDrive/agent-repair-musique
07:58:52 | INFO    | stage6 | rows: 161925 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%     95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step      3.8   2.8-4.9%         216            3.90             14.8
                                                       full_restart      5.9   4.6-7.2%         348            6.62             42.8
                                               oracle_targeted__bt2      5.6   4.4-6.8%         347            6.39             42.8
                                     oracle_targeted__bt2__informed      5.6   4.4-7.0%         347            6.43             42.8
                                          oracle_targeted__informed      4.9   3.8-6.0%         321            5.87            100.0
                                    unc__max_token_prob_max__argmax      4.2   3.1-5.2%         208            3.74              9.9
                               unc__max_token_prob_max__argmax__bt2      4.2   3.1-5.4%         282            5.14             26.8
                     unc__max_token_prob_max__argmax__bt2__informed      4.3   3.2-5.5%         278            5.16             26.8
                          unc__max_token_prob_max__argmax__informed      3.2   2.3-4.2%         205            3.75              9.9
                          unc__max_token_prob_max__cascade_gradient      3.6   2.7-4.6%         229            4.22             11.5
                     unc__max_token_prob_max__cascade_gradient__bt2      4.1   3.1-5.2%         300            5.53             29.6
           unc__max_token_prob_max__cascade_gradient__bt2__informed      4.6   3.5-5.7%         300            5.58             29.6
                unc__max_token_prob_max__cascade_gradient__informed      3.3   2.4-4.3%         230            4.25             11.5
                          unc__max_token_prob_max__cascade_upstream      4.2   3.1-5.4%         282            5.14             26.8
                     unc__max_token_prob_max__cascade_upstream__bt2      5.2   4.0-6.4%         331            6.07             39.5
           unc__max_token_prob_max__cascade_upstream__bt2__informed      5.2   4.1-6.5%         329            6.09             39.5
                unc__max_token_prob_max__cascade_upstream__informed      4.3   3.2-5.5%         278            5.16             26.8
                          unc__max_token_prob_max__cascade_weighted      4.6   3.5-5.8%         305            5.57             22.8
                     unc__max_token_prob_max__cascade_weighted__bt2      4.9   3.8-6.1%         342            6.26             41.2
           unc__max_token_prob_max__cascade_weighted__bt2__informed      5.6   4.3-6.9%         341            6.31             41.2
                unc__max_token_prob_max__cascade_weighted__informed      4.9   3.8-6.2%         302            5.59             22.8
                  unc__max_token_prob_max__earliest_above_threshold      4.9   3.8-6.2%         257            4.67             14.1
             unc__max_token_prob_max__earliest_above_threshold__bt2      4.7   3.6-5.9%         319            5.82             38.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed      5.0   3.8-6.3%         315            5.80             38.8
        unc__max_token_prob_max__earliest_above_threshold__informed      3.2   2.3-4.2%         254            4.70             14.1
                                      unc__max_token_prob_max__topk      4.2   3.2-5.3%         289            5.27             20.5
                                 unc__max_token_prob_max__topk__bt2      4.5   3.4-5.7%         338            6.16             44.0
                       unc__max_token_prob_max__topk__bt2__informed      5.2   4.1-6.5%         337            6.22             44.0
                            unc__max_token_prob_max__topk__informed      3.7   2.7-4.8%         287            5.34             20.5
                                            unc__perplexity__argmax      3.3   2.4-4.3%         209            3.77              6.4
                                       unc__perplexity__argmax__bt2      4.6   3.5-5.8%         283            5.15             31.3
                             unc__perplexity__argmax__bt2__informed      4.9   3.8-6.0%         281            5.18             31.3
                                  unc__perplexity__argmax__informed      2.8   2.0-3.8%         206            3.80              6.4
                                  unc__perplexity__cascade_gradient      3.3   2.4-4.3%         228            4.18              9.2

In [38]:
# View cascade-aware results
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())

import pandas as pd
results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)

import glob
from IPython.display import display, Image
figs = sorted(glob.glob(os.path.join(cfg.path('figures'), '*.png')))
for f in figs:
    print(f'\n--- {os.path.basename(f)} ---')
    display(Image(filename=f, width=800))

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,3.8,2.8-4.9%,216,3.90,14.8
1,full_restart,5.9,4.6-7.2%,348,6.62,42.8
2,oracle_targeted__bt2,5.6,4.4-6.8%,347,6.39,42.8
3,oracle_targeted__bt2__informed,5.6,4.4-7.0%,347,6.43,42.8
4,oracle_targeted__informed,4.9,3.8-6.0%,321,5.87,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,3.8,2.8-4.9%,326,5.97,33.9
123,unc__verbalized_confidence__topk__bt2__informed,4.6,3.5-5.7%,323,6.02,33.9
124,unc__verbalized_confidence__topk__informed,3.9,2.9-5.0%,285,5.28,22.1
125,uncertainty_ensemble_any,16.2,14.3-18.3%,15317,281.18,84.9
126,oracle_targeted,4.9,3.7-6.0%,320,5.82,100.0