# Agent Repair Pipeline — FEVER

**ICLR Experiment Pipeline — Colab A100-80GB + Qwen2.5-32B-Instruct-AWQ**

| Stage | What it does | ~Time (A100-80GB, 500 Qs) |
|---|---|---|
| 0 | Download FEVER, create folders | 1 min |
| 1 | ReAct trajectory generation (Qwen2.5-32B-Instruct-AWQ) | ~1-2 h |
| 2 | Step-level uncertainty scoring | ~1-2 h |
| 3 | 72B judge error annotation | ~1-2 h |
| 4 | Localization scoring (+ cascade-aware rules) | < 1 min |
| 5 | 126 repair strategies (backtrack × nudge type ablation) | ~4-6 h |
| 6 | Tables, stats, figures, ablation analysis | < 1 min |

**Every stage is resumable** — if Colab disconnects, re-run the cell and it picks up where it left off.

---
## 0. Setup

In [1]:
# Verify GPU — should show A100
!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

NVIDIA A100-SXM4-80GB, 81920 MiB

In [2]:
# Mount Google Drive for persistent storage
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_fever.yaml'

if not os.path.exists(REPO_DIR):
    !git clone https://github.com/kishormorol/agent-repair.git {REPO_DIR}
else:
    !cd {REPO_DIR} && git pull

os.chdir(REPO_DIR)
print(f'Working directory: {os.getcwd()}')

Cloning into '/content/agent-repair'...
remote: Enumerating objects: 214, done.
remote: Counting objects: 100% (214/214), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 214 (delta 107), reused 171 (delta 64), pack-reused 0 (from 0)
Receiving objects: 100% (214/214), 316.57 KiB | 8.33 MiB/s, done.
Resolving deltas: 100% (107/107), done.
Working directory: /content/agent-repair

In [4]:
# Check Colab's CUDA version first
!nvcc --version 2>/dev/null || echo "nvcc not found"
!python -c "import torch; print(f'torch CUDA: {torch.version.cuda}')" 2>/dev/null || echo "torch not installed yet"
!nvidia-smi | grep "CUDA Version"

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0
torch CUDA: 12.8
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |

In [5]:
# Install vLLM — pinned to 0.19.0 (last version with CUDA 12 default wheels)
# vLLM >= 0.20 ships CUDA 13 wheels which don't work on Colab's CUDA 12.x
!pip uninstall -y vllm 2>/dev/null
!pip install -q "vllm==0.19.0" 2>&1 | tail -5

# Install remaining dependencies
!pip install -q "transformers>=4.57.0" "tokenizers>=0.21.0" accelerate \
    huggingface_hub datasets scipy scikit-learn pandas pyarrow \
    pyyaml tqdm matplotlib seaborn statsmodels 2>&1 | tail -3

print('\n--- Installation complete ---')

gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.6 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.6 which is incompatible.
google-adk 2.4.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.4.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.

--- Installation complete ---

In [6]:
# Quick sanity check: can vLLM see the GPU?
import torch, vllm
print(f'torch:  {torch.__version__}')
print(f'vLLM:   {vllm.__version__}')
print(f'CUDA:   {torch.version.cuda}')
print(f'GPU:    {torch.cuda.get_device_name(0)}')
print(f'VRAM:   {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

torch:  2.10.0+cu128
vLLM:   0.19.0
CUDA:   12.8
GPU:    NVIDIA A100-SXM4-80GB
VRAM:   85.1 GB

In [7]:
# Clear previous data
import shutil, os
drive_base = '/content/drive/MyDrive/agent-repair-fever'
for d in ['outputs', 'data/processed']:
    p = os.path.join(drive_base, d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
for d in ['outputs', 'data/processed']:
    p = os.path.join('/content/agent-repair', d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
print('Ready for fresh run with FEVER')

Ready for fresh run with FEVER

In [26]:
!cd /content/agent-repair && git pull

remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 1.65 KiB | 1.65 MiB/s, done.
From https://github.com/kishormorol/agent-repair
   d62fdd9..99e468c  main       -> origin/main
Updating d62fdd9..99e468c
Fast-forward
 src/env/fever_env.py | 182 ++++++++++++++++++++-------------------------------
 1 file changed, 72 insertions(+), 110 deletions(-)

In [27]:
!rm -rf /content/drive/MyDrive/agent-repair-fever/data

---
## Smoke Test (20 questions, ~10-15 min)

**Run this first** to verify everything works before committing A100 units to the full 500-question run.

In [28]:
stages = ['run_setup', 'run_generate', 'run_uncertainty', 'run_annotate',
          'run_localize', 'run_repair', 'run_eval']

for stage in stages:
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG} --limit 20
    print()

============================================================
  run_setup
============================================================
15:47:35 | INFO    | setup | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
15:47:35 | INFO    | setup | Dataset: fever (file: fever_dev.json)
15:47:35 | INFO    | setup | Downloading fever via registry download function...
  Trying: https://s3-eu-west-1.amazonaws.com/fever.public/shared_task_dev.jsonl
    failed: HTTP Error 403: Forbidden
  Trying: https://fever.ai/download/fever/shared_task_dev.jsonl
15:47:35 | INFO    | setup | Downloaded 19998 records for fever.
15:47:36 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-fever/data/raw/fever_dev.json (7.5 MB, 19998 questions)
15:47:36 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-fever


============================================================
  run_generate
============================================================
15:47:36 | INFO    | stage1 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
15:47:36 | INFO    | stage1 | Dataset: fever (env: FEVEREnv)
15:47:36 | INFO    | stage1 | Pool: 500 questions
15:47:36 | INFO    | stage1 | To process: 20 of 20 (0 already done)
15:47:38 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 15:47:42.049426: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 15:47:42.120784: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tokenizer_config.json: 7.30kB [00:00, 32.0MB/s]
vocab.json: 2.78MB [00:00, 93.2MB/s]
merges.txt: 1.67MB [00:00, 128MB/s]
tokenizer.json: 7.03MB [00:00, 154MB/s]
INFO 07-21 15:47:55 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
config.json: 100% 841/841 [00:00<00:00, 8.71MB/s]
INFO 07-21 15:48:15 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 15:48:15 [model.py:1678] Using max model len 8192
INFO 07-21 15:48:15 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 15:48:15 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
model.safetensors.index.json: 143kB [00:00, 226MB/s]
Parse safetensors files: 100% 5/5 [00:01<00:00,  4.86it/s]
INFO 07-21 15:48:17 [vllm.py:790] Asynchronous scheduling is enabled.
generation_config.json: 100% 243/243 [00:00<00:00, 1.67MB/s]
WARNING 07-21 15:48:18 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=20749) INFO 07-21 15:48:36 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=20749) INFO 07-21 15:48:36 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:36115 backend=nccl
(EngineCore pid=20749) INFO 07-21 15:48:36 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=20749) INFO 07-21 15:48:37 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=20749) INFO 07-21 15:48:37 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=20749) INFO 07-21 15:48:38 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=20749) INFO 07-21 15:48:38 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=20749) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=20749) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
model-00005-of-00005.safetensors:   0% 0.00/3.48G [00:00<?, ?B/s]
model-00001-of-00005.safetensors:   0% 0.00/3.94G [00:00<?, ?B/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00003-of-00005.safetensors:   0% 0.00/3.95G [00:00<?, ?B/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00004-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:   7% 268M/3.98G [00:01<00:24, 151MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00005-of-00005.safetensors:   8% 268M/3.48G [00:02<00:24, 132MB/s]
model-00001-of-00005.safetensors:   7% 268M/3.94G [00:02<00:27, 132MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00004-of-00005.safetensors:   7% 268M/3.98G [00:02<00:31, 118MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:   8% 335M/3.98G [00:02<00:28, 127MB/s]
model-00001-of-00005.safetensors:  10% 404M/3.94G [00:02<00:21, 168MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00004-of-00005.safetensors:   8% 335M/3.98G [00:02<00:26, 138MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  10% 335M/3.48G [00:02<00:26, 117MB/s]
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  12% 402M/3.48G [00:04<00:34, 88.6MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00003-of-00005.safetensors:  15% 604M/3.95G [00:04<00:22, 149MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  20% 805M/3.98G [00:04<00:15, 205MB/s]
model-00005-of-00005.safetensors:  29% 1.02G/3.48G [00:08<00:19, 127MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00004-of-00005.safetensors:  13% 536M/3.98G [00:08<01:01, 55.9MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  30% 1.21G/3.98G [00:08<00:20, 139MB/s]
model-00001-of-00005.safetensors:  26% 1.02G/3.94G [00:08<00:24, 120MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00003-of-00005.safetensors:  29% 1.14G/3.95G [00:09<00:22, 124MB/s]
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  37% 1.27G/3.48G [00:12<00:23, 93.2MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  40% 1.61G/3.98G [00:13<00:24, 98.1MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  45% 1.81G/3.98G [00:16<00:24, 86.8MB/s]
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  50% 1.74G/3.48G [00:17<00:18, 93.5MB/s]
model-00001-of-00005.safetensors:  43% 1.68G/3.94G [00:17<00:25, 90.0MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00003-of-00005.safetensors:  46% 1.81G/3.95G [00:17<00:22, 95.2MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  49% 1.94G/3.98G [00:18<00:24, 82.4MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  54% 1.88G/3.48G [00:20<00:20, 77.2MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  51% 2.01G/3.98G [00:20<00:31, 63.1MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  63% 2.19G/3.48G [00:24<00:16, 77.6MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00003-of-00005.safetensors:  56% 2.21G/3.95G [00:24<00:21, 80.0MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  59% 2.35G/3.98G [00:24<00:22, 72.8MB/s]
model-00005-of-00005.safetensors:  71% 2.46G/3.48G [00:31<00:17, 59.4MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  64% 2.55G/3.98G [00:31<00:29, 49.0MB/s]
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  80% 2.80G/3.48G [00:32<00:08, 81.8MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  74% 2.95G/3.98G [00:32<00:12, 83.4MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  82% 2.86G/3.48G [00:32<00:07, 87.3MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  76% 3.02G/3.98G [00:32<00:10, 92.1MB/s]
model-00005-of-00005.safetensors:  84% 2.93G/3.48G [00:33<00:05, 94.6MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  78% 3.09G/3.98G [00:33<00:09, 91.6MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00005-of-00005.safetensors:  86% 3.00G/3.48G [00:34<00:05, 85.4MB/s]
model-00001-of-00005.safetensors:  80% 3.17G/3.94G [00:36<00:09, 80.5MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  86% 3.42G/3.98G [00:37<00:06, 84.3MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00005-of-00005.safetensors: 100% 3.48G/3.48G [00:40<00:00, 84.8MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00004-of-00005.safetensors:  83% 3.29G/3.98G [00:42<00:08, 77.3MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors:  98% 3.89G/3.98G [00:43<00:01, 84.8MB/s]
(EngineCore pid=20749)
model-00002-of-00005.safetensors: 100% 3.98G/3.98G [00:44<00:00, 90.4MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00003-of-00005.safetensors: 100% 3.95G/3.95G [00:44<00:00, 88.5MB/s]
(EngineCore pid=20749)
model-00001-of-00005.safetensors: 100% 3.94G/3.94G [00:44<00:00, 88.1MB/s]
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
(EngineCore pid=20749)
model-00004-of-00005.safetensors: 100% 3.98G/3.98G [00:46<00:00, 85.0MB/s]
(EngineCore pid=20749) INFO 07-21 15:49:26 [weight_utils.py:581] Time spent downloading weights for Qwen/Qwen2.5-32B-Instruct-AWQ: 47.188233 seconds
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.19s/it]
(EngineCore pid=20749) INFO 07-21 15:49:32 [default_loader.py:384] Loading weights took 6.04 seconds
(EngineCore pid=20749) INFO 07-21 15:49:37 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 58.432383 seconds
(EngineCore pid=20749) INFO 07-21 15:49:56 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=20749) INFO 07-21 15:49:56 [backends.py:1111] Dynamo bytecode transform time: 18.54 s
(EngineCore pid=20749) INFO 07-21 15:50:02 [backends.py:372] Cache the graph of compile range (1, 8192) for later use
(EngineCore pid=20749) INFO 07-21 15:50:11 [backends.py:390] Compiling a graph for compile range (1, 8192) takes 14.11 s
(EngineCore pid=20749) INFO 07-21 15:50:16 [decorators.py:640] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=20749) INFO 07-21 15:50:16 [monitor.py:48] torch.compile took 39.03 s in total
(EngineCore pid=20749) INFO 07-21 15:50:20 [monitor.py:76] Initial profiling/warmup run took 3.22 s
(EngineCore pid=20749) INFO 07-21 15:50:30 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=20749) INFO 07-21 15:50:30 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=20749) INFO 07-21 15:50:34 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=20749) INFO 07-21 15:50:34 [gpu_worker.py:436] Available KV cache memory: 51.42 GiB
(EngineCore pid=20749) INFO 07-21 15:50:34 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=20749) INFO 07-21 15:50:34 [kv_cache_utils.py:1319] GPU KV cache size: 210,608 tokens
(EngineCore pid=20749) INFO 07-21 15:50:34 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.71x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.05it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.47it/s]
(EngineCore pid=20749) INFO 07-21 15:50:47 [gpu_model_runner.py:6046] Graph capturing finished in 13 secs, took 0.90 GiB
(EngineCore pid=20749) INFO 07-21 15:50:47 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=20749) INFO 07-21 15:50:47 [core.py:283] init engine (profile, create kv cache, warmup model) took 70.23 seconds
(EngineCore pid=20749) INFO 07-21 15:50:49 [vllm.py:790] Asynchronous scheduling is enabled.
15:51:04 | INFO    | stage1 | 20/20  (1.35 q/s, ETA 0 min)
15:51:04 | INFO    | stage1 | TOTAL 20 | success 2 (10.0%) | FAILED 18
15:51:04 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=20749) INFO 07-21 15:51:04 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=20749) INFO 07-21 15:51:04 [core.py:1233] Shutdown complete
[rank0]:[W721 15:51:04.774151120 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())


============================================================
  run_uncertainty
============================================================
15:51:08 | INFO    | stage2 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
15:51:08 | INFO    | stage2 | Math metrics: 20 of 20 trajectories to do
15:51:09 | INFO    | stage2 | Math metrics done.
15:51:09 | INFO    | stage2 | Sampling metrics: 18 of 18 failed trajectories
15:51:11 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 15:51:14.325532: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 15:51:14.401285: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 15:51:24 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 15:51:25 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 15:51:25 [model.py:1678] Using max model len 8192
INFO 07-21 15:51:27 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 15:51:27 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  8.45it/s]
INFO 07-21 15:51:28 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 15:51:29 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized

In [29]:
# Check smoke test produced output
import glob
tables = glob.glob('outputs/tables/*') + glob.glob('/content/drive/MyDrive/agent-repair-fever/outputs/tables/*')
figs = glob.glob('outputs/figures/*') + glob.glob('/content/drive/MyDrive/agent-repair-fever/outputs/figures/*')
print(f'Tables: {len(tables)}, Figures: {len(figs)}')
if tables or figs:
    print('Smoke test PASSED — safe to run the full pipeline below.')
else:
    print('WARNING: No outputs found. Check the logs above for errors.')

Tables: 4, Figures: 0
Smoke test PASSED — safe to run the full pipeline below.

---
## Full Pipeline (500 questions)

Only run these cells after the smoke test passes. To reset and run fresh, delete the `data/processed/` folder.

### Stage 0: Download FEVER

In [30]:
!python scripts/run_setup.py --config {CONFIG}

16:04:34 | INFO    | setup | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
16:04:34 | INFO    | setup | Dataset: fever (file: fever_dev.json)
16:04:34 | INFO    | setup | Dataset already present: /content/drive/MyDrive/agent-repair-fever/data/raw/fever_dev.json
16:04:34 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-fever/data/raw/fever_dev.json (7.5 MB, 19998 questions)
16:04:34 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-fever

### Stage 1: Generate ReAct Trajectories

In [31]:
!python scripts/run_generate.py --config {CONFIG}

16:04:34 | INFO    | stage1 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
16:04:34 | INFO    | stage1 | Dataset: fever (env: FEVEREnv)
16:04:34 | INFO    | stage1 | Pool: 500 questions
16:04:34 | INFO    | stage1 | To process: 480 of 500 (20 already done)
16:04:36 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 16:04:39.649020: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 16:04:39.724098: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 16:04:49 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 16:04:50 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 16:04:50 [model.py:1678] Using max model len 8192
INFO 07-21 16:04:51 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 16:04:51 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  9.17it/s]
INFO 07-21 16:04:52 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 16:04:53 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=26457) INFO 07-21 16:05:11 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=26457) INFO 07-21 16:05:12 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:53475 backend=nccl
(EngineCore pid=26457) INFO 07-21 16:05:12 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=26457) INFO 07-21 16:05:13 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=26457) INFO 07-21 16:05:13 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=26457) INFO 07-21 16:05:14 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=26457) INFO 07-21 16:05:14 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=26457) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=26457) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.17s/it]
(EngineCore pid=26457) INFO 07-21 16:05:21 [default_loader.py:384] Loading weights took 5.94 seconds
(EngineCore pid=26457) INFO 07-21 16:05:26 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.214589 seconds
(EngineCore pid=26457) INFO 07-21 16:05:34 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=26457) INFO 07-21 16:05:34 [backends.py:1111] Dynamo bytecode transform time: 8.00 s
(EngineCore pid=26457) INFO 07-21 16:05:38 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.005 s
(EngineCore pid=26457) INFO 07-21 16:05:38 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=26457) INFO 07-21 16:05:38 [monitor.py:48] torch.compile took 12.17 s in total
(EngineCore pid=26457) INFO 07-21 16:05:41 [monitor.py:76] Initial profiling/warmup run took 3.01 s
(EngineCore pid=26457) INFO 07-21 16:05:42 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=26457) INFO 07-21 16:05:42 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=26457) INFO 07-21 16:05:45 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=26457) INFO 07-21 16:05:46 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=26457) INFO 07-21 16:05:46 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=26457) INFO 07-21 16:05:46 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=26457) INFO 07-21 16:05:46 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.02it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.36it/s]
(EngineCore pid=26457) INFO 07-21 16:05:58 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=26457) INFO 07-21 16:05:58 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=26457) INFO 07-21 16:05:58 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.51 seconds
(EngineCore pid=26457) INFO 07-21 16:06:00 [vllm.py:790] Asynchronous scheduling is enabled.
16:06:14 | INFO    | stage1 | 32/480  (2.19 q/s, ETA 3 min)
16:06:30 | INFO    | stage1 | 64/480  (2.15 q/s, ETA 3 min)
16:06:45 | INFO    | stage1 | 96/480  (2.11 q/s, ETA 3 min)
16:07:00 | INFO    | stage1 | 128/480  (2.13 q/s, ETA 3 min)
16:07:16 | INFO    | stage1 | 160/480  (2.11 q/s, ETA 3 min)
16:07:33 | INFO    | stage1 | 192/480  (2.07 q/s, ETA 2 min)
16:07:50 | INFO    | stage1 | 224/480  (2.04 q/s, ETA 2 min)
16:08:04 | INFO    | stage1 | 256/480  (2.05 q/s, ETA 2 min)
16:08:20 | INFO    | stage1 | 288/480  (2.05 q/s, ETA 2 min)
16:08:35 | INFO    | stage1 | 320/480  (2.06 q/s, ETA 1 min)
16:08:50 | INFO    | stage1 | 352/480  (2.07 q/s, ETA 1 min)
16:09:05 | INFO    | stage1 | 384/480  (2.07 q/s, ETA 1 min)
16:09:22 | INFO    | stage1 | 416/480  (2.06 q/s, ETA 1 min)
16:09:39 | INFO    | stage1 | 448/480  (2.05 q/s, ETA 0 min)
16:09:52 | INFO    | stage1 | 480/480  (2.06 q/s, ETA 0 min)
16:09:56 | INFO    | stage1 | TOTAL 500 | success 15 (3.0%) | FAILED 485
16:09:56 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=26457) INFO 07-21 16:09:56 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=26457) INFO 07-21 16:09:56 [core.py:1233] Shutdown complete
[rank0]:[W721 16:09:57.283310546 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 2: Step-Level Uncertainty

In [32]:
!python scripts/run_uncertainty.py --config {CONFIG}

16:10:01 | INFO    | stage2 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
16:10:01 | INFO    | stage2 | Math metrics: 480 of 500 trajectories to do
16:10:14 | INFO    | stage2 | Math metrics done.
16:10:14 | INFO    | stage2 | Sampling metrics: 467 of 485 failed trajectories
16:10:16 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 16:10:19.317205: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 16:10:19.391762: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 16:10:29 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 16:10:32 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 16:10:32 [model.py:1678] Using max model len 8192
INFO 07-21 16:10:33 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 16:10:33 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00, 10.22it/s]
INFO 07-21 16:10:34 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 16:10:35 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=28635) INFO 07-21 16:10:53 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=28635) INFO 07-21 16:10:53 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:33013 backend=nccl
(EngineCore pid=28635) INFO 07-21 16:10:53 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=28635) INFO 07-21 16:10:54 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=28635) INFO 07-21 16:10:55 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=28635) INFO 07-21 16:10:55 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=28635) INFO 07-21 16:10:55 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=28635) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=28635) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=28635) INFO 07-21 16:11:02 [default_loader.py:384] Loading weights took 5.89 seconds
(EngineCore pid=28635) INFO 07-21 16:11:07 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.225907 seconds
(EngineCore pid=28635) INFO 07-21 16:11:15 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=28635) INFO 07-21 16:11:15 [backends.py:1111] Dynamo bytecode transform time: 7.92 s
(EngineCore pid=28635) INFO 07-21 16:11:20 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.052 s
(EngineCore pid=28635) INFO 07-21 16:11:20 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=28635) INFO 07-21 16:11:20 [monitor.py:48] torch.compile took 12.16 s in total
(EngineCore pid=28635) INFO 07-21 16:11:23 [monitor.py:76] Initial profiling/warmup run took 3.03 s
(EngineCore pid=28635) INFO 07-21 16:11:24 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=28635) INFO 07-21 16:11:24 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=28635) INFO 07-21 16:11:26 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=28635) INFO 07-21 16:11:27 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=28635) INFO 07-21 16:11:27 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=28635) INFO 07-21 16:11:27 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=28635) INFO 07-21 16:11:27 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.13it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.72it/s]
(EngineCore pid=28635) INFO 07-21 16:11:39 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=28635) INFO 07-21 16:11:39 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=28635) INFO 07-21 16:11:39 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.16 seconds
(EngineCore pid=28635) INFO 07-21 16:11:41 [vllm.py:790] Asynchronous scheduling is enabled.
16:11:58 | INFO    | stage2 | 16/467  (0.91 q/s, ETA 8 min)
16:12:15 | INFO    | stage2 | 32/467  (0.95 q/s, ETA 8 min)
16:12:36 | INFO    | stage2 | 48/467  (0.88 q/s, ETA 8 min)
16:12:52 | INFO    | stage2 | 64/467  (0.90 q/s, ETA 7 min)
16:13:09 | INFO    | stage2 | 80/467  (0.91 q/s, ETA 7 min)
16:13:23 | INFO    | stage2 | 96/467  (0.94 q/s, ETA 7 min)
16:13:38 | INFO    | stage2 | 112/467  (0.96 q/s, ETA 6 min)
16:13:59 | INFO    | stage2 | 128/467  (0.93 q/s, ETA 6 min)
16:14:20 | INFO    | stage2 | 144/467  (0.90 q/s, ETA 6 min)
16:14:39 | INFO    | stage2 | 160/467  (0.90 q/s, ETA 6 min)
16:14:59 | INFO    | stage2 | 176/467  (0.89 q/s, ETA 5 min)
16:15:15 | INFO    | stage2 | 192/467  (0.90 q/s, ETA 5 min)
16:15:38 | INFO    | stage2 | 208/467  (0.88 q/s, ETA 5 min)
16:15:56 | INFO    | stage2 | 224/467  (0.88 q/s, ETA 5 min)
16:16:16 | INFO    | stage2 | 240/467  (0.87 q/s, ETA 4 min)
16:16:35 | INFO    | stage2 | 256/467  (0.87 q/s, ETA 4 min)
16:16:54 | INFO    | stage2 | 272/467  (0.87 q/s, ETA 4 min)
16:17:13 | INFO    | stage2 | 288/467  (0.87 q/s, ETA 3 min)
16:17:31 | INFO    | stage2 | 304/467  (0.87 q/s, ETA 3 min)
16:17:50 | INFO    | stage2 | 320/467  (0.87 q/s, ETA 3 min)
16:18:02 | INFO    | stage2 | 336/467  (0.88 q/s, ETA 2 min)
16:18:22 | INFO    | stage2 | 352/467  (0.88 q/s, ETA 2 min)
16:18:39 | INFO    | stage2 | 368/467  (0.88 q/s, ETA 2 min)
16:19:03 | INFO    | stage2 | 384/467  (0.87 q/s, ETA 2 min)
16:19:25 | INFO    | stage2 | 400/467  (0.86 q/s, ETA 1 min)
16:19:43 | INFO    | stage2 | 416/467  (0.86 q/s, ETA 1 min)
16:20:01 | INFO    | stage2 | 432/467  (0.86 q/s, ETA 1 min)
16:20:20 | INFO    | stage2 | 448/467  (0.86 q/s, ETA 0 min)
16:20:45 | INFO    | stage2 | 464/467  (0.85 q/s, ETA 0 min)
16:20:50 | INFO    | stage2 | 467/467  (0.85 q/s, ETA 0 min)
16:20:50 | INFO    | stage2 | Sampling-based uncertainty done.
(EngineCore pid=28635) INFO 07-21 16:20:50 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=28635) INFO 07-21 16:20:50 [core.py:1233] Shutdown complete
[rank0]:[W721 16:20:50.396053082 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 3: Error Annotation (72B Judge)

In [33]:
!python scripts/run_annotate.py --config {CONFIG}

16:20:54 | INFO    | stage3 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
16:20:54 | INFO    | stage3 | To annotate: 467 of 485 failed trajectories
16:20:56 | INFO    | stage3 | GPU VRAM: 85.094825984 GB | judge: Qwen/Qwen2.5-72B-Instruct-AWQ (85 GB -> 72B judge)
2026-07-21 16:20:59.191512: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 16:20:59.264007: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 16:21:09 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-72B-Instruct-AWQ'}
INFO 07-21 16:21:10 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 16:21:10 [model.py:1678] Using max model len 8192
INFO 07-21 16:21:11 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 16:21:11 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 11/11 [00:00<00:00, 13.75it/s]
INFO 07-21 16:21:12 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 16:21:13 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=31663) INFO 07-21 16:21:31 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-72B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-72B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-72B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=31663) INFO 07-21 16:21:31 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:33389 backend=nccl
(EngineCore pid=31663) INFO 07-21 16:21:31 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=31663) INFO 07-21 16:21:32 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-72B-Instruct-AWQ...
(EngineCore pid=31663) INFO 07-21 16:21:33 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=31663) INFO 07-21 16:21:33 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=31663) INFO 07-21 16:21:33 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=31663) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=31663) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 11/11 [00:13<00:00,  1.26s/it]
(EngineCore pid=31663) INFO 07-21 16:21:49 [default_loader.py:384] Loading weights took 14.06 seconds
(EngineCore pid=31663) INFO 07-21 16:21:59 [gpu_model_runner.py:4820] Model loading took 38.77 GiB memory and 25.060350 seconds
(EngineCore pid=31663) INFO 07-21 16:22:09 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/53d20b985e/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=31663) INFO 07-21 16:22:09 [backends.py:1111] Dynamo bytecode transform time: 9.41 s
(EngineCore pid=31663) INFO 07-21 16:22:14 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.720 s
(EngineCore pid=31663) INFO 07-21 16:22:14 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/bfecb0b875229f090c0ca3328404a3eb2f6add3eda8c9a9377d884ffa1bb6e0d/rank_0_0/model
(EngineCore pid=31663) INFO 07-21 16:22:14 [monitor.py:48] torch.compile took 14.70 s in total
(EngineCore pid=31663) INFO 07-21 16:22:21 [monitor.py:76] Initial profiling/warmup run took 6.42 s
(EngineCore pid=31663) INFO 07-21 16:22:31 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=31663) INFO 07-21 16:22:31 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=31663) INFO 07-21 16:22:35 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.31 GiB total
(EngineCore pid=31663) INFO 07-21 16:22:36 [gpu_worker.py:436] Available KV cache memory: 32.24 GiB
(EngineCore pid=31663) INFO 07-21 16:22:36 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9200 to 0.9365 to maintain the same effective KV cache size.
(EngineCore pid=31663) INFO 07-21 16:22:36 [kv_cache_utils.py:1319] GPU KV cache size: 105,648 tokens
(EngineCore pid=31663) INFO 07-21 16:22:36 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 12.90x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:12<00:00,  4.01it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:05<00:00,  5.87it/s]
(EngineCore pid=31663) INFO 07-21 16:22:56 [gpu_model_runner.py:6046] Graph capturing finished in 20 secs, took 1.17 GiB
(EngineCore pid=31663) INFO 07-21 16:22:56 [gpu_worker.py:597] CUDA graph pool memory: 1.17 GiB (actual), 1.31 GiB (estimated), difference: 0.14 GiB (12.2%).
(EngineCore pid=31663) INFO 07-21 16:22:56 [core.py:283] init engine (profile, create kv cache, warmup model) took 56.82 seconds
(EngineCore pid=31663) INFO 07-21 16:22:58 [vllm.py:790] Asynchronous scheduling is enabled.
16:23:07 | INFO    | stage3 | 16/467  (1.72 traj/s, ETA 4 min)
16:23:15 | INFO    | stage3 | 32/467  (1.82 traj/s, ETA 4 min)
16:23:25 | INFO    | stage3 | 48/467  (1.78 traj/s, ETA 4 min)
16:23:33 | INFO    | stage3 | 64/467  (1.79 traj/s, ETA 4 min)
16:23:42 | INFO    | stage3 | 80/467  (1.80 traj/s, ETA 4 min)
16:23:50 | INFO    | stage3 | 96/467  (1.84 traj/s, ETA 3 min)
16:23:58 | INFO    | stage3 | 112/467  (1.85 traj/s, ETA 3 min)
16:24:08 | INFO    | stage3 | 128/467  (1.83 traj/s, ETA 3 min)
16:24:17 | INFO    | stage3 | 144/467  (1.81 traj/s, ETA 3 min)
16:24:26 | INFO    | stage3 | 160/467  (1.80 traj/s, ETA 3 min)
16:24:36 | INFO    | stage3 | 176/467  (1.79 traj/s, ETA 3 min)
16:24:45 | INFO    | stage3 | 192/467  (1.79 traj/s, ETA 3 min)
16:24:55 | INFO    | stage3 | 208/467  (1.78 traj/s, ETA 2 min)
16:25:04 | INFO    | stage3 | 224/467  (1.77 traj/s, ETA 2 min)
16:25:13 | INFO    | stage3 | 240/467  (1.77 traj/s, ETA 2 min)
16:25:22 | INFO    | stage3 | 256/467  (1.77 traj/s, ETA 2 min)
16:25:31 | INFO    | stage3 | 272/467  (1.77 traj/s, ETA 2 min)
16:25:40 | INFO    | stage3 | 288/467  (1.77 traj/s, ETA 2 min)
16:25:49 | INFO    | stage3 | 304/467  (1.77 traj/s, ETA 2 min)
16:25:59 | INFO    | stage3 | 320/467  (1.77 traj/s, ETA 1 min)
16:26:06 | INFO    | stage3 | 336/467  (1.78 traj/s, ETA 1 min)
16:26:15 | INFO    | stage3 | 352/467  (1.78 traj/s, ETA 1 min)
16:26:24 | INFO    | stage3 | 368/467  (1.78 traj/s, ETA 1 min)
16:26:35 | INFO    | stage3 | 384/467  (1.77 traj/s, ETA 1 min)
16:26:45 | INFO    | stage3 | 400/467  (1.76 traj/s, ETA 1 min)
16:26:53 | INFO    | stage3 | 416/467  (1.76 traj/s, ETA 0 min)
16:27:03 | INFO    | stage3 | 432/467  (1.76 traj/s, ETA 0 min)
16:27:12 | INFO    | stage3 | 448/467  (1.76 traj/s, ETA 0 min)
16:27:23 | INFO    | stage3 | 464/467  (1.75 traj/s, ETA 0 min)
16:27:26 | INFO    | stage3 | 467/467  (1.74 traj/s, ETA 0 min)
16:27:27 | INFO    | stage3 | Annotated: 485
16:27:27 | INFO    | stage3 | error types: Counter({'wrong_search_query': 194, 'premature_or_wrong_answer': 132, 'wrong_fact_extraction': 122, 'faulty_reasoning': 36, 'formatting_tool_error': 1})
16:27:27 | INFO    | stage3 | sources    : Counter({'judge': 485})
16:27:27 | INFO    | stage3 | Next: run `python scripts/label_human.py` to hand-label 50 and check agreement.
(EngineCore pid=31663) INFO 07-21 16:27:27 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=31663) INFO 07-21 16:27:27 [core.py:1233] Shutdown complete
[rank0]:[W721 16:27:27.543605086 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 4: Localization Scoring

In [34]:
!python scripts/run_localize.py --config {CONFIG}

16:27:31 | INFO    | stage4 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
16:27:33 | INFO    | stage4 | records: 4850 (485 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.223           0.534  0.429          0.229              0.606     0.447     0.491  485
max_token_prob_max            0.212           0.548  0.458          0.252              0.633     0.507     0.596  485
token_entropy_max             0.210           0.551  0.453          0.260              0.654     0.503     0.584  485
max_token_prob_mean           0.184           0.569  0.435          0.208              0.639     0.491     0.557  485
perplexity                    0.171           0.573  0.429          0.202              0.645     0.493     0.557  485
verbalized_confidence         0.167           0.536  0.440          0.210              0.604     0.520     0.588  485
token_entropy_mean            0.163           0.553  0.421          0.192              0.639     0.489     0.557  485
token_entropy_mean_k20        0.163           0.553  0.421          0.192              0.639     0.489     0.557  485
token_entropy_mean_k50        0.163           0.553  0.421          0.192              0.639     0.489     0.557  485
token_entropy_mean_k5         0.161           0.553  0.422          0.194              0.629     0.495     0.555  485
16:27:34 | INFO    | stage4 | Random top-1 baseline: 0.304 | best metric: self_consistency (0.223)
16:27:34 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-fever/outputs/tables/localization_summary.csv

### Stage 5: Repair (126 Strategies)

In [35]:
!python scripts/run_repair.py --config {CONFIG}

16:27:34 | INFO    | stage5 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
16:27:34 | INFO    | stage5 | Dataset: fever (env: FEVEREnv)
16:27:34 | INFO    | stage5 | 485 failed x 126 strategies x 3 seeds = 183330 result rows (actual GPU runs are far fewer: dedup)
16:27:36 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 16:27:39.645485: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 16:27:39.719521: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 16:27:50 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 16:27:51 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 16:27:51 [model.py:1678] Using max model len 8192
INFO 07-21 16:27:53 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 16:27:53 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00, 10.13it/s]
INFO 07-21 16:27:53 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 16:27:55 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=33703) INFO 07-21 16:28:13 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=33703) INFO 07-21 16:28:13 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:48793 backend=nccl
(EngineCore pid=33703) INFO 07-21 16:28:13 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=33703) INFO 07-21 16:28:14 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=33703) INFO 07-21 16:28:14 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=33703) INFO 07-21 16:28:15 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=33703) INFO 07-21 16:28:15 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=33703) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=33703) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.17s/it]
(EngineCore pid=33703) INFO 07-21 16:28:22 [default_loader.py:384] Loading weights took 5.92 seconds
(EngineCore pid=33703) INFO 07-21 16:28:27 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.424964 seconds
(EngineCore pid=33703) INFO 07-21 16:28:36 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=33703) INFO 07-21 16:28:36 [backends.py:1111] Dynamo bytecode transform time: 8.07 s
(EngineCore pid=33703) INFO 07-21 16:28:40 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.030 s
(EngineCore pid=33703) INFO 07-21 16:28:40 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=33703) INFO 07-21 16:28:40 [monitor.py:48] torch.compile took 12.29 s in total
(EngineCore pid=33703) INFO 07-21 16:28:43 [monitor.py:76] Initial profiling/warmup run took 3.01 s
(EngineCore pid=33703) INFO 07-21 16:28:44 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=33703) INFO 07-21 16:28:44 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=33703) INFO 07-21 16:28:47 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=33703) INFO 07-21 16:28:47 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=33703) INFO 07-21 16:28:47 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=33703) INFO 07-21 16:28:47 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=33703) INFO 07-21 16:28:47 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  6.94it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.44it/s]
(EngineCore pid=33703) INFO 07-21 16:29:00 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=33703) INFO 07-21 16:29:00 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=33703) INFO 07-21 16:29:00 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.73 seconds
(EngineCore pid=33703) INFO 07-21 16:29:01 [vllm.py:790] Asynchronous scheduling is enabled.
16:29:01 | INFO    | stage5 | --- seed 0 ---
16:33:56 | INFO    | stage5 | seed 0: 64/485 questions | 561 GPU repairs so far | 4.9 min elapsed
16:39:07 | INFO    | stage5 | seed 0: 128/485 questions | 1126 GPU repairs so far | 10.1 min elapsed
16:44:40 | INFO    | stage5 | seed 0: 192/485 questions | 1744 GPU repairs so far | 15.6 min elapsed
16:50:13 | INFO    | stage5 | seed 0: 256/485 questions | 2378 GPU repairs so far | 21.2 min elapsed
16:55:32 | INFO    | stage5 | seed 0: 320/485 questions | 2981 GPU repairs so far | 26.5 min elapsed
17:00:43 | INFO    | stage5 | seed 0: 384/485 questions | 3570 GPU repairs so far | 31.7 min elapsed
17:06:05 | INFO    | stage5 | seed 0: 448/485 questions | 4165 GPU repairs so far | 37.1 min elapsed
17:09:30 | INFO    | stage5 | seed 0: 485/485 questions | 4541 GPU repairs so far | 40.5 min elapsed
17:09:30 | INFO    | stage5 | --- seed 1 ---
17:14:32 | INFO    | stage5 | seed 1: 64/485 questions | 5107 GPU repairs so far | 45.5 min elapsed
17:19:40 | INFO    | stage5 | seed 1: 128/485 questions | 5670 GPU repairs so far | 50.6 min elapsed
17:25:16 | INFO    | stage5 | seed 1: 192/485 questions | 6286 GPU repairs so far | 56.2 min elapsed
17:30:51 | INFO    | stage5 | seed 1: 256/485 questions | 6916 GPU repairs so far | 61.8 min elapsed
17:36:08 | INFO    | stage5 | seed 1: 320/485 questions | 7520 GPU repairs so far | 67.1 min elapsed
17:41:25 | INFO    | stage5 | seed 1: 384/485 questions | 8105 GPU repairs so far | 72.4 min elapsed
17:46:43 | INFO    | stage5 | seed 1: 448/485 questions | 8695 GPU repairs so far | 77.7 min elapsed
17:50:16 | INFO    | stage5 | seed 1: 485/485 questions | 9072 GPU repairs so far | 81.2 min elapsed
17:50:16 | INFO    | stage5 | --- seed 2 ---
17:55:15 | INFO    | stage5 | seed 2: 64/485 questions | 9635 GPU repairs so far | 86.2 min elapsed
18:00:24 | INFO    | stage5 | seed 2: 128/485 questions | 10200 GPU repairs so far | 91.4 min elapsed
18:05:59 | INFO    | stage5 | seed 2: 192/485 questions | 10817 GPU repairs so far | 97.0 min elapsed
18:11:34 | INFO    | stage5 | seed 2: 256/485 questions | 11443 GPU repairs so far | 102.5 min elapsed
18:16:55 | INFO    | stage5 | seed 2: 320/485 questions | 12048 GPU repairs so far | 107.9 min elapsed
18:22:10 | INFO    | stage5 | seed 2: 384/485 questions | 12636 GPU repairs so far | 113.1 min elapsed
18:27:33 | INFO    | stage5 | seed 2: 448/485 questions | 13230 GPU repairs so far | 118.5 min elapsed
18:30:58 | INFO    | stage5 | seed 2: 485/485 questions | 13604 GPU repairs so far | 121.9 min elapsed
18:30:58 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 13604 (vs 183330 result rows — dedup saved 93%)
18:30:58 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-fever/outputs/repairs/results.jsonl
(EngineCore pid=33703) INFO 07-21 18:30:58 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=33703) INFO 07-21 18:30:58 [core.py:1233] Shutdown complete
[rank0]:[W721 18:30:58.777986699 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 6: Evaluation

In [36]:
!python scripts/run_eval.py --config {CONFIG}

18:31:03 | INFO    | stage6 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
18:31:07 | INFO    | stage6 | rows: 184785 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%    95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step      1.2  0.7-1.7%         156            2.68             32.8
                                                       full_restart      2.8  2.0-3.7%         220            3.91             68.0
                                               oracle_targeted__bt2      3.0  2.2-3.9%         223            3.92             68.0
                                     oracle_targeted__bt2__informed      3.0  2.2-3.9%         225            3.98             68.0
                                          oracle_targeted__informed      2.7  1.9-3.6%         229            4.03            100.0
                                    unc__max_token_prob_max__argmax      1.9  1.2-2.5%         149            2.54             21.2
                               unc__max_token_prob_max__argmax__bt2      2.7  1.9-3.6%         186            3.24             33.6
                     unc__max_token_prob_max__argmax__bt2__informed      2.6  1.8-3.4%         184            3.24             33.6
                          unc__max_token_prob_max__argmax__informed      2.5  1.7-3.3%         148            2.56             21.2
                          unc__max_token_prob_max__cascade_gradient      1.2  0.6-1.8%         165            2.87             32.2
                     unc__max_token_prob_max__cascade_gradient__bt2      2.8  2.0-3.7%         200            3.49             42.5
           unc__max_token_prob_max__cascade_gradient__bt2__informed      2.3  1.6-3.2%         202            3.58             42.5
                unc__max_token_prob_max__cascade_gradient__informed      2.1  1.4-2.8%         168            2.95             32.2
                          unc__max_token_prob_max__cascade_upstream      2.7  1.9-3.6%         186            3.24             33.6
                     unc__max_token_prob_max__cascade_upstream__bt2      3.2  2.3-4.0%         211            3.72             48.7
           unc__max_token_prob_max__cascade_upstream__bt2__informed      3.1  2.3-4.0%         211            3.76             48.7
                unc__max_token_prob_max__cascade_upstream__informed      2.6  1.8-3.4%         184            3.24             33.6
                          unc__max_token_prob_max__cascade_weighted      2.4  1.7-3.2%         201            3.54             30.3
                     unc__max_token_prob_max__cascade_weighted__bt2      2.8  1.9-3.6%         218            3.83             60.2
           unc__max_token_prob_max__cascade_weighted__bt2__informed      2.8  1.9-3.6%         220            3.90             60.2
                unc__max_token_prob_max__cascade_weighted__informed      2.8  1.9-3.6%         200            3.56             30.3
                  unc__max_token_prob_max__earliest_above_threshold      2.2  1.5-3.0%         178            3.09             25.2
             unc__max_token_prob_max__earliest_above_threshold__bt2      2.8  2.0-3.7%         206            3.62             45.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed      2.7  1.9-3.5%         208            3.69             45.8
        unc__max_token_prob_max__earliest_above_threshold__informed      2.2  1.4-3.0%         176            3.10             25.2
                                      unc__max_token_prob_max__topk      2.6  1.8-3.4%         196            3.44             29.7
                                 unc__max_token_prob_max__topk__bt2      3.2  2.3-4.0%         216            3.79             56.3
                       unc__max_token_prob_max__topk__bt2__informed      2.9  2.1-3.8%         218            3.86             56.3
                            unc__max_token_prob_max__topk__informed      2.4  1.7-3.2%         195            3.46             29.7
                                            unc__perplexity__argmax      1.9  1.2-2.7%         153            2.60             17.1
                                       unc__perplexity__argmax__bt2      2.8  1.9-3.6%         188            3.25             35.7
                             unc__perplexity__argmax__bt2__informed      3.0  2.2-3.9%         187            3.29             35.7
                                  unc__perplexity__argmax__informed      1.7  1.1-2.4%         152            2.64             17.1
                                  unc__perplexity__cascade_gradient      1.4  0.9-2.1%         165            2.86             31.8
                             unc__perplexity__cascade_gradient__bt2      2.7  1.9-3.5%         199            3.46             43.1
                   unc__perplexity__cascade_gradient__bt2__informed      3.1  2.3-4.0%         199            3.52             43.1
                        unc__perplexity__cascade_gradient__informed      1.9  1.2-2.5%         167            2.92             31.8
                                  unc__perplexity__cascade_upstream      2.8  1.9-3.6%         188            3.25             35.7
                             unc__perplexity__cascade_upstream__bt2      3.1  2.3-4.0%         209            3.69             49.7
                   unc__perplexity__cascade_upstream__bt2__informed      3.0  2.1-3.9%         210            3.71             49.7
                        unc__perplexity__cascade_upstream__informed      3.0  2.2-3.9%         187            3.29             35.7
                                  unc__perplexity__cascade_weighted      2.1  1.4-2.8%         199            3.48             25.6
                             unc__perplexity__cascade_weighted__bt2      3.2  2.3-4.1%         217            3.81             58.6
                   unc__perplexity__cascade_weighted__bt2__informed      3.0  2.2-3.9%         218            3.86             58.6
                        unc__perplexity__cascade_weighted__informed      2.4  1.7-3.2%         197            3.52             25.6
                          unc__perplexity__earliest_above_threshold      2.0  1.3-2.8%         178            3.08             20.2
                     unc__perplexity__earliest_above_threshold__bt2      3.2  2.3-4.1%         204            3.58             46.4
           unc__perplexity__earliest_above_threshold__bt2__informed      2.8  1.9-3.6%         206            3.64             46.4
                unc__perplexity__earliest_above_threshold__informed      2.0  1.3-2.8%         177            3.13             20.2
                                              unc__perplexity__topk      2.1  1.4-2.9%         194            3.40             26.2
                                         unc__perplexity__topk__bt2      3.3  2.4-4.3%         214            3.75             55.7
                               unc__perplexity__topk__bt2__informed      3.0  2.2-3.9%         215            3.81             55.7
                                    unc__perplexity__topk__informed      2.8  1.9-3.6%         192            3.42             26.2
                                      unc__self_consistency__argmax      1.4  0.8-2.0%         158            2.69             22.3
                                 unc__self_consistency__argmax__bt2      2.5  1.7-3.3%         193            3.37             34.6
                       unc__self_consistency__argmax__bt2__informed      2.9  2.1-3.7%         192            3.39             34.6
                            unc__self_consistency__argmax__informed      1.9  1.2-2.6%         156            2.70             22.3
                            unc__self_consistency__cascade_gradient      1.6  1.0-2.3%         184            3.26             31.6
                       unc__self_consistency__cascade_gradient__bt2      2.7  1.9-3.5%         212            3.74             53.0
             unc__self_consistency__cascade_gradient__bt2__informed      2.8  2.0-3.6%         213            3.76             53.0
                  unc__self_consistency__cascade_gradient__informed      1.8  1.2-2.5%         187            3.29             31.6
                            unc__self_consistency__cascade_upstream      2.5  1.7-3.3%         193            3.37             34.6
                       unc__self_consistency__cascade_upstream__bt2      3.0  2.2-3.9%         214            3.75             52.8
             unc__self_consistency__cascade_upstream__bt2__informed      2.8  1.9-3.6%         214            3.76             52.8
                  unc__self_consistency__cascade_upstream__informed      2.9  2.1-3.7%         192            3.39             34.6
                            unc__self_consistency__cascade_weighted      2.3  1.6-3.2%         195            3.44             19.4
                       unc__self_consistency__cascade_weighted__bt2      3.0  2.1-3.9%         217            3.81             57.5
             unc__self_consistency__cascade_weighted__bt2__informed      2.8  2.0-3.6%         219            3.89             57.5
                  unc__self_consistency__cascade_weighted__informed      3.0  2.1-3.9%         194            3.45             19.4
                    unc__self_consistency__earliest_above_threshold      1.6  1.0-2.3%         179            3.11             22.9
               unc__self_consistency__earliest_above_threshold__bt2      2.8  2.0-3.7%         207            3.65             44.1
     unc__self_consistency__earliest_above_threshold__bt2__informed      3.0  2.1-3.9%         209            3.70             44.1
          unc__self_consistency__earliest_above_threshold__informed      1.9  1.2-2.7%         178            3.12             22.9
                                        unc__self_consistency__topk      2.3  1.5-3.1%         191            3.36             19.6
                                   unc__self_consistency__topk__bt2      3.1  2.2-4.0%         214            3.77             53.8
                         unc__self_consistency__topk__bt2__informed      2.8  2.0-3.6%         216            3.84             53.8
                              unc__self_consistency__topk__informed      2.5  1.8-3.4%         189            3.35             19.6
                                     unc__token_entropy_max__argmax      1.4  0.8-2.1%         148            2.52             21.0
                                unc__token_entropy_max__argmax__bt2      2.5  1.8-3.4%         186            3.24             34.4
                      unc__token_entropy_max__argmax__bt2__informed      2.5  1.7-3.3%         186            3.30             34.4
                           unc__token_entropy_max__argmax__informed      2.3  1.5-3.0%         148            2.58             21.0
                           unc__token_entropy_max__cascade_gradient      1.4  0.8-2.0%         162            2.80             32.4
                      unc__token_entropy_max__cascade_gradient__bt2      2.5  1.7-3.3%         197            3.48             40.4
            unc__token_entropy_max__cascade_gradient__bt2__informed      2.3  1.6-3.2%         197            3.53             40.4
                 unc__token_entropy_max__cascade_gradient__informed      2.1  1.4-2.8%         164            2.89             32.4
                           unc__token_entropy_max__cascade_upstream      2.5  1.8-3.4%         186            3.24             34.4
                      unc__token_entropy_max__cascade_upstream__bt2      3.4  2.5-4.3%         211            3.74             48.4
            unc__token_entropy_max__cascade_upstream__bt2__informed      3.0  2.1-3.9%         211            3.75             48.4
                 unc__token_entropy_max__cascade_upstream__informed      2.5  1.7-3.3%         186            3.30             34.4
                           unc__token_entropy_max__cascade_weighted      2.3  1.5-3.0%         201            3.55             29.1
                      unc__token_entropy_max__cascade_weighted__bt2      3.1  2.3-4.0%         216            3.80             60.0
            unc__token_entropy_max__cascade_weighted__bt2__informed      2.9  2.1-3.8%         219            3.88             60.0
                 unc__token_entropy_max__cascade_weighted__informed      3.0  2.2-3.9%         200            3.57             29.1
                   unc__token_entropy_max__earliest_above_threshold      2.0  1.3-2.8%         178            3.06             26.0
              unc__token_entropy_max__earliest_above_threshold__bt2      2.8  2.0-3.7%         206            3.64             45.8
    unc__token_entropy_max__earliest_above_threshold__bt2__informed      3.0  2.1-3.9%         207            3.67             45.8
         unc__token_entropy_max__earliest_above_threshold__informed      1.9  1.2-2.6%         177            3.13             26.0
                                       unc__token_entropy_max__topk      2.0  1.3-2.8%         197            3.47             28.7
                                  unc__token_entropy_max__topk__bt2      3.3  2.4-4.3%         218            3.85             56.3
                        unc__token_entropy_max__topk__bt2__informed      2.9  2.1-3.8%         219            3.88             56.3
                             unc__token_entropy_max__topk__informed      2.5  1.8-3.4%         196            3.47             28.7
                                 unc__verbalized_confidence__argmax      1.9  1.2-2.7%         142            2.40             16.7
                            unc__verbalized_confidence__argmax__bt2      2.8  1.9-3.6%         179            3.11             28.9
                  unc__verbalized_confidence__argmax__bt2__informed      2.4  1.7-3.2%         178            3.14             28.9
                       unc__verbalized_confidence__argmax__informed      2.4  1.7-3.2%         139            2.40             16.7
                       unc__verbalized_confidence__cascade_gradient      1.1  0.6-1.7%         148            2.52             31.8
                  unc__verbalized_confidence__cascade_gradient__bt2      2.7  1.9-3.5%         186            3.23             32.6
        unc__verbalized_confidence__cascade_gradient__bt2__informed      2.4  1.7-3.2%         187            3.32             32.6
             unc__verbalized_confidence__cascade_gradient__informed      1.7  1.1-2.4%         150            2.61             31.8
                       unc__verbalized_confidence__cascade_upstream      2.8  1.9-3.6%         179            3.11             28.9
                  unc__verbalized_confidence__cascade_upstream__bt2      3.4  2.5-4.3%         205            3.65             45.6
        unc__verbalized_confidence__cascade_upstream__bt2__informed      2.8  1.9-3.6%         207            3.68             45.6
             unc__verbalized_confidence__cascade_upstream__informed      2.4  1.7-3.2%         178            3.14             28.9
                       unc__verbalized_confidence__cascade_weighted      2.4  1.7-3.2%         170            2.94             23.1
                  unc__verbalized_confidence__cascade_weighted__bt2      2.9  2.1-3.8%         200            3.48             41.4
        unc__verbalized_confidence__cascade_weighted__bt2__informed      2.6  1.9-3.4%         201            3.58             41.4
             unc__verbalized_confidence__cascade_weighted__informed      2.7  1.9-3.5%         169            2.96             23.1
               unc__verbalized_confidence__earliest_above_threshold      2.1  1.4-2.9%         165            2.87             21.0
          unc__verbalized_confidence__earliest_above_threshold__bt2      2.8  2.0-3.7%         196            3.45             38.6
unc__verbalized_confidence__earliest_above_threshold__bt2__informed      2.8  1.9-3.6%         198            3.52             38.6
     unc__verbalized_confidence__earliest_above_threshold__informed      2.6  1.9-3.4%         164            2.87             21.0
                                   unc__verbalized_confidence__topk      2.5  1.8-3.4%         186            3.26             29.9
                              unc__verbalized_confidence__topk__bt2      3.1  2.3-4.0%         208            3.68             49.3
                    unc__verbalized_confidence__topk__bt2__informed      2.7  1.9-3.5%         212            3.76             49.3
                         unc__verbalized_confidence__topk__informed      2.6  1.8-3.4%         186            3.29             29.9
                                           uncertainty_ensemble_any      9.3 7.8-10.8%       10608          185.66             93.6
                                                    oracle_targeted      2.3  1.6-3.2%         222            3.89            100.0
Traceback (most recent call last):
  File "/content/agent-repair/scripts/run_eval.py", line 461, in <module>
    main()
  File "/content/agent-repair/scripts/run_eval.py", line 91, in main
    u = df[df.strategy.isin(bt0_strats)] if bt0_strats else df[df.strategy.isin(unc_strats)]
                                            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'bt0_strats' where it is not associated with a value

---
## Results

In [37]:
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())
else:
    print('Summary not yet generated. Run Stage 6 first.')

Summary not yet generated. Run Stage 6 first.

In [38]:
import pandas as pd

results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)
else:
    print('Results table not yet generated. Run Stage 6 first.')

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,1.2,0.7-1.7%,156,2.68,32.8
1,full_restart,2.8,2.0-3.7%,220,3.91,68.0
2,oracle_targeted__bt2,3.0,2.2-3.9%,223,3.92,68.0
3,oracle_targeted__bt2__informed,3.0,2.2-3.9%,225,3.98,68.0
4,oracle_targeted__informed,2.7,1.9-3.6%,229,4.03,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,3.1,2.3-4.0%,208,3.68,49.3
123,unc__verbalized_confidence__topk__bt2__informed,2.7,1.9-3.5%,212,3.76,49.3
124,unc__verbalized_confidence__topk__informed,2.6,1.8-3.4%,186,3.29,29.9
125,uncertainty_ensemble_any,9.3,7.8-10.8%,10608,185.66,93.6
126,oracle_targeted,2.3,1.6-3.2%,222,3.89,100.0

In [39]:
import glob
from IPython.display import display, Image

fig_dir = cfg.path('figures')
figs = sorted(glob.glob(os.path.join(fig_dir, '*.png')))
if figs:
    for f in figs:
        print(f'\n--- {os.path.basename(f)} ---')
        display(Image(filename=f, width=800))
else:
    print('No figures yet. Run Stage 6 first.')

No figures yet. Run Stage 6 first.

---
## Re-run Stages 4–6 with Cascade-Aware Strategies

**Use this after you already have stages 1–3 completed** (trajectories, uncertainty, annotations).
This pulls the latest code (with cascade rules), clears only localization/repair/eval outputs,
and re-runs stages 4→5→6 in one cell. ~3-4 hours on A100-80GB for 500 questions.

In [40]:
import os, shutil

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_fever.yaml'

# 1. Pull latest code with cascade-aware strategies
os.chdir(REPO_DIR)
!git pull

# 2. Clear ONLY stages 4-6 outputs (keep trajectories, uncertainty, annotations)
drive_base = '/content/drive/MyDrive/agent-repair-fever'
for base in [REPO_DIR, drive_base]:
    for d in ['outputs/localization', 'outputs/repairs', 'outputs/tables', 'outputs/figures']:
        p = os.path.join(base, d)
        if os.path.exists(p):
            shutil.rmtree(p)
            print(f'Cleared {p}')

# 3. Clear checkpoint files for stages 4-6 (these live in outputs/logs/)
for base in [REPO_DIR, drive_base]:
    for ckpt in ['outputs/logs/stage4_localize.jsonl',
                 'outputs/logs/stage5_repair.jsonl',
                 'outputs/logs/stage6_eval.jsonl']:
        p = os.path.join(base, ckpt)
        if os.path.exists(p):
            os.remove(p)
            print(f'Removed checkpoint: {p}')

print('\nStages 1-3 data preserved. Ready to re-run 4→5→6.')

Already up to date.
Cleared /content/drive/MyDrive/agent-repair-fever/outputs/localization
Cleared /content/drive/MyDrive/agent-repair-fever/outputs/repairs
Cleared /content/drive/MyDrive/agent-repair-fever/outputs/tables
Cleared /content/drive/MyDrive/agent-repair-fever/outputs/figures
Removed checkpoint: /content/drive/MyDrive/agent-repair-fever/outputs/logs/stage5_repair.jsonl

Stages 1-3 data preserved. Ready to re-run 4→5→6.

In [41]:
# Run stages 4 → 5 → 6 sequentially (run this and go to sleep)
import time

for stage in ['run_localize', 'run_repair', 'run_eval']:
    t0 = time.time()
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG}
    elapsed = (time.time() - t0) / 60
    print(f'  ✓ {stage} done in {elapsed:.1f} min\n')

print('\n' + '='*60)
print('  ALL DONE — check results below')
print('='*60)

============================================================
  run_localize
============================================================
18:31:27 | INFO    | stage4 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
18:31:29 | INFO    | stage4 | records: 4850 (485 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.223           0.534  0.429          0.229              0.606     0.447     0.491  485
max_token_prob_max            0.212           0.548  0.458          0.252              0.633     0.507     0.596  485
token_entropy_max             0.210           0.551  0.453          0.260              0.654     0.503     0.584  485
max_token_prob_mean           0.184           0.569  0.435          0.208              0.639     0.491     0.557  485
perplexity                    0.171           0.573  0.429          0.202              0.645     0.493     0.557  485
verbalized_confidence         0.167           0.536  0.440          0.210              0.604     0.520     0.588  485
token_entropy_mean            0.163           0.553  0.421          0.192              0.639     0.489     0.557  485
token_entropy_mean_k20        0.163           0.553  0.421          0.192              0.639     0.489     0.557  485
token_entropy_mean_k50        0.163           0.553  0.421          0.192              0.639     0.489     0.557  485
token_entropy_mean_k5         0.161           0.553  0.422          0.194              0.629     0.495     0.555  485
18:31:29 | INFO    | stage4 | Random top-1 baseline: 0.304 | best metric: self_consistency (0.223)
18:31:29 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-fever/outputs/tables/localization_summary.csv
  ✓ run_localize done in 0.1 min


============================================================
  run_repair
============================================================
18:31:30 | INFO    | stage5 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
18:31:30 | INFO    | stage5 | Dataset: fever (env: FEVEREnv)
18:31:30 | INFO    | stage5 | 485 failed x 126 strategies x 3 seeds = 183330 result rows (actual GPU runs are far fewer: dedup)
18:31:32 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-21 18:31:35.504498: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-21 18:31:35.577309: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-21 18:31:46 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-21 18:31:47 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-21 18:31:47 [model.py:1678] Using max model len 8192
INFO 07-21 18:31:48 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-21 18:31:48 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  9.85it/s]
INFO 07-21 18:31:49 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-21 18:31:50 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=66744) INFO 07-21 18:32:09 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=66744) INFO 07-21 18:32:09 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:48233 backend=nccl
(EngineCore pid=66744) INFO 07-21 18:32:09 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=66744) INFO 07-21 18:32:10 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=66744) INFO 07-21 18:32:11 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=66744) INFO 07-21 18:32:11 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=66744) INFO 07-21 18:32:11 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=66744) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=66744) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.19s/it]
(EngineCore pid=66744) INFO 07-21 18:32:18 [default_loader.py:384] Loading weights took 6.01 seconds
(EngineCore pid=66744) INFO 07-21 18:32:23 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.405811 seconds
(EngineCore pid=66744) INFO 07-21 18:32:32 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=66744) INFO 07-21 18:32:32 [backends.py:1111] Dynamo bytecode transform time: 8.18 s
(EngineCore pid=66744) INFO 07-21 18:32:36 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.142 s
(EngineCore pid=66744) INFO 07-21 18:32:36 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=66744) INFO 07-21 18:32:36 [monitor.py:48] torch.compile took 12.53 s in total
(EngineCore pid=66744) INFO 07-21 18:32:39 [monitor.py:76] Initial profiling/warmup run took 3.02 s
(EngineCore pid=66744) INFO 07-21 18:32:40 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=66744) INFO 07-21 18:32:40 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=66744) INFO 07-21 18:32:43 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=66744) INFO 07-21 18:32:44 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=66744) INFO 07-21 18:32:44 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=66744) INFO 07-21 18:32:44 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=66744) INFO 07-21 18:32:44 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.00it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.35it/s]
(EngineCore pid=66744) INFO 07-21 18:32:56 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=66744) INFO 07-21 18:32:56 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=66744) INFO 07-21 18:32:56 [core.py:283] init engine (profile, create kv cache, warmup model) took 33.06 seconds
(EngineCore pid=66744) INFO 07-21 18:32:58 [vllm.py:790] Asynchronous scheduling is enabled.
18:32:58 | INFO    | stage5 | --- seed 0 ---
18:37:58 | INFO    | stage5 | seed 0: 64/485 questions | 574 GPU repairs so far | 5.0 min elapsed
18:43:25 | INFO    | stage5 | seed 0: 128/485 questions | 1168 GPU repairs so far | 10.4 min elapsed
18:48:58 | INFO    | stage5 | seed 0: 192/485 questions | 1791 GPU repairs so far | 16.0 min elapsed
18:54:54 | INFO    | stage5 | seed 0: 256/485 questions | 2465 GPU repairs so far | 21.9 min elapsed
19:00:28 | INFO    | stage5 | seed 0: 320/485 questions | 3083 GPU repairs so far | 27.5 min elapsed
19:06:04 | INFO    | stage5 | seed 0: 384/485 questions | 3712 GPU repairs so far | 33.1 min elapsed
19:11:41 | INFO    | stage5 | seed 0: 448/485 questions | 4334 GPU repairs so far | 38.7 min elapsed
19:15:25 | INFO    | stage5 | seed 0: 485/485 questions | 4740 GPU repairs so far | 42.5 min elapsed
19:15:25 | INFO    | stage5 | --- seed 1 ---
19:20:34 | INFO    | stage5 | seed 1: 64/485 questions | 5319 GPU repairs so far | 47.6 min elapsed
19:26:00 | INFO    | stage5 | seed 1: 128/485 questions | 5910 GPU repairs so far | 53.0 min elapsed
19:31:35 | INFO    | stage5 | seed 1: 192/485 questions | 6531 GPU repairs so far | 58.6 min elapsed
19:37:38 | INFO    | stage5 | seed 1: 256/485 questions | 7200 GPU repairs so far | 64.7 min elapsed
19:43:08 | INFO    | stage5 | seed 1: 320/485 questions | 7819 GPU repairs so far | 70.2 min elapsed
19:48:43 | INFO    | stage5 | seed 1: 384/485 questions | 8444 GPU repairs so far | 75.7 min elapsed
19:54:16 | INFO    | stage5 | seed 1: 448/485 questions | 9060 GPU repairs so far | 81.3 min elapsed
19:58:04 | INFO    | stage5 | seed 1: 485/485 questions | 9467 GPU repairs so far | 85.1 min elapsed
19:58:04 | INFO    | stage5 | --- seed 2 ---
20:03:12 | INFO    | stage5 | seed 2: 64/485 questions | 10043 GPU repairs so far | 90.2 min elapsed
20:08:40 | INFO    | stage5 | seed 2: 128/485 questions | 10636 GPU repairs so far | 95.7 min elapsed
20:14:15 | INFO    | stage5 | seed 2: 192/485 questions | 11258 GPU repairs so far | 101.3 min elapsed
20:20:15 | INFO    | stage5 | seed 2: 256/485 questions | 11921 GPU repairs so far | 107.3 min elapsed
20:25:53 | INFO    | stage5 | seed 2: 320/485 questions | 12541 GPU repairs so far | 112.9 min elapsed
20:31:32 | INFO    | stage5 | seed 2: 384/485 questions | 13169 GPU repairs so far | 118.6 min elapsed
20:37:04 | INFO    | stage5 | seed 2: 448/485 questions | 13790 GPU repairs so far | 124.1 min elapsed
20:40:48 | INFO    | stage5 | seed 2: 485/485 questions | 14194 GPU repairs so far | 127.8 min elapsed
20:40:48 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 14194 (vs 183330 result rows — dedup saved 92%)
20:40:48 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-fever/outputs/repairs/results.jsonl
(EngineCore pid=66744) INFO 07-21 20:40:48 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=66744) INFO 07-21 20:40:48 [core.py:1233] Shutdown complete
[rank0]:[W721 20:40:48.590841193 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
  ✓ run_repair done in 129.4 min


============================================================
  run_eval
============================================================
20:40:53 | INFO    | stage6 | config=config/config_colab_fever.yaml  base=/content/drive/MyDrive/agent-repair-fever
20:40:58 | INFO    | stage6 | rows: 184785 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%    95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step      1.2  0.6-1.7%         157            2.68             32.8
                                                       full_restart      2.8  2.0-3.7%         221            3.90             68.0
                                               oracle_targeted__bt2      3.2  2.3-4.0%         222            3.91             68.0
                                     oracle_targeted__bt2__informed      2.9  2.1-3.8%         224            3.97             68.0
                                          oracle_targeted__informed      2.5  1.8-3.4%         228            4.02            100.0
                                    unc__max_token_prob_max__argmax      1.9  1.2-2.7%         149            2.55             21.2
                               unc__max_token_prob_max__argmax__bt2      2.9  2.1-3.8%         186            3.24             33.6
                     unc__max_token_prob_max__argmax__bt2__informed      2.6  1.9-3.4%         184            3.24             33.6
                          unc__max_token_prob_max__argmax__informed      2.5  1.7-3.3%         148            2.58             21.2
                          unc__max_token_prob_max__cascade_gradient      1.2  0.6-1.7%         165            2.87             32.2
                     unc__max_token_prob_max__cascade_gradient__bt2      2.9  2.1-3.8%         200            3.49             42.5
           unc__max_token_prob_max__cascade_gradient__bt2__informed      2.3  1.5-3.0%         201            3.57             42.5
                unc__max_token_prob_max__cascade_gradient__informed      2.1  1.4-2.8%         168            2.96             32.2
                          unc__max_token_prob_max__cascade_upstream      2.9  2.1-3.8%         186            3.24             33.6
                     unc__max_token_prob_max__cascade_upstream__bt2      3.2  2.3-4.0%         210            3.72             48.7
           unc__max_token_prob_max__cascade_upstream__bt2__informed      3.1  2.2-4.0%         210            3.74             48.7
                unc__max_token_prob_max__cascade_upstream__informed      2.6  1.9-3.4%         184            3.24             33.6
                          unc__max_token_prob_max__cascade_weighted      2.5  1.7-3.3%         200            3.53             30.3
                     unc__max_token_prob_max__cascade_weighted__bt2      3.1  2.3-4.0%         217            3.81             60.2
           unc__max_token_prob_max__cascade_weighted__bt2__informed      2.6  1.9-3.4%         220            3.89             60.2
                unc__max_token_prob_max__cascade_weighted__informed      2.5  1.8-3.4%         199            3.55             30.3
                  unc__max_token_prob_max__earliest_above_threshold      2.2  1.5-3.0%         178            3.09             25.2
             unc__max_token_prob_max__earliest_above_threshold__bt2      3.1  2.3-4.0%         205            3.61             45.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed      2.7  1.9-3.5%         208            3.68             45.8
        unc__max_token_prob_max__earliest_above_threshold__informed      2.3  1.6-3.2%         176            3.11             25.2
                                      unc__max_token_prob_max__topk      2.8  1.9-3.6%         196            3.43             29.7
                                 unc__max_token_prob_max__topk__bt2      3.4  2.5-4.4%         215            3.78             56.3
                       unc__max_token_prob_max__topk__bt2__informed      2.9  2.1-3.8%         217            3.84             56.3
                            unc__max_token_prob_max__topk__informed      2.3  1.6-3.1%         194            3.45             29.7
                                            unc__perplexity__argmax      1.9  1.2-2.7%         153            2.60             17.1
                                       unc__perplexity__argmax__bt2      3.0  2.1-3.9%         187            3.23             35.7
                             unc__perplexity__argmax__bt2__informed      2.9  2.1-3.8%         187            3.29             35.7

In [42]:
# View cascade-aware results
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())

import pandas as pd
results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)

import glob
from IPython.display import display, Image
figs = sorted(glob.glob(os.path.join(cfg.path('figures'), '*.png')))
for f in figs:
    print(f'\n--- {os.path.basename(f)} ---')
    display(Image(filename=f, width=800))

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,1.2,0.6-1.7%,157,2.68,32.8
1,full_restart,2.8,2.0-3.7%,221,3.90,68.0
2,oracle_targeted__bt2,3.2,2.3-4.0%,222,3.91,68.0
3,oracle_targeted__bt2__informed,2.9,2.1-3.8%,224,3.97,68.0
4,oracle_targeted__informed,2.5,1.8-3.4%,228,4.02,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,3.4,2.5-4.3%,208,3.68,49.3
123,unc__verbalized_confidence__topk__bt2__informed,2.5,1.8-3.4%,211,3.75,49.3
124,unc__verbalized_confidence__topk__informed,2.5,1.8-3.4%,185,3.28,29.9
125,uncertainty_ensemble_any,9.6,8.1-11.1%,10600,185.46,93.6
126,oracle_targeted,2.5,1.7-3.3%,221,3.88,100.0